### ISSUE TITLE
The future of recarrays

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#1552]
Numpy recarrays have some support in some code paths.  Where this occurs, it requires some non-trivial code to handle the recarray.  

Is there any reason to continue to support recarrays given pandas is a requirement?  If not, then these can be cleaned up when the related code is touched.

One example I encountered:

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/tsatools.py#L66-L70

**Comment by josef-pkt** [comment]
I just saw in #3947 that the VAR test suite is based on recarrays/structured dtype, loaded from datasets macrodata.

So we do have support of it inside the models, and it's only a unicode pickling error with recent pandas and numpy that caused problems (on py2.7).

**Comment by jbrockmendel** [comment]
We should consider more proactively removing/deprecating support for recarrays in some areas of the code.  In particular, while working on `sm.tools.tools.categorical` (trying to address #1342) I'm seeing a lot of complication and some TODOs being caused by recarray handling (along with 1342 itself being caused by a recarray check done incorrectly)
