### ISSUE TITLE
statsmodels.tsa.ar_model.ARResults.predict

### ISSUE THREAD

**Issue by eoseubert** [statsmodels/statsmodels#1651]
Hi,

I don't believe that the confint parameter is being implemented in http://statsmodels.sourceforge.net/devel/generated/statsmodels.tsa.ar_model.ARResults.predict.html

ARResults.predict(start=None, end=None, dynamic=False)

**Comment by GuillaumeLeclerc** [comment]
Hello,

I think it is still not implemented. It has been closed though. Any explanation ? Or Am I doing something wrong (I have an instance of `ARResultsWrapper` and according to the docs it's on `ARResults`. I looked at the code and I'm not sure how to "UnWrap" it.

Thank you for your help

**Comment by josef-pkt** [comment]
@GuillaumeLeclerc  The preferred model is now `SARIMAX` which has `get_prediction` with more features.
Most likely enhancing `AR` will not be a priority anymore and might eventually be deprecated, unless someone comes up with a good reason to keep it.

**Comment by GuillaumeLeclerc** [comment]
Ok thank you. It might be good to have the documentation up to date to avoid confusion I think. If the argument is not supported it should not be there.

**Comment by GuillaumeLeclerc** [comment]
@josef-pkt Sorry to come back to you. I tried what you suggested and I just can't fit my model with SARIMAX (I also tried with ARMA and ARIMA), even though it is perfectly fine with AR (and I get pretty good predictions on my testing data)

Here what I have
```python
fit_AR = AR(training_data).fit(MAX_LAG_MODELING).params.values
print(fit_AR)
fit_SARIMAX = SARIMAX(training_data, order = (1, 0, MAX_LAG_MODELING)).fit(disp = False)
print(fit_SARIMAX)
```

The second line prints the weights correctly (and they make sense when you compare them with the data).
On the other hand the second line fails. From my understanding of these models. The two should be perfectly equivalent but maybe I'm wrong.

For the third line I get 
```
raise ValueError('non-invertible starting MA parameters found'
ValueError: non-invertible starting MA parameters found with `enforce_invertibility` set to True.
```

I don't see how with  only one AM parameter I should get a non invertible filter (maybe if the weights becomes zero but then there might be an issue in the solver (I tried others solvers without any luck).

I tried tweeking the params and sometimes I get a different error. It says that the data is not stationary. Which is false according to the adf test.

I can't lower my `MAX_LAG_MODELING` because this is the seasonality of my data.

I hope there is a way to get these confidence intervals. Thank you very much for your help

**Comment by josef-pkt** [comment]
You specified a MA model not an AR, ARMA(ar_order, differencing, ma_order)
an AR as ARMA would be order = (MAX_LAG_MODELING, 0, 0)

Given that you have seasonal data, you could try the seasonal ARMA specification, which would require fewer parameters than a full length AR. See docstring and example notebooks for SARIMAX

**Comment by GuillaumeLeclerc** [comment]
I'm sorry, but it's still not working. It is taking 100% of my CPU and never find a solution. With the AR model it takes less than a second. I don't understand this difference since I only have AR parameters. Is it normal ?
