### ISSUE TITLE
GLM aic bic inconsistency

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1733]
writing unit tests for GLM aic and bic compared to Stata

our aic agrees with `estat ic` but not with the one in `ereturn list`
our bic agrees with `ereturn list` but not with `estat ic`

???

`GLMResults aic` uses the usual `llf` based definition
`GLMResults bic` uses the deviance based definition.

Proposal 
make both llf based, for comparability and consistency across MLE models (e.g. discrete)
add `aic_dev` and `bic_dev` for users that want the `deviance` based ic

AFAIK: they should only differ by a constant within same model (llf of saturated model), and it won't affect comparison within the same model for different df_model.

**Comment by ledmonster** [comment]
+1

**Comment by josef-pkt** [comment]
bump for 0.10: the inconsistency in definition of bic is just ugly (comparing GLM gaussian to ols/wls)

**Comment by JoonsukPark** [comment]
So it seems that this issue hasn't been resolved. I looked at the definition of llf and deviance in the GLM api and it seems that either works fine. The problem is actually about the usage of df_resid instead of (df_model+1) that should have been used in that place -- that is the source of discrepancies between the R version of BIC and the statsmodels' one. For consistency, however, it would be better to just use llf in the definition of BIC.

**Comment by josef-pkt** [comment]
The problem is that we have unit tests against Stata that fail in PR #6568

I never looked at the formula specifically for the deviance case, but the use of `df_resid` looks now strange/wrong to me.

We need to check whether there was a problem in Stata or if the unit tests hide some problems, some `decimal` in the asserts are very low.

**Comment by josef-pkt** [comment]
Stata docs matches our computation with df_resid = N - k
BIC = D**2 - (N - k) ln(N)

But this still looks wrong.
e.g AFAIK, deviance is supposed to be the analogue of RSS in the linear model, but there we use `k` and not df_resid,
e.g. https://en.wikipedia.org/wiki/Bayesian_information_criterion
and `tools.eval_measures.bic_sigma`

I don't find a reference for the deviance based bic.

**Comment by josef-pkt** [comment]
BIC in Stata and statsmodels is not wrong in terms of ranking models.

Because of the linearity in `k`, using df_resid just adds a constant that is not model (selection of exogs) dependent for a given sample (of given size nobs=N). 

BIC = D**2 - (N - k) ln(N) = D**2 + k ln(N) - N ln(N)

(I might have seen this version before in some references with the N log N term)

The problem is "only" the inconsistency in the definition with other information criteria and that we cannot compare bic across models (i.e. across model classes).

**Comment by JoonsukPark** [comment]
Yes, that is true; ranking of the models would not change under the Stata-style BIC. I only raised this issue because the R-style definition is a more common one (at least what I have seen from the literature) and I thought it would be better to adopt such a thing. Personally, I think the Stata-style definition is a bit weird because it does not make it clear that BIC penalizes models based on the complexity (i.e., number of model parameters). Either way, however, BIC will do its job.

**Comment by josef-pkt** [comment]
One possible difference between likelihood based and divergence based aic is likely in dispersion for models like Poisson and Binomial.
The likelihood version does not include excess dispersion, scale is assumed to be 1.
I guess that the divergence based aic does not use the scale=1 assumption.

see also #1802   https://github.com/statsmodels/statsmodels/issues/1802#issuecomment-560011437
#6516 for TIC (similar to robust cov_type)

The main way forward is to add a method where we can add several options for different definitions of the information criteria. Then we don't have to rely so much at the attributes that cannot have options, and we could deprecate the cases that we don't like.

**Comment by JoonsukPark** [comment]
OK, I will try to commit something like that sooner or later.
