### ISSUE TITLE
how to specify columns in conf_int()?

### ISSUE THREAD

**Issue by andreas-h** [statsmodels/statsmodels#1956]
On statsmodels 0.5, the docstring to the `RegressionResultsWrapper.conf_int()` method states

```
cols : array-like, optional
    `cols` specifies which confidence intervals to return
```

However, when I use this kwarg as

```
result2.conf_int(cols=["omega"])
```

I get

```
IndexError: arrays used as indices must be of integer (or boolean) type
```

When trying an integer /col/, 

```
result2.conf_int(cols=[1])
```

I get

```
ValueError: Shape of passed values is (2, 1), indices imply (2, 37)
```

So somehow I'm not using this kwarg correctly; most probably due to my interpretation of the docstring.

**Comment by josef-pkt** [comment]
I'm not sure we really need to support column selection. I thought it is mostly noise (unnecessary code complication) in cov_params.

However, it might also become useful when we add dropped variables to the results.

**Comment by ssakatausa** [comment]
Using version 0.13.0 of statsmodels, I encountered the same problem as andreas-h. Inspecting the source codes, I found that the problem is caused by a single line in base/data.py.  Attached is a patch for fixing the problem.[
[data.py.txt](https://github.com/statsmodels/statsmodels/files/7452717/data.py.txt)
](url)

**Comment by bashtage** [comment]
@ssakatausa Do you want to submit a PR?

**Comment by ssakatausa** [comment]
Sorry, my "fix", which I have already removed from this thread, was totally incorrect. But I think the problem is essentially in attach_columns in data.py defined between lines 553 and 560. The function assumes that the given argument, _result_, is an array whose rows correspond to self.param_names. But when conf_int is called with a non-None _cols_ argument, _result_ only contains the elements specified by _cols_, so that self.param_names contains the names of the elements not contained in _result_.  This makes the dimension mismatch between _result_ and self.param_names. Unfortunately, I do not understand the structure of the statsmodels package enough to find the best way to address the issue (without breaking many other modules). Anyone has a good idea?

**Comment by ssakatausa** [comment]
I went over the source code to see how the confidence intervals are calculated and processed to yield a pandas dataframe. Here are my findings. First, the confidence intervals are calculated for all parameters, regardless of what are specified in _cols_, and then the parameters not in _cols_ are stripped off from the result if _cols_ is not None. So, _cols_ has absolutely no effects on the compuation burden (well, the burden is negligible in any case, though). Second, the pandas dataframe of conf_int's output is generated by some wrappers, which essentially add row names to the matrix containing the upper and lower bounds of the confidence intervals. The problem is that the wrappers are not written in such a way that they can access _cols_. To make _cols_ work correctly, we would need to do something a little tricky in a way or another, at the cost of making the code more difficult to maintain.  So, I did not touch the code.

A good news is that what _cols_ option is supposed to do can be done easily by using .loc and .iloc methods of pandas dataframe objects. E.g.:
`
result.conf_int(0.01).loc[['smoker', 'nprevist']]
`
or
`
result.conf_int(0.05).iloc[[0, 2]]
`
So, I propose dropping the _cols_ option from the conf_int method.
