### ISSUE TITLE
SUMM: follow-up state space kalman filter merge

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2252]
**soon**

- [x] `specification` dict should be a Bunch, IMO (I don't have tab completion for dict keys)
- [ ] related to `specification` dict: `_init_kwds` for recreating model (generic, not used in tsa yet ?) PR WIP #2259
- [x] unit tests for t_test, wald_test (use testing helper function) PR #2258

- [ ]  wrapper: I just saw this. `MLEResults` and `SARIMAXResults` do explicit wrapping of `params` and similar, instead of using the wrapper class as other models. e.g. `res.params` is pandas.Series, `res._params` is np array. `ARIMA` is using `arima_model.ARMAResultsWrapper`

it looks like there might be trailing whitespace, rebase didn't clean those up. 
(my editor removed some whitespace in #2258)

**later**

- [ ] check precision issues found in some unit tests https://github.com/statsmodels/statsmodels/pull/1698#issuecomment-74037056
- [x] `cov_type`, `use_t`

**design, possible refactoring**

mostly undecided

- [ ] `*args, **kwds` in loglike, score and similar, see comment below
- [ ]  minimize holding of "state" if it's not needed (remove from methods that don't require it)
- [ ]  memory layout, c or fortran contiguous, see todo and comments
- [ ]  single precision calculation: pretty large failure on Travis and most likely will also have problems on other machines, check or ignore (recommendation: Don't do that!)

**Comment by josef-pkt** [comment]
two details

- I'm not able to run the skipped test with `nosetests --no-skip`. I don't know how this needs to be done.
- for t_test, wald_test: to fix: define `df_resid`, delete `mlemodel.MLEResults.cov_params` to use inherited.

**Comment by ChadFulton** [comment]
Should I make individual issues for different TODO items, or group them here? Possibly the single-precision issue deserves its own issue since it will presumably be long-lived until someone has the motivation to investigate and fix it.

**Comment by josef-pkt** [comment]
I started SUMM issues as a table of content and for general discussion and overview. If there is more specific information (besides a few line summary), then we can open another issue. Also it's good to have separate issues that can be closed when we actually work on it, also for the record and easier searching for changes.
(The biggest SUMM issue is cov_type which has lots of separate issues for specific implementation.)

**Comment by josef-pkt** [comment]
right now we don't need to open issues for things that we will fix right away. 
I have the t_test/wald_test fix almost ready. (but need to pick up now the kids from school)

**Comment by josef-pkt** [comment]
it looks like `SARIMAXStatsmodelsTests` are not run.
`nosetests <path to>/test_sarimax.py` runs 305 tests
if I change name to `TestSARIMAXStatsmodels`   leading `Tests` in name, then I get 312 tests (including one I added) 

(found because: to verify that my test is run, I changed the numbers to cause a failure, but the failure never showed up.)

**Comment by josef-pkt** [comment]
It took me a while to figure out how to calculate the right `score` to check convergence.

*args and **kwargs in loglike, score, and similar are different from other models.
Do we want to refactor this at some point?  
(both have advantages and disadvantages, but having to distinguish transformed and untransformed as user is confusing.)

```
        nargs = len(args)
        if nargs < 1:
            kwargs.setdefault('average_loglike', True)
        if nargs < 2:
            kwargs.setdefault('transformed', False)
        if nargs < 3:
            kwargs.setdefault('set_params', False)
```

I was checking the score at the optimum and got large numbers.
no args and keyword transformed=True

**Comment by josef-pkt** [comment]
@ChadFulton  question on actually used number of observations:
t_test, wald_test require a df_resid attribute even if it's not used.

Is there a simple way to get the number of observations used in estimation, excluding for example the initial observations differenced away?

**Comment by ChadFulton** [comment]
> args and *kwargs in loglike, score, and similar are different from other models.
Do we want to refactor this at some point?

I agree, that would be a good idea, lets put it on the TODO list. I'm sure there's a better way to do it, but it's a part that I haven't looked at since I got it "working".

> Is there a simple way to get the number of observations used in estimation, excluding for example the initial observations differenced away?

The way it works right now for SARIMAX is as follows:

If `simple_differencing=False`, then all observations are used for estimation, and `mod.nobs` is accurate, even if there is an order-of-integration in the model. However, in that case, we typically ignore the likelihood for a number of periods equal to the order of integration. Should those count in a d.o.f. parameter? I don't know.

If `simple_differencing=True`, then the actual `mod.endog` (and possibly `mod.exog`) arrays are replaced in the constructor with the differenced versions. So still, here, `mod.nobs` gives the true number of observations used in estimation. The original datasets are held in `mod.orig_endog` (and possibly `mod.orig_exog`).

**Comment by josef-pkt** [comment]
df_resid:
For MLE in general, I would say the number of observations in loglike evaluation (len(loglike_obs))
which in this case, given the change in `endog`,  we would only have in one case `n_ignores` (?) to subtract from nobs. (or for simplicity we just stick with nobs.

**Comment by ChadFulton** [comment]
A couple of miscellaneous things that need to be done:

- [ ] Add unit tests for `standardized_forecasts_error` and `kalman_gain`
- [ ] Cache (or do something about) foreign files in the notebooks
- [ ] I renamed `params_included` to `param_terms`, but need to make it an OrderedDict

**Comment by ChadFulton** [comment]
Two new miscellaneous issues that came up:

- `exog_names` breaks on Pandas objects in SARIMAX
- Adding `self.data.param_names = self.param_names` to the MLEModel constructor causes ad-hoc models to fail since the names then aren't specified at construction time.

I will have PRs that fix them in a moment.

**Comment by ChadFulton** [comment]
I'm hoping to revisit this issue / the plan for state space models in 0.7.

The following PRs / issues are currently open (see also #2467):

1. #2330 - (Issue) design question about whether or not to allow ad-hoc state space models
2. #2356 - (PR, ENH) Add `cov_type` to MLEModel results, improve standard errors
3. #2431 - (PR, ENH) State space diagnostics
4. #2432 - (PR, ENH) Unobserved components models
5. #2434 - (PR, ENH) Add Kalman smoother
6. #2461 - (PR, FIX) `standardized_forecasts_error` had a bug with Scipy 0.11
7. #2473 - (PR, ENH) decouple MLE from state space / remove triple inheritance (see also #2265, an issue describing the decoupling)
8. #2488 - (PR, ENH) add initialization option as keyword arguments to KalmanFilter
9. #2489 - (PR, REF) change specification from dict to Bunch in SARIMAXResults

-------------

The only PR that I suppose *must* be in 0.7 is #2461, fixing the standardized forecast errors. However, here is what I propose.

1. Review / merge bug fixes: #2461(fix the standardized forecast errors bug)
2. Review / merge simple PRs: #2489 (dict -> Bunch), #2488 (initialization in init kwargs)
3. Review / merge #2356: add covariance matrix improvements

So far these should be relatively easy to review and merge. Only #2356 has any substantial changes. 

Now, there are two design decisions in the list above, and it seems to me that they should be addressed prior to 0.7, so that we don't immediately introduce relatively big changes in 0.8:

4. Decide whether or not to include ad-hoc models (see #2330). My current thought is that they should not be supported in the base `MLEModel` class, even if we add them later in a subclass (e.g. `AdHocModel` or whatever). If we do decide to drop them, that is addressed in #2473.
5. Review / discuss / merge #2473: decouple MLE from state space. My feeling is that the PR is actually pretty straightforward, and doesn't have any particularly challenging questions that need to be addressed, although there are probably some changes that would need to be made.

If we did all of these things, then in addition to the things mentioned above, the various PRs will also give us the following:

- `_init_kwds` for recreating model should be fully consistent with base models (no need to issue a warning in SARIMAX for alternate initializations or put endog and exog in the `_init_kwds` dict).
- Wrapper classes will be used for the Results classes.
- `cov_type` will be allowed, along with good estimation methods (`opg` and `oim`) and a robust / QMLE option
- `*args` has already been removed from everywhere feasible, and `**kwargs` has been pared down where possible and documented elsewhere.

**Comment by ChadFulton** [comment]
Finally, the remaining PRs:

- #2431 - (PR, ENH) State space diagnostics
- #2432 - (PR, ENH) Unobserved components models
- #2434 - (PR, ENH) Add Kalman smoother

could wait until 0.8.

**Comment by josef-pkt** [comment]
@ChadFulton Thanks for the summary and update

I'll try to go over it tomorrow. I agree that we should merge the fixes since this hasn't been released yet, and we want to get some of the refactoring before the release.
(I was hoping to start merging 0.8 PRs, but it might not happen before I fly to Europe next weekend.)

**Comment by josef-pkt** [comment]
the first three are easy to merge #2461 #2489  #2488 rebasing is mainly cosmetic

I will go over cov_type #2356 during the next few hours,

**Comment by josef-pkt** [comment]
#2356 is also merged

#2330 ad hoc models: I read the discussion again. I think we shouldn't allow them, or at least not advertise them and discourage their use until further notice. 
We can leave some refactoring for 0.8. It will be the first release with `statespace` and I expect that we get some feedback, and assume we will still have ongoing "maturing" during 0.8 and will get additional experience based on the additional models coming in with the GSOC project.

#2473 This is mostly internal, and I don't have time or I'm too impatient right now to review this. I will merge it based on your recommendation. 
Because test coverage is pretty good and you have several models on top of it, I guess mergin it should be pretty safe. However, I guess it won't affect endusers much and will affect mainly developers, so merging it for 0.7 or right after tagging for 0.8 won't make much difference.

I also assume we want to merge it very soon, so you can rebase the new models on top of it.

Lot's of guesses based on insufficient review. (I need to go pack my suitcase :)

**Comment by josef-pkt** [comment]
@ChadFulton  One more for 0.7: Can you check whether the release notes need an update, and open a PR if necessary? Thanks

**Comment by ChadFulton** [comment]
I think everything discussed in this issue has been resolved / merged. We could probably close, unless it's handy to keep open for some reason.

**Comment by josef-pkt** [comment]
I read through this again. There might be some details left to look at, but this is pretty much done.

So closing. We can still find it as reference.
