### ISSUE TITLE
BUG/TST statespace SARIMAX test failure on i386 Ubuntu

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2267]
all 32 bit Ubuntu i386 are red

one failure: nan in bse

```
======================================================================
FAIL: statsmodels.tsa.statespace.tests.test_sarimax.TestFriedmanStateRegression.test_bse
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/buildd/statsmodels-0.7.0~ppa27~revno/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/tsa/statespace/tests/test_sarimax.py", line 425, in test_bse
    atol=1e-1,
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 607, in assert_array_compare
    chk_same_position(x_isnan, y_isnan, hasval='nan')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 587, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.1

x and y nan location mismatch:
 x: array(nan)
 y: array([ 0.039903])
```

**Comment by josef-pkt** [comment]
@chadfulton   Do you know what problems this could be, and how to fix it?

It is 32 bit specific, but I don't have the test failure on 32bit python on a Windows 64bit computer.
Andm it's the only failure on those machines, so I guess it must be a special case problem.

**Comment by ChadFulton** [comment]
This is bizarre, since there are two tests in the `test_bse` function and only the second one fails. I don't have a 32-bit system to hand, but I'll set up a VirtualBox and see if I can replicate.

**Comment by ChadFulton** [comment]
> This is bizarre, since there are two tests in the test_bse function and only the second one fails.

Looking closer at the test above, it was actually the first one that failed. To be clear, the test in question is:

```python
def test_bse(self):
    assert_allclose(
        self.result.bse[0], self.true['se_ar_oim'],
        atol=1e-1,
    )
    assert_allclose(
        self.result.bse[1], self.true['se_ma_oim'],
        atol=1e-4,
    )
```

The first assert is the standard error of the of the AR parameter, the second is the MA parameter. The failure above shows that there is a NaN in the AR parameter, and it is unknown what the standard error of the MA parameter is (NaN or otherwise).

-------------

I have setup a Ubuntu 14.10 i386 (32 bit) VirtualBox and installed Anaconda + Statsmodels master. For this setup, the first assert (AR BSE) passes, and the second assert (MA BSE) fails with the following error:

```
======================================================================
FAIL: statsmodels.tsa.statespace.tests.test_sarimax.TestFriedmanStateRegression.test_bse
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fulton/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/fulton/src/statsmodels/statsmodels/tsa/statespace/tests/test_sarimax.py", line 429, in test_bse
    atol=1e-4,
  File "/home/fulton/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/fulton/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.0001

(mismatch 100.0%)
 x: array(0.01727489374662606)
 y: array([ 0.112519])
```

Furthermore, dropping into the debugger shows that the standard error of the variance parameter (not tested here) is `NaN`.

All of these issues come down to problems with `cov_params` and so ultimately problems with the Hessian calculation when using untransformed parameters.

-------------

The `cov_params_delta` are fine here, though, and will allow both asserts to pass. Given this and the `NaN`s  `local_level_model` issues, maybe we should only have `cov_params_delta` until I can do further testing on the direct method?

**Comment by josef-pkt** [comment]
Does the test suite pass if we switch the current default cov_params to cov_params_delta?
If it passes for you, then you could prepare a PR with that, and we see whether Travis and then the other test servers also have no failures.
(store cov_params_hessian as attribute or property, and assign `cov_params_default=cov_params_delta`)

Did you see anything that might be 32bit specific?  Are some values in the problem very strange, large numbers in Hessian, or very unequal numbers?

Another thing I tried in my playing with some of the Stata examples is to run an additional optimization, fit with newton. The score (with correct transformed option) was very small, but the numbers didn't get closer to Stata.

I wanted to say:
Also, given that there is only one failure,  we could use the hessian by default, and tell users to switch to cov_params_delta if the hessian fails, but we don't have `cov_type` yet.

Since I'm starting to get tired with 0.7, we find a solution that works now and warn that `cov_type` will be refactored in 0.8 because hessian calculations are not yet robust enough.
I will briefly look at the example tomorrow to see if I can see anything weird on my computer.

**Comment by ChadFulton** [comment]
It appears there may be a scale issue of some kind - when I replace `exog` with `exog / 10.`, I get much closer values on the 32 bit system, and the tests could pass (although I would still have to slightly reduce the precision on the MA BSE test).

On the 64 bit system I can start getting some strange results when I replace `exog` with `exog * 2000.`.

I have not considered scaling issues at all so far. I can take a look into it, but it might take a while to figure out all the places it might be causing problems. What are your thoughts?

**Comment by josef-pkt** [comment]
If we can get away with rescaling the exog to have the tests pass, then we do this as a first solution.
Investigating why or where scaling issues create problems is then for later, 0.8 or so

We have scaling issues in some non-linear models like Poisson or NegativeBinomial. I have an internal rescaling function that I used to make a Poisson or NegativeBinomial test pass.
I expect support for some optional rescaling in discrete models in the near future, but for now it's up to the user.

I will also look soon at the example, I just finished another bug fix PR.

**Comment by josef-pkt** [comment]
you could try to scale both endog and exog, they both show a similar or the same trend.

question: Are the ar and ma coefficient estimates invariant to linear transformation of endog and exog? (besides numerical noise)
I guess they should be, except I don't know how initial conditions are handled.
the variance/scale will change quadratic/proportionally, if we change the the scale endog.

**Comment by josef-pkt** [comment]
One possible source for problem for unequal scales can be the stepsize in the numerical hessian calculation. You fixed it at 1e-9, and it might be worth a look to see how sensitive the results are to changing the epsilon, or using the default epsilon.

The variance looks much larger the the ar and ma parameters.
However, in this case you don't have directly a parameter for exog in the hessian calculation, so maybe that's not a good guess for problems in this case.

**Comment by ChadFulton** [comment]
This test is a little bit unique in the sense that the likelihood function is going to be slightly different when the regression effects are incorporated into the state vector with approximate diffuse initialization. For that reason, there's no particular reason that the likelihood function would be maximized at exactly the same parameters (and in fact the test notes that llf, aic, etc. are not tested since they are expected to be different), or that it would have exactly the same curvature there.

The AR and MA MLE parameters are not in an existing unit test for this particular case (TestFriedmanStateRegression), although I could add a test for them at a similarly low precision.

But it's not clear to me, now that I think about it, that the Stata-reported coefficients and standard errors are the correct results to test against. I suppose this is why the precision is so low in this test case.

The PR I submitted will allow the tests to pass (at least they do on my machines) and we could keep it as a sort of low-precision "look these models give reasonably close results even though they technically use different methods", or we could drop it altogether until I can get alternate results (not from Stata, but I could do it in R or possibly MATLAB).

**Comment by ChadFulton** [comment]
> One possible source for problem for unequal scales can be the stepsize in the numerical hessian calculation. You fixed it at 1e-9, and it might be worth a look to see how sensitive the results are to changing the epsilon, or using the default epsilon.

This is a good idea, thanks for mentioning it. I will add a note also to my Hessian refactoring PR.

**Comment by josef-pkt** [comment]
In general: even approximate unit tests against a similar but different algorithm are better than NO unit tests. It's still a check that the numbers are in the right neighborhood. 
And comments in the unit tests can remind us why we have low precision.
So I think adding low precision unit tests for the parameters would also be helpful.

Related: To catch refactoring changes, it might be useful in this cases to add a higher precision regression test, so we get a failure an alert if the numbers start to change or vary widely across machines. In this case that would be more important for the params if the standard errors have possibly a large numerical noise.

**Comment by ChadFulton** [comment]
> Does the test suite pass if we switch the current default cov_params to cov_params_delta?

Just to document this, the suite does not pass with `cov_params_delta`, even on the 64bit machine; there are 10-20 failures related to standard errors.

**Comment by ChadFulton** [comment]
> In general: even approximate unit tests against a similar but different algorithm are better than NO unit tests. It's still a check that the numbers are in the right neighborhood. 
And comments in the unit tests can remind us why we have low precision.
So I think adding low precision unit tests for the parameters would also be helpful.

I added the MLE parameters at quite low precision (`atol=1e-1, rtol=1e-1`). I will add a note to the test class describing what is going on.

**Comment by josef-pkt** [comment]
all green on Ubuntu python-xy testing

closing this
