### ISSUE TITLE
TypeError unexpected keyword argument 'missing_idx' when using Var.from_formula()

### ISSUE THREAD

**Issue by jamesonthecrow** [statsmodels/statsmodels#2347]
When I try to specify a VAR model from a formula I get an error about an unexpected keyword argument that seems to be a default.

```
import statsmodels.api as sm
import pandas
import numpy
import datetime

df = pandas.DataFrame(numpy.random.rand(100,4), columns=['A', 'B', 'C', 'D'])
df.index = pandas.DatetimeIndex(periods=100, freq='1D', start=datetime.datetime(2015,1,1))
model_spec = 'A ~ B + C'
var_model = statsmodels.tsa.VAR.from_formula(model_spec, df )
```

Produced the following error:

```
from_formula(cls, formula, data, subset, *args, **kwargs)
    148         kwargs.update({'missing_idx': missing_idx,
    149                        'missing': missing})
--> 150         mod = cls(endog, exog, *args, **kwargs)
    151         mod.formula = formula
    152 

TypeError: __init__() got an unexpected keyword argument 'missing_idx'
```

I think this is because the constructor for the var_model class doesn't take the same keyword arguments as the base model class.

**Comment by josef-pkt** [comment]
`from_formula` doesn't make much sense for VAR. VAR doesn't have `exog` explanatory variables, and all we need is the multivariate `endog`.

I think it should raise a NotImplementedError, I didn't even know time series models inherit from_formula.

Var is a different type of model than the base model because endog is multivariate, and AFAIR, there are other inherited methods that are not yet correctly overwritten in the subclasses.
