### ISSUE TITLE
What is the sigma2 term on SARIMAX model

### ISSUE THREAD

**Issue by hxu** [statsmodels/statsmodels#2507]
In the new functionality implemented by #2250, a model with seasonal components has a sigma2 variable added to it, as in Stata (see http://www.stata.com/manuals13/tsarima.pdf).  But the R implementation doesn't have this term (see https://www.otexts.org/fpp/8/9).  I've searched the literature but can't seem to find an explanation for what this term is.  Would someone be able to point me in the right direction?

**Comment by josef-pkt** [comment]
@ChadFulton

**Comment by ChadFulton** [comment]
The sigma2 output in the coefficients table is the estimate of the variance of the error term. Your second link provides the following specification for an SARIMA model:

![](https://www.otexts.org/sites/default/files/fpp/images/sarima2.png)

The e_t term (the error term) is assumed to be iid white noise, with variance sigma2.

From your link, it appears that R does estimate the sigma2 term, but it outputs it below the coefficient table rather than inside it.

```R
> fit <- Arima(h02, order=c(3,0,1), seasonal=c(0,1,2), lambda=0)
```

    ARIMA(3,0,1)(0,1,2)[12]                    
    Box Cox transformation: lambda= 0 

    Coefficients:
              ar1     ar2     ar3     ma1     sma1     sma2
          -0.1603  0.5481  0.5678  0.3827  -0.5222  -0.1768
    s.e.   0.1636  0.0878  0.0942  0.1895   0.0861   0.0872

    sigma^2 estimated as 0.004145:  log likelihood=250.04
    AIC=-486.08   AICc=-485.48   BIC=-463.28

My guess would be that they do this because the variance term can be concentrated out of the likelihood function, so it may not be calculated the same way as the coefficients and is put in a different spot

**Comment by hxu** [comment]
Okay, thanks for the quick response.  So the only reason that it's put into the coefficients table is because it's calculated in the same way, and not because it's part of the model specification.  Apologies if this is going off topic, but what kinds of diagnostics use the sigma term?

**Comment by josef-pkt** [comment]
I'm tagging it as a FAQ so general discussion is not off-topic.

**Comment by ChadFulton** [comment]
> Okay, thanks for the quick response. So the only reason that it's put into the coefficients table is because it's calculated in the same way, and not because it's part of the model specification.

It is part of the model's specification, in the sense that it is part of the specification of the error term, and contributes to the likelihood of the model (in fact, without this error term the model would not be a statistical model at all).

Rather than thinking of us putting it into the coefficients table because it's calculated the same way, it's more accurate to think of R as taking it out of the coefficients table because they calculate it differently.

> Apologies if this is going off topic, but what kinds of diagnostics use the sigma term?

The sigma term describes a fundamental characteristic (volatility) of the hypothesized random process. Nothing that I have done uses hypothesis tests to this parameter. In the #2431 diagnostics, standardized residuals are used to net out the variance (so that hypothesis tests can be run against a null of a Normal (0,1) distribution).

**Comment by hxu** [comment]
Got it, thanks for the explanation.

**Comment by josef-pkt** [comment]
FAQ issues stay open for future reference

**Comment by dciborow** [comment]
I am comparing an ARIMA model in Python that uses statsmodels (pmdarima) to SAS's PROC ARIMA. 

I am starting off with ARIMA(0,0,0), just to try and get the two implementations to be equal(ish). 

SAS calculates...
![image](https://user-images.githubusercontent.com/9027725/95140989-0f3db080-073e-11eb-8783-d6f02b995739.png)

While Python in Python the output includes the sigma2. 
![image](https://user-images.githubusercontent.com/9027725/95141025-28def800-073e-11eb-8abd-6faf21be30db.png)

It appears that the sigma is perhaps barely significant, but I believe including this term is changing the value of my std_err for my intercept. Is including this sigma2 why my std_err for my intercept is different?

**Comment by bashtage** [comment]
It is the innovation variance. It's standard error isn't always that
meaningful since we know it is greater than 0.

**Comment by bashtage** [comment]
The std error for the intercept is computed numerically.  In this case we have an analytical formula and the SAS se is exact while the stars models one has some numerical imprecision.

**Comment by dciborow** [comment]
Got it. Guess thats why turning off sigma2 reporting didn't get me to equal.

![image](https://user-images.githubusercontent.com/9027725/95142555-f46d3b00-0741-11eb-9f06-27905ee62a99.png)

**Comment by aksehra** [comment]
![InkedScreenshot 2022-05-01 180647_LI](https://user-images.githubusercontent.com/77278003/166159336-40d6abd7-b47c-4753-942e-2514b2cc65ec.jpg)
 In case of a computation using pmd.auto_arima where seasonal=False what does the value of sigma2 , coef = 5.7414 signify ? Is it related to the error term OR since the model is ARIMA (0,1,0) differenced once as d=1, is it value of the intercept/drift ?

**Comment by bashtage** [comment]
It is estimated variance of the residual in the model.
