### ISSUE TITLE
BUG: State space: Cholesky factorization with complex step derivatives

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#2514]
In multivariate state space models with variance parameters, complex step derivatives can fail because the Cholesky factorization (zpotrf) silently ignores the complex part. This is because zpotrf assumes a positive-definite matrix with, in particular, real entries on the diagonal. In this case the complex step derivative evaluates the derivative as zero since the likelihood doesn't change.

This doesn't affect any of the models developed so far (SARIMAX, UnobservedComponents) but it would affect OPG covariance matrix estimation of multivariate custom models.

**Comment by josef-pkt** [comment]
Is this a generic problem that the complex derivative matrices are not hermitian, or a specific problem with the LAPACK function that is used in the calculation of cholesky?

If it's the second, is there a simple example matrix to use as test case for improving numpy or scipy?

**Comment by ChadFulton** [comment]
I think it's a generic problem that complex derivative matrices when the variance terms are complex are not Hermitian, because the diagonals of a Hermitian matrix must be real. Here's an illustration of the problem:

```python
>>> np.linalg.cholesky([[9+5j]])
array([[ 3.+0.j]])
```

**Comment by josef-pkt** [comment]
OK, I'm a bit surprised then that LAPACK or whatever linalg package is used doesn't throw an exception.

Without an exception we might also have problems in other models that use Cholesky decomposition which are mainly mixed models right now. So, it might be useful to follow up on this more generally than the fix for the statespace models.

**Comment by ChadFulton** [comment]
Good idea - I'll submit an issue on Scipy and see what they think.

**Comment by josef-pkt** [comment]
one additional follow-up because I was recommending complex derivatives to MixedGLM.

Can we split the covariance matrix into a variance vector and the cholesky of the correlation matrix with real ones on the main diagonal (and compose ourselves) to replicate the correct behavior even for the use of complex derivatives?
(In GEE Kerby is separating variance from correlation parameters, but we don't do that in other places.)

**Comment by ChadFulton** [comment]
I've been trying to think about this, but I'm still not sure. I think what you're suggesting is:

Corr(X) = D^{-1/2} Cov(X) D^{-1/2}
D^{1/2} Corr(X) D^{1/2} = Cov(X)
D^{1/2} L (D^{1/2} L)* = Cov(X)
DL DL* = Cov(X)

where L is the Cholesky factorization of Corr(X), D is the diagonal matrix of variance terms, and D^{1/2} can be calculated using the principal square root of complex numbers. Then DL is a lower triangular matrix.

That sounds reasonable to me, but I guess I'm not quite confident asserting that it is always correct, since I don't recall enough complex analysis to know how the complex square root branch cut might affect things.

**Comment by ChadFulton** [comment]
Closed by #2515
