### ISSUE TITLE
predict function parameters of tsa.arima_model.ARIMA

### ISSUE THREAD

**Issue by hlin117** [statsmodels/statsmodels#2561]
The constructor, fit, and predict function definitions of ARIMA models is below:

- `ARIMA(endog, dates=None, freq=None, missing='none')[source] `
- `fit([maxlag, method, ic, trend, ...])  `
- `predict(params[, start, end, dynamic])`

Source: <a href="http://statsmodels.sourceforge.net/0.6.0/generated/statsmodels.tsa.arima_model.ARIMA.html#statsmodels.tsa.arima_model.ARIMA">here</a>.

Note that `predict` takes in another parameter, `params`, into its function call, which are the parameters it was just fit to.

Why is this function designed this way? Shouldn't it just be sufficient to specify which range of dates ARIMA should predict upon?

**Comment by jseabold** [comment]
You can predict with the results object returned from fit. It will call the
model predict with the appropriate params.

**Comment by jseabold** [comment]
Answered [here](https://stackoverflow.com/questions/31665256/python-statsmodels-params-parameter-for-predict-function-of-arima-models)

**Comment by hlin117** [comment]
Thanks for the answer!

Out of curiosity, what's the purpose of doing this? When I use scikit-learn models, each `fit` function modifies the model in question, but to facilitate chaining, each model also returns the `self` object.

**Comment by josef-pkt** [comment]
> Out of curiosity, what's the purpose of doing this?

Look at `dir(result_instance)` and compare with the results that scikit-learn produces.

We have a large number of results that become available after `fit`, many of those are lazy attributes/properties or methods that require a fit. It was easier and cleaner to add those in a separate class (which has it's own inheritance hierarchy).
scikit-learn is much more a "single purpose" library for prediction.

We can still chain, if we don't need to keep hold of the results instance.  `model.fit().predict()` instead of `res = model.fit(); res.predict()`
