### ISSUE TITLE
In statsmodels.tsa.ar_model.AR.select_order, bestlag may be undefined when ic=='t-stat'

### ISSUE THREAD

**Issue by 121onto** [statsmodels/statsmodels#2658]
See:

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/ar_model.py#L444

When `np.abs(fit.tvalues[-1]) >= stop` is false at all lags, python throws an exception `UnboundLocalError: local variable 'bestlag' referenced before assignment` .  We should set a default value for bestlag to act as a fallback.

**Comment by josef-pkt** [comment]
Based on your description, the default would be zero, which is just OLS, and if I remember correctly should work now as special case.

What should be the answer in this case, exception, warning, no lags or bestlag=1?
Based on reading the other branch (`ic != 't-stat'`) the smallest lag is 1, as far as I can tell.

Instead of defining a default for bestlag, we could also add a `else` to the `for` loop that additionally warns that we use bestlag 1 even though bestlag should be 0.

(Or switch to returning the no lag model ?)

**Comment by josef-pkt** [comment]
Given that this is in time series analysis, I think a minimum lag of 1 sounds fine, otherwise users might not have any explanatory variables to forecast, except unconditional mean.

So initializing bestlag=1 sounds fine, but the minimum should be mentioned in the "ic" part of the `fit` docstring.

@121onto  Thanks for reporting this. Do you want to make a PR?

**Comment by dhpiyush** [comment]
@josef-pkt I would to make a PR . What i understood is that we need to add bestlag=1 in the else part to the for loop but i did not get the reason ??
