### ISSUE TITLE
add_constant considers a column of all 0s as a constant.

### ISSUE THREAD

**Issue by bjlange** [statsmodels/statsmodels#2659]
`tools.add_constant` uses the variance of columns to detect if a constant is already present. Unfortunately this means that if a column of all 0s is provided, it considers it a constant even thought the model can't use this pre-existing column.

Example:
```python
import statsmodels as sm
import pandas as pd

X = pd.DataFrame([[0, 1, 3.0],
                  [0, 0, 2.2],
                  [0, 1, 4.5]])

# print X 
#    0  1    2
# 0  0  1  3.0
# 1  0  0  2.2
# 2  0  1  4.5

X_const = sm.tools.add_constant(X)

# print X_const
#    0  1    2
# 0  0  1  3.0
# 1  0  0  2.2
# 2  0  1  4.5
```

Seems to me that `add_constant` should either check the content of the columns considered to be constant, or at the least a warning or exception should be raised at some point if one of the columns is all zeros.

I'm happy to open a pull request to change this, just thought I'd open an issue first here to discuss how it should work before writing any code.

**Comment by josef-pkt** [comment]
@bjlange   Thanks, a PR would be very good for this.  

I agree that we should identify a constant as being nonzero. (I guess we have the same problem in the model data handling.)

Since the current check is with equality, I guess we can also use equality testing for not zero, and we would need to check only one element (row). (We haven't had any complaints about equality testing, AFAIR) 

The main question is what should be the default, do we need a extra keyword options. Should we make it dependent on the existing keyword `has_constant`.

maybe: treat zeros as `not a constant`, which means add a constant if there is no non-zero constant, and `has_constant` is 'skip' or 'add', raise if `has_constant='raise'`

(note mainly to myself: This might create a merge conflict, but that shouldn't affect the actual change. I need to check.)

**Comment by bjlange** [comment]
Treating zeros as 'not a constant' seems reasonable to me, and doing equality on the first row sounds good since a variance of zero guarantees that the whole column consists of the same value. 

I'll get to work on a PR.

**Comment by josef-pkt** [comment]
Thanks,

I forgot to mention: in other cases for checking constant we replaced variance `var` by np.ptp, which is faster since it uses only a single pass through the data, and I expect it's also more accurate. I think you could do this also here when you make the changes.

**Comment by bjlange** [comment]
While I'm in the guts:

Is there any particular reason it doesn't do the constant checking if the data is structured or recarrays? (see in code [here](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tools/tools.py#L327))

**Comment by josef-pkt** [comment]
@bjlange  Most likely @jseabold  didn't implement it for structured dtypes or recarrays because it's difficult to check (dtypes could be anything) and it wasn't used enough to put in much effort.

It's still open what we will do with structured dtypes and recarrays, drop most of the support for them, handle them be round tripping through pandas or fix those problems. Nobody complained about this in 6 or 7 years, AFAIR, not even before pandas essentially replaced recarrays for almost all users.

**Comment by bjlange** [comment]
Makes sense, I'll just leave that part alone.
