### ISSUE TITLE
Possible source of testing timeout: TSA tests and __init__

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#2694]
@ChadFulton @josef-pkt  Many tests in `statespace` estimate and smooth in `__init__`.  The is the source of the timeout on travis since the class is initialized before the test run, and nothing is produced by the init.
I think there might be a problem in the statespace tests that use `__init__` to estimate models.

Instead of being in `__init__`, I think these should be in 
```
    @classmethod
    def setup_class(cls):
        pass
 
    @classmethod
    def teardown_class(cls):
        pass
```

so that they are called right before the tests are run.  This will let nose finish the initial steps much faster and get tot he point where it starts spitting out `......S....E...`

To see the effects of this, try

`nosetests --verbosity=4 statsmodels.tsa.statespace`

You should see a noticeable pause for each class that nose finds.  This is very different from running 

``nosetests --verbosity=4 statsmodels.regression`

which flies through the initial steps.

**Comment by bashtage** [comment]
From what I can tell, a new object is created for each test in a class, which means the same model is estimated/filtered/smoothed many, many times.

**Comment by josef-pkt** [comment]
Sounds good, thanks

Yes, `__init__` is run before each test method is called. That's why we use the classmethod `setup_class` in many tests, to do expensive calculations only once.  When Skipper timed this initially, many years ago, then in a few cases where model setup and estimation was fast, putting it in `__init__` was a bit faster than in `setup_class`.
The other speedup that I added in several cases is to use good starting values (close to optimal) in unit tests for auxiliary results, when checking convergence is not the point of the unit test.

**Comment by ChadFulton** [comment]
Thanks for investigating this @bashtage. I wasn't aware of `setup_class`, I'm sure that will help substantially.

**Comment by bashtage** [comment]
Some of the TestRLM and TestGLM are also a bit slow in the initial test discovery/creation run in nose.

**Comment by bashtage** [comment]
@josef-pkt @ChadFulton This should be closed - not an issue with master on Travis.

**Comment by ChadFulton** [comment]
Thanks!
