### ISSUE TITLE
LinAlgError using IV-2SLS 

### ISSUE THREAD

**Issue by oddskool** [statsmodels/statsmodels#2720]
When using IV2SLS from statsmodels.sandbox.regression.gmm I get a LinAlgError ("0-dimensional array given. Array must be at least two-dimensional") when giving 1D inputs.

A dummy way of triggering the error might be:
```python
import numpy as np
from statsmodels.sandbox.regression.gmm import IV2SLS

IV2SLS(np.arange(10), np.arange(10), np.arange(10)).fit()
```

As it makes perfect sense to use 1D instrument, endo- and exo-geneous variables I think this is a bug.

**Comment by josef-pkt** [comment]
It's likely that there is not enough shape checking (and automatic conversion to 2-d)

However, that's really an unusual case that I never thought about.
Note, we are not adding automatically a constant in the array interface.

So this would be one endogenous "reponse" variable, one endogenous regressor and one instrument, where neither of the two regression has a constant.

What is your example or application with this case?

The only problem should be in the first stage auxiliary regression, where we need to check the instrument array and convert 1-D to 2-D column if necessary.

**Comment by oddskool** [comment]
Maybe I'm confused with the interface. In the first stage I'm ok to add an intercept to the regression, but I have only one (continuous) instrument variable. 

So not sure how to express that as whenever I put a 1D instrument this triggers the error:

```python
IV2SLS(np.arange(10), sm.add_constant(np.arange(10)), np.arange(10)).fit()
```

Having a first stage without intercept may be a valid case too (but no for my application).

PS: I was able to compute a coefficient estimate using two OLS models, but now I want a correct confidence interval for the coefficient - hence testing the sandbox IV2SLS :)

**Comment by josef-pkt** [comment]
I haven't checked the code yet.

But the following two versions would add a constant to the first stage regression, with or without a constant in the main regression

`IV2SLS(np.arange(10), sm.add_constant(np.arange(10)), sm.add_constant(np.arange(10))).fit()`
`IV2SLS(np.arange(10), np.arange(10), sm.add_constant(np.arange(10))).fit()`


Assuming this is just a shape, problem the following should also work, i.e. explicitly use a 2-D single-column instrument array: 

`IV2SLS(np.arange(10), sm.add_constant(np.arange(10)), np.arange(10)[:, None]).fit()`

As reminder: If you have exogenous regressors in the main equation, then they need to be added to the instruments. 

Aside: Unit test coverage for IV2SLS should be pretty good. The main problem are still some interface choices. So, if you have any comments on the API and usability, then I'd appreciate to hear them.

**Comment by josef-pkt** [comment]
There is no special data handling beyond the default endog exog handling. Obviously I never went back to this because I only used numpy arrays in the examples and tests.

`missing` handling including instruments can now (>0.6 IIRC) also be delegated to super.
asarray and shape check for instruments need to be in the class itself.

```
__init__(self, endog, exog, instrument=None):
        self.instrument = instrument
        super(IV2SLS, self).__init__(endog, exog)
```

related: 
`from_formula` is inherited but needs to be overwritten to handle formulas for instruments. 
We now have also cases for that, AFAIK, most likely MixedLM.


---
one main API and internal decision is whether to split up the regressors into an endogenous and exogenous part, as Stata's ivreg and ivreg2 do. However, it makes inherited data handling more difficult, but that should be feasible now with statsmodels >=0.7 (?)
The split is irrelevant for the way it's currently calculated, but we don't have much in terms of IV diagnostics yet, especially with respect to possible weak instruments problems.

**Comment by oddskool** [comment]
Ok, so in my case the system equations are (omitting noise):
  - $x = \alpha_1 + \beta_1 z$
  - $y = \alpha_2 + \beta_2 x$
So I ended with the following call: `IV2SLS(y, sm.add_constant(x), sm.add_constant(z)).fit()`

I think the API might be sensible, but the docstring could be improved (especially for people like me taming their first 2SLS in python). Including an example with the system equations and the corresponding IV2SLS calls would be a must :)

Apart from that point, I suppose that the return value is the result of the second regression - which is sensible again - given that the user is provided with 2 additional infos:
- correct confidence interval over the coefficients : I'm told it should differ from the naive OLS of the second stage since the regressor is an estimate (for now I'm not sure since in my case the two method give the same CI)
- the value of the F-statistic for the first stage : a rule of thumb is that it should be > 10 for a strong instrument
Maybe both infos are already there but not documented/accessible through `summary()`, haven't checked it atm.

If it's not too involved and given proper guidance I might be able to provide a PR targeting an improved docstring. Let me know if it helps.

**Comment by josef-pkt** [comment]
@oddskool   Thanks, yes the feedback helps, and PR would be welcome.

about docs: Yes, it's still lacking and improvements would be helpful. I started to work on that module again, but only on the GMM part. Adding or starting a notebook with an example would also be useful. (I started several on GMM)

about confidence interval: They **should** be correct, but I need to check test coverage if they are directly tested (confint are inherited). Are your bse and tvalues also the same between OLS and IV2SLS? I guess they should only be close to each other if you have an almost perfectly correlated instrument.

about info for first stage:  This is still completely open. Currently no information about the first stage is stored. One design question is when to calculate it and what to store. In general we try to calculate extra results only on demand, for example only when `summary` is called. However, in this case storing the entire first stage might use up more memory in large data cases.
I guess calculating R squared assuming the presence of a constant would be relatively straight forward and not computationally expensive. We should be able to calculate the F-statistic, f_values directly from it. (I guess it will be useful just a statistic and will not be a valid F-test under robust covariance assumptions, heteroscedasticity, correlation, ...)
I guess summary could be improved with more specific IV 2SLS information.
From my personal interest I targeted more IVGMM for enhancements than IV2SLS. 

The simplest solution for the exog check is to
- use asarray
- if instruments.ndim == 1: check length is the same as endog then reshape otherwise raise
- add instrument keyword to super `__init__` call
