### ISSUE TITLE
BUG DOC build:  model docs don't show `from_formula`

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2755]
`from_formula` is missing in the list of methods in the new documentation
http://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.WLS.html

but it's in the old version
http://statsmodels.sourceforge.net/devel/generated/statsmodels.regression.linear_model.WLS.html

MixedLM docs shows from_formula, so maybe it's related to inheritance of class methods?

**Comment by ngaurav** [comment]
from_formula is implemented only in statsmodels/regression/mixed_linear_model.py ; so, it is listed only in  [http://www.statsmodels.org/dev/generated/statsmodels.regression.mixed_linear_model.MixedLM.html](http://www.statsmodels.org/dev/generated/statsmodels.regression.mixed_linear_model.MixedLM.html)

Whereas, other methods like fit_regularized are implemented in statsmodels/regression/linear_model.py as well as in statsmodels/regression/mixed_linear_model.py
That's why they are also enlisted in [http://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.WLS.html](http://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.WLS.html)

**Comment by josef-pkt** [comment]
`from_formula` is inherited and should be available and in the documentation for all the supported model classes, as it is in the old documentation on sourceforge.

I have no idea why they don't show up in the recent documentation on github (www.statsmodels.org)  Maybe a bug in the sphinx version that was used.

**Comment by ngaurav** [comment]
Yes, you correctly pointed out the issue. I ran sphinx-build using sphinx 1.3.5. The generated docs had all the methods in the old doc. It also included one extra method `get_distribution`. Here is the screenshot.
<img width="811" alt="screen shot 2016-01-30 at 10 49 30 am" src="https://cloud.githubusercontent.com/assets/12483343/12693880/7bb581fa-c73f-11e5-9a49-ebc761e39826.png">

**Comment by ngaurav** [comment]
The old doc uses sphinx 1.2.2 while the current doc uses sphinx 1.3.1. Should we update the sphinx version?

**Comment by josef-pkt** [comment]
from formula is back
http://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.WLS.from_formula.html

#2816 fixed the doc and notebook build and uses sphinx 1.3.5 (several sphinx versions had bugs with autodoc)
