### ISSUE TITLE
BUG: Non-ASCII character in KPSS docstring

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#2785]
The hyphen in the page numbers (159-178) is a non-ASCII character. This doesn't break on Python 2.x on Travis, but it does on my machine.

```
  File "/Users/fulton/projects/statsmodels/statsmodels/tsa/stattools.py", line 1114
    `Journal of Econometrics` 54, 159–178.
                                          ^
SyntaxError: Non-ASCII character '\xe2' in file .../statsmodels/statsmodels/tsa/stattools.py on line 1115, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

**Comment by josef-pkt** [comment]
@ChadFulton  Can you make the change to ASCII?    (one character PR and merge?)

AFAIK, all my editors default to utf-8, but we should stick with ASCII unless there is a non-ASCII name.
My spyder default header adds `# -*- coding: utf-8 -*-` to new modules, but we never defined or even discussed this in general.

(BTW: try to add github labels to new issues and PRs)

**Comment by ChadFulton** [comment]
No problem - just wanted to make sure it wasn't something specific to my machine. I still don't fully understand the unicode idiosyncracies of Py2 vs Py3.

Thanks for the reminder about labels - I forgot I could do that.

**Comment by josef-pkt** [comment]
Copy-pasting non-ASCII and non utf-8 can happen easily when we copy things from another editor like references. I need to change things like forward quotes and hyphens every once in a while. But the original contributor might not realize because everything is in a compatible encoding.

I think python 3 interprets all modules as utf-8 by default, so there shouldn't be a problem with unicode characters. But it's easy to copy-paste the default system encoding, latin-1, cpxxxx. In the past I ran into problems with greek letters in PRs where I didn't know the original encoding which wasn't utf-8.
IIRC, Python 2 falls back to system encoding, which for me was always Windows cp1252 and is, AFAIK, incompatible for special characters with other (Linux) defaults.

Sticking to ASCII avoids the problems, but we don't want to mess up proper names either.
(I find Julia's preference for greek unicode letters "weird", I never remember for most of them how that squiggly things are pronounced nor what the keyboard shortcut would be, except maybe a, b, d, g :)

**Comment by ChadFulton** [comment]
Thanks for that description. That makes sense to me. Am I then right in thinking that the tests didn't fail on Travis because it's an environment the system encoding which Python 2 fell back to allowed the non-ASCII character?
