### ISSUE TITLE
DOC: Building notebooks fails with some ipython version

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#2813]
The `nbgenerate` script no longer works well, and should in any case probably be at least partly replaced because the newer versions of `ipython nbconvert` work pretty well; e.g.

```ipython nbconvert --to rst --execute *.ipynb```

**Comment by josef-pkt** [comment]
I didn't know about the `--execute` option. I was recently trying out `runipy` another wrapper program on top of it, that also seems to work fine.

Currently we generate html instead of rst and embed it as html in the rst file.

Also it doesn't work on python 3. #2312
Another issue: which format #2530

**Comment by josef-pkt** [comment]
I need additional `--allow-errors` to get over cells that raise exceptions

However, format 4 seems to hardcode the python version. 
I get a keyerror `python2` and nbconvert stops with an exception.
(I'm using python 3.4 and I think I don't have a python 2 on the system path.)
It looks like we might have to get rid of the python version specific "kernelspec" 
???

I didn't figure out yet how to stop raising an exception on timeout, which happened, AFAICS, in one of the notebooks (on cold start)

Also: I recently looked at sphinx extension for notebook conversion, like http://nbsphinx.readthedocs.org/en/0.2.4/index.html
but I have no idea how reliable they already are.

**Comment by TomAugspurger** [comment]
Quick update, I've got all the notebooks converted to version 4, and a new version of `nbgenerate` that uses `nbconvert`. It optionally executes the notebooks as well.

Tonight or maybe tomorrow I'll finish fixing the notebooks so that they're all running. The only real bug I've seen so far (not simple things like py3 compat) is this one in `discrete_choice_overview.ipynb`

```python
margeff = logit_res.get_margeff()
print(margeff.summary())
```

which gives

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-f2053e93ff07> in <module>()
      1 margeff = logit_res.get_margeff()
----> 2 print(margeff.summary())

/Users/tom.augspurger/Envs/dev/lib/python3.4/site-packages/statsmodels/statsmodels/discrete/discrete_margins.py in summary(self, alpha)
    520         _, const_idx = _get_const_index(model.exog)
    521         if const_idx is not None:
--> 522             exog_names.pop(const_idx)
    523 
    524         J = int(getattr(model, "J", 1))

TypeError: only integer scalar arrays can be converted to a scalar index
```

I am using numpy-dev. I can open an issue if this isn't already known.

**Comment by TomAugspurger** [comment]
> However, format 4 seems to hardcode the python version. 

This is a parameter to the `nbconvert.preprocess.PreprocessExectutor`, the thing that actually runs the notebook. By default it grabs that from the notebook metadata, but it can be overridden.

**Comment by josef-pkt** [comment]
@TomAugspurger   Thanks for all this work. Sounds very good.

You can also put it then in a PR or somewhere so I can also try.
(Reminder: Don't commit output in notebooks. We don't want to load the repo with temporary print and plots.)

I'll look at the `get_margeff` error. It looks like we don't have a unit test for summary (which have smoke tests only so far)

**Comment by TomAugspurger** [comment]
@josef-pkt https://github.com/statsmodels/statsmodels/pull/2816
