### ISSUE TITLE
State space modelling - prediction intervals

### ISSUE THREAD

**Issue by anguschadney** [statsmodels/statsmodels#2823]
Apologies if this is the wrong forum for this...
At the moment it appears that it is not possible to extract confidence intervals from the predict/forecast functions for SARIMAX (which predicts via SARIMAXResults, MLEResults).
This notebook from Chad shows how this used to work:

http://pages.uoregon.edu/cfulton/posts/state_space_python.html

Are there any plans to add this back in, or am I just missing some arguments?

```
mod = sm.tsa.SARIMAX(
    endog=train_sample,
    order=(2,0,0),
    seasonal_order=(0,1,0,48)
)
res = mod.fit()
forecast = res.forecast(steps=48, full_output=True)
type(forecast)
```
Out:  pandas.core.series.Series

Version: '0.8.0.dev0+96cad08'

**Comment by ChadFulton** [comment]
Thanks for reporting this - it is still possible, but the syntax has changed to `get_prediction` or `get_forecast` to get the full output object rather than the `full_results` keyword argument to `predict` or `forecast.

Take a look at the plot at the bottom of this notebook for an example: http://www.statsmodels.org/dev/examples/notebooks/generated/statespace_local_linear_trend.html

It looks like I need to update my personal website on a couple of issues that have since changed.

**Comment by josef-pkt** [comment]
The sarimax notebook also uses `get_prediction`
http://www.statsmodels.org/dev/examples/notebooks/generated/statespace_sarimax_internet.html

the list of notebooks is http://www.statsmodels.org/dev/examples/index.html
(at the moment not linked back from the notebooks)

**Comment by anguschadney** [comment]
Thank you so much guys - works like a charm!
