### ISSUE TITLE
BUG: df_model in GLM

### ISSUE THREAD

**Issue by thequackdaddy** [statsmodels/statsmodels#2853]
Hello, 

First, thanks on your help getting `freq_weights` in GLM. Its working great. 

Using my design matrix construction program, I've been building GLM's in some pretty good times. One had around 40 coefficients and 1.2 million records and I fit it, from a bcolz ctable (with 1.2 million rows and about 100 columns) to a fit model, in around 60 seconds with Poisson/log. There's also some additional potential speed improvements I can think of, but I just haven't gotten around to programming them. 

I am running into a problem now with `df_model`. Its not material, but its something I should ask about.

I've noticed that we essentially calculate `df_model` with `np.linalg.matrix_rank(exog) - 1`. On my design matrix, that yields a 1. My design matrix can hold very large values for some variables. Some values can be in the 10's of millions. I think that bumps up the singular values of the SVD which is an input to the default `tol` calculate. 

If I adjust `tol` to be `1e-100`, it works. On a 1.2 million long x 18 column wide matrix, `matrix_rank(exog, tol=1e-100)` yields 17, the correct answer. 

Before I make a PR changing this, any thoughts?

**Comment by josef-pkt** [comment]
If I understand you correctly:

I think this is the wrong end to fix this. I think you need to rescale your variables, because the same numerical problems might show up in other parts, e.g numerical stability problems in WLS.
I had large problems with discrete Poisson and scipy optimizers, because even at x values of 100 the exp can easily overflow when starting params or trial values during optimization are too large. (bfgs has been or is being fixed in scipy to be more robust in cases like this.)

IRLS/WLS is pretty robust but could still run into rank problems and might use the generalized pinv in cases like this, at least further away from the optimum.

My solution for Poisson has been to work towards internally standardizing all variables, but present the unnormalized parameters to the user. (this requires a rescaled copy of the exog array.)

What are the estimated parameters for the exog with large values? Are they very small or very negative?

**Comment by josef-pkt** [comment]
A bit related possible design choice/enhancement: 
In some nonlinear cases it would be more appropriate to look at the rank of the cov_params directly, or the rank of score_obs. But, because of the additive part it won't change anything in this case unless some weights are zero/score_factors, AFAICS. (And I don't really know what would happen in partial separation cases.)

**Comment by thequackdaddy** [comment]
Ahhh.... Clever

Yes, essentially I have variables in my data that are things like "VehicleWeight". Then I add additonal columns for things like VehicleWeight **2, VehicleWeight ** 3, etc. That creates massive values. The parameters for those guys are really small, but the standard errors are even smaller, so I want to keep those variables. Normalizing the columns, but showing normalized parameters makes sense to me. 

Thanks.

**Comment by josef-pkt** [comment]
In general, polynomials work much better when the underlying variable is normalized or bound to a small intervall. numpy polynomial vander functions allow automatic rescaling.

One example that broke Poisson optimization for me was age and age**2 for retired people, age 60 to 100. Stata does automatic rescaling internally and didn't have problems. 
There are several issues open for this.

**Comment by thequackdaddy** [comment]
Interesting... I didn't know about vander--that's close to what I want, but not exact. I often take the 1st power and 3rd power, and skip the second. 

I'll go ahead and close this and experiment more.

Thanks.

**Comment by josef-pkt** [comment]
@thequackdaddy   performance question related to `np.linalg.matrix_rank(exog)`

How long does the matrix_rank check take in your dataset?
I just realized that we check this in each iteration in WLS also, which is pretty redundant in this case.

**Comment by thequackdaddy** [comment]
It's pretty fast... Maybe a half second

I'm setting maxiter=10, so that's probably 10 seconds of waste!
