### ISSUE TITLE
Exog in custom state space model

### ISSUE THREAD

**Issue by suhalim9** [statsmodels/statsmodels#2859]
Hi,

I am following this (http://pages.uoregon.edu/cfulton/posts/state_space_python.html) to build a custom local linear trend model but I would like it to take exog. Exog seems working the way I expect when I used Unobserved Components, but when I follow the custom state space model (made sure to take exog in arguments), exog doesn't seem to take effects on the model.

Can you investigate on this? Does it require me to have extra configuration in __init__ other than taking it as an argument and passing it to super()?

Thanks!

**Comment by ChadFulton** [comment]
Custom state space models are entirely custom, so they don't have any built-in `exog` handling. Your class could accept an `exog` array and then handle it however you would like.

For example, in the `RecursiveLS` class in #2830, the `exog` array is put into the `design` matrix in order to perform recursive least squares. In the `UnobservedComponents` class, the coefficients are estimated via MLE and the resulting `X b` array is put into the `obs_intercept`.

**Comment by suhalim9** [comment]
Thanks so much for reply. Yeah that makes sense. :)
