### ISSUE TITLE
BUG?: GLM working residuals

### ISSUE THREAD

**Issue by thequackdaddy** [statsmodels/statsmodels#2891]
Wanted to document this in a separate issue. 

There is some discussion in #2872 about working residuals. I believe there is an error with our derivation. 

Currently, the code is...

```python
    def resid_working(self):
        # Isn't self.resid_response is already adjusted by _n_trials?
        val = (self.resid_response / self.family.link.deriv(self.mu))
        val *= self._n_trials
        return val
```

I suggest it really ought to be... 

```python
    def resid_working(self):
        val = (self.resid_response * self.family.link.deriv(self.mu))
        return val
```
This change breaks some unit tests... @josef-pkt found [this link](http://www.stata.com/manuals14/rglmpostestimation.pdf) (see page 6) which shows we should multiply, not divide, by the derivative. 

(For the record, I don't use working residuals, nor do I plan to start using them. But I feel bad about writing a test in #2872 with an intentionally incorrect result to match what I think is incorrect.) 

Thanks!

**Comment by josef-pkt** [comment]
skip testing the working residuals. That's what I do in the weights testing PR.
I added the verified results but did not add an `assert` for them, so I can add it later.

The problem is that we need to redo the current unit test results which have coded the wrong numbers. If we just fix the bug, then the unit tests will fail. (all residuals are combined together so it's not so easy just to replace the incorrect working residuals in the test results file.)

**Comment by thequackdaddy** [comment]
Yes sir. Thanks!
