### ISSUE TITLE
BUG: self.history in GLM doesn't seem like it does anything...

### ISSUE THREAD

**Issue by thequackdaddy** [statsmodels/statsmodels#2977]
Hello,

The `history` attribute in GLM doesn't seem like it really does anything. It seems like what's happening is that the history is created by each of the district `fit` methods. 

See this line of code:
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_linear_model.py#L291

You can uncomment it all and GLMs seem to work just as before. A few tests fail when they try to reference that attribute, however, so there's some hunting that will be necessary to clean this up.

**Comment by josef-pkt** [comment]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_linear_model.py#L989

`history` is used in the convergence check in fit_irls. it checks the last element in the list,
At least, that is what it is supposed to be doing.

It's also available as a results attribute, AFAIR, so we can check the history of irls optimization.
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_linear_model.py#L1002

**Comment by thequackdaddy** [comment]
Sorry I wasn't clear.

The `history` that is defined in `GLM` in the `initialize` section appears to be ignored in the `fit_irls` section. There, `history` is created as a new dict, totally independent of the one in the ` `GLM` instance. That new `history` is later saved as part of the model result. The original history, in the model, is totally disconnected.

**Comment by josef-pkt** [comment]
Ok, my guess is that the part in initialize with `self.history` is a an orphan because of the refactoring
https://github.com/statsmodels/statsmodels/commit/9cb2a022040e96472c68e136027ab09c5b702ab1

We try to avoid having fit specific information attached to the model. So using history and attaching it to the results instance is cleaner.
It looks to me we can remove it from `initialize`, but we need to check what the let over usage of it is that you say raise an error.  Maybe those tests should check the results.history, but they might not test much if `self.history`, where self is the model, never gets updated.

**Comment by thequackdaddy** [comment]
Sounds good.  I think this is just an inconvenience... Not major by any stretch. Just I decided to put some time back into the convergence issue I had before and this confused me for a bit.

**Comment by jbrockmendel** [comment]
+1 for getting rid of this

**Comment by josef-pkt** [comment]
I think the fix for this has been included and merged with one of thequackdaddy's PRs

**Comment by thequackdaddy** [comment]
No the PR is #3465 . Not merged. Looks like there’s a conflict now.

**Comment by jbrockmendel** [comment]
Can be fixed at the same time as #2399.
