### ISSUE TITLE
BUG:  import statsmodels slow and loads a lot, including pandas

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3082]
```
C:\...\WinPython-64bit-3.4.4.2\notebooks>python
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(len(sys.modules))
122
>>> import statsmodels as stm
>>> print(len(sys.modules))
648
>>>
```

I got suspicious because of slow import when I just want to check something quickly.

AFAICS, `statsmodels.__init__` loads some of the warnings, which imports tools which now loads pandas and others in `tools.__init__` because `add_constant` is loaded from `tools.tools`

**Comment by josef-pkt** [comment]
maybe that wasn't better in 0.6.1

```
>>> import statsmodels as stm
>>> stm.__file__
'C:\\Users\\josef\\Downloads\\WinPython-64bit-3.4.3.6\\python-3.4.3.amd64\\lib\\site-packages\\statsmodels\\__init__.py'
>>> stm.__version__
'0.6.1'
>>> import sys
>>> len(sys.modules)
843
```

this includes matplotlib, matplotlib is disabled in the python 3.4.4. version above

**Comment by bashtage** [comment]
One partial solution to this is to reorganize so that tests are a TLD under statsmodels but is not directly imported.  See what pandas has done.

**Comment by josef-pkt** [comment]
Why would that help the import issue? When and why did pandas collect the test folders? I didn't find anything with github search.

The problem is that pandas is importing pytest during runtime, so I didn't check all places to see whether we might also import it. I didn't see any code that imports our `tests` folders in the regular code (i.e. outside of examples, docs and tests)

**Comment by bashtage** [comment]
It is the same but IMO can't plausible be fixed in the near-to-medium term. Importing takes about 2s for just statsmodels given pandas and scipy.stats have been imported.

You can profile import times on python in 3.7

`python.exe -X importtime -c "import statsmodels as sm"`

There is nothing obvious.

**Comment by jbrockmendel** [comment]
closable?

**Comment by josef-pkt** [comment]
I think this is a perennial issue, i.e. needs checking every once in a while.

a quick check
It looks like something (pandas ?) still imports matplotlib
But the number of modules looks stable compared to 2016 above

```
M:\josef\temp>python
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> len(sys.modules)
43
>>> import statsmodels as stm
>>> len(sys.modules)
650
>>> len([i for i in sys.modules if "matplotlib" in i])
19
>>> len([i for i in sys.modules if "pandas" in i])
144

>>> [i for i in sys.modules if "matplotlib" in i]
['matplotlib.transforms', 'matplotlib.colors', 'matplotlib._version', 'matplotli
b.externals.six.moves.urllib.request', 'matplotlib.compat', 'matplotlib.rcsetup'
, 'matplotlib.cbook', 'matplotlib.fontconfig_pattern', 'matplotlib.compat.subpro
cess', 'matplotlib._path', 'matplotlib.externals', 'matplotlib.externals.six.mov
es', 'matplotlib.units', 'matplotlib.dates', 'matplotlib.ticker', 'matplotlib.ex
ternals.six', 'matplotlib.path', 'matplotlib.externals.six.moves.urllib', 'matpl
otlib']
```

**oops** that's not relevant. 
I'm using an ancient python and an ancient pandas. So there cannot be a change in that part. 
However, importing statsmodels itself hasn't changed much in master compared to 2016

**Comment by jbrockmendel** [comment]
I'm getting the following import times for `python3 -X importtime -c "import foo" for the following packages, in microseconds:

| Package  | Microseconds |
| ------------- | ------------- |
|statsmodels.api       |    1059719   |
|pandas                     |    321407   |
|matplotlib                 |   123115  |
|matplotlib.pyplot      |   250980  |
| patsy | 335032 |
| scipy | 83140 |
| scipy.stats | 238988 |
| scipy.signal | 253966 |
| scipy.special | 120417 |

These numbers aren't super-meaningful in isolation since e.g. patsy imports numpy, and many parts of scipy.foo overlap with scipy.bar

Brainstorming optimizations:
- In the distant future when only py37+ is supported we can patch module `__getattr__` and make all imports lazy.
- Implement asv benchmarks, including one for import speed, so we can at least keep track of this.
- There are non-lazy imports of matplotlib.pyplot in two places.  lazifying those saves about 10%
- the statespace cython imports are pretty heavy
  - try to make them lazy
  - consider making modules smaller by dropping float32 and complex64?
- the `get_version` call in `__init__` is about 90ms (close to 10%).  can't make this lazy until 3.7
- Maybe there are less-used scipy sub-packages that can be imported lazily?  I haven't had any luck with this.

**Comment by josef-pkt** [comment]
@jbrockmendel 

Note that I am talking about the empty `import statsmodels` which should be fast so we can import parts with minimum overhead.

importing the api, `statsmodels.api` will always be very slow because it loads almost all of statsmodels and all direct and indirect dependencies at once.

**Comment by josef-pkt** [comment]
> In the distant future when only py37+ is supported we can patch module __getattr__ and make all imports lazy.

Nonstarter, actually several packages tried this 8 to 10 years ago, but it never worked properly and AFAIK they all gave up.
It was always too much magic to me, so we never even tried.
But I'm very glad that I pushed for the `api` dual track.

**Comment by jbrockmendel** [comment]
> Nonstarter, actually several packages tried this 8 to 10 years ago, but it never worked properly and AFAIK they all gave up.

Right, which is why the suggestion was specific to py37+, as this was one of the selling points of [PEP 562.](https://www.python.org/dev/peps/pep-0562/)

> Note that I am talking about the empty import statsmodels which should be fast so we can import parts with minimum overhead.

Lots of room for optimizations for that one.

**Comment by bashtage** [comment]
This has been resolved as much as reasonable.
