### ISSUE TITLE
xname filter in OLS doesnt line up coefficients

### ISSUE THREAD

**Issue by msdels** [statsmodels/statsmodels#3122]
There seems to be a more general problem of the xname filtering. When passing a list of variables to include it correctly shows those names in the summary but it does not pick the correct summary information. The summary statistics (coefficients etc) get truncated from first to last regardless of the xnames passed.

```
from __future__ import print_function
import numpy as np
import statsmodels.api as sm

np.random.seed(9876789)

nsample = 50
sig = 0.5
x = np.linspace(0, 20, nsample)
X = np.column_stack((x, np.sin(x), (x-5)**2, np.ones(nsample)))
beta = [0.5, 0.5, -0.02, 5.]

y_true = np.dot(X, beta)
y = y_true + sig * np.random.normal(size=nsample)
```

Then compare:

```
res = sm.OLS(y, X).fit()
print(res.summary())
```

vs

```
res = sm.OLS(y, X).fit()
print(res.summary(xname=['x2','x3']))
```

The names are filtered but they now have the incorrect coefficients.

Using sm version '0.6.1'

**Comment by josef-pkt** [comment]
The bug here is that we don't warn or raise an exception.
I don't know if we can support selection on names.

@msdels xname only sets the names that is printed in summary, it does not select. However, the table class truncates the rows to the number of xnames. Given that you specify 2 xnames, it prints the first two rows with the given xnames.
e.g `print(res.summary(xname=['x1', 'x2','x3', 'const']))`
has the same number of xnames as params and prints the summary as in the original.

`print(res.summary(xname=['const', 'x2','x3', 'x1']))`
changes the labels but not the values, i.e. const is now shown with the first params, and x1 with the last. xnames is pure labeling.

Was your intention to only print the rows for the x2 and x3 parameters?

That is currently not supported, and would need another keyword for selection and not just labeling.

**Comment by josef-pkt** [comment]
another option:

for out of sample forecasting we could also add a keyword argument to `predict` and `forecast` so users can provide an out-of-sample pandas index in the no-`freq` case. That would allow the users to avoid the "magic" and get an explicit extension of the index.

**Comment by josef-pkt** [comment]
However, 

Adding more options makes the code more complex again, and `begin`, `end` handling in forecasting and prediction is already complicated enough.
It would be possible to just support integer index for no-freq pandas Series, and force users to convert the index back and forth when they want to use non-equal spaced time periods.

I think either way is possible depending on how difficult it is to support the various options.

**Comment by josef-pkt** [comment]
If I see this correctly we would have the following 3 cases

1. freq given, no gaps - current case, fully supported
2. freq given, with gaps including the case with `missing="drop"` - maybe "allow_irregular=True": assume equal spaced lags in estimation in spite of gaps and use freq to create out of sample index
3. freq not given, only integer index allowed, or arbitrary "row-labels" with explicit out-of-sample index

**Comment by msdels** [comment]
Thanks for quick replies. 

Yes, my intention was to only print the rows for x2 and x3. In my real world use case I want to suppress rows that are not of interest as there are many of them (nuisance parameters).

This can be done easily enough by just wrapping the summary() call with something that opens the statsmodels.iolib.table.SimpleTable object and removes the rows I dont care about.

**Comment by bashtage** [comment]
You could add an option to summary to do this in a PR.  Maybe `report=['x1','x4']` or `report=[0,1,4]`?

**Comment by bashtage** [comment]
Maybe `filter` would be better.
