### ISSUE TITLE
BUG/ENH: MICEData should give a more informative error with missing column names

### ISSUE THREAD

**Issue by fnielsen** [statsmodels/statsmodels#3177]
With the following initialization:

```
MICEData(DataFrame([[1, 4], [2, 3]]))
```

you get a TypeError exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/imputation/mice.py", line 242, in __init__
    self.set_imputer(vname)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/imputation/mice.py", line 352, in set_imputer
    fml = endog_name + " ~ " + " + ".join(main_effects)
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S21') dtype('S21') dtype('S21')
```

This error seems to be because the column names are missing, since the below code does not give any error:

```
MICEData(DataFrame([[1, None], [2, 3], [1, np.nan]], columns=['a', 'b']))
```

I would have expected a more informative error. Or perhaps that it even was able to handle columns with no names.

**Comment by kshedden** [comment]
@fnielsen, thanks for the report.  

The issue here seems to be that your dataframe uses the default column labels, which are actually numbers (0, 1, 2, ...).

MICE uses patsy heavily, so the variable names used by MICE need to be valid variable names for patsy.

I suppose we could detect this and give an error somehow, maybe just something like:

```
if data.columns.dtype is np.dtype('O'):
    raise ValueError(...)
```

(this would still not exclude all possible invalid patsy names)
