### ISSUE TITLE
NormalIndPower.solve_power crashes with TypeError

### ISSUE THREAD

**Issue by psarka** [statsmodels/statsmodels#3188]
In 0.6.1 version NormalIndPower.solve_power seems to be broken:

Running

```
import statsmodels.api as sm
sm.stats.NormalIndPower.solve_power(0.1)
```

results in an Exception:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-4-95c51872332c> in <module>()
----> 1 sm.stats.NormalIndPower.solve_power(0.1)

/usr/local/lib/python3.5/dist-packages/statsmodels/stats/power.py in solve_power(self, effect_size, nobs1, alpha, power, ratio, alternative)
    712 
    713         '''
--> 714         return super(NormalIndPower, self).solve_power(effect_size=effect_size,
    715                                                       nobs1=nobs1,
    716                                                       alpha=alpha,

TypeError: super(type, obj): obj must be an instance or subtype of type`
```

**Comment by josef-pkt** [comment]
The TypeError sounds strange,  (*)

AFAIR, you have to specify all but one of the arguments, the one that is not specified, i.e. the one that is None, will be solved for.

(*) I need to check this (since I'm not sure I remember correctly what's required), but the type error might indicate that NormalIndPower needs to be instantiated
i.e. with parenthesis `NormalIndPower()` creates an instance

`sm.stats.NormalIndPower().solve_power(...)`

**Comment by psarka** [comment]
You are right, adding parenthesis solves the issue.

Thanks!
