### ISSUE TITLE
coint on two identical time series return a coint pvalue not equal to 0

### ISSUE THREAD

**Issue by NoahLiot** [statsmodels/statsmodels#3190]
`from statsmodels.tsa.stattools import coint`
`coint(ANALYTICS_DATA['mid_vwap_TP'], ANALYTICS_DATA['mid_vwap_TP'])`

return:
`(-4.0238632646196653,
 0.0066382019114883646,
 array([-3.43036157, -2.86154511, -2.56677272]))`

I would imagine it would return 0...

**Comment by josef-pkt** [comment]
Note: the function has changed in master and 0.8. The old version was never public and is buggy for several options.

but there is the same problem in the corner case, but not with a small noise added

```
>>> from statsmodels.tsa.stattools import coint
>>> zz = np.random.randn(500).cumsum()
>>> coint(zz, zz, maxlag=3, autolag=None)
(0.14404335520602779, 0.98874068144442639, array([-3.91852234, -3.34840209, -3.05296032]))
>>> help(coint)
Help on function coint in module statsmodels.tsa.stattools:

coint(y0, y1, trend='c', method='aeg', maxlag=None, autolag='aic', return_results=None)
    Test for no-cointegration of a univariate equation
... 

>>> coint(zz, zz + 1e-4 *np.random.randn(len(zz)), maxlag=3, autolag=None)
(-10.935213140495513, 1.1950011740648767e-18, array([-3.91852234, -3.34840209, -3.05296032]))
```

AFAIK: The error correction term, i.e. residual of cointegrating relationship is identically zero, so the slope parameter for the ec term in the difference regression will not be identified.
most likely we get "some" numbers because OLS is using pinv.

I think we can check r_squared or something similar of the cointegrating regression to find this case. But that also needs a threshold. 
Should we raise or return `(nan, 0, array(...))` ?

OLS question: why is the t-value not `nan`? I think it should be 0/0. too much floating point noise?
**correction** the ADF-diff regression is all zeros (zero endog and several zero exog), so nothing really makes sense.

@NoahLiot Do you have a preference between raising an exception or issuing a warning and returning (nan, 0) in this case?
nan still breaks code that compares the test statistic with the critical values. (for that -np.inf would be better)

**Comment by NoahLiot** [comment]
Hello,

I would imagine the result on such could be issuing a warning with `(-np.inf, 0, array(...))` as this would make sense, and not break the test. 
Raising exception for something that should be mathematically possible to do seems a bit drastic since, for example, if the user loop over different data series, he would end up having to handle duplicate data. It also obfuscate further weird results investigation. This is how I was able to pinpoint this bug. Just my two cents.

Cheers!

**Comment by josef-pkt** [comment]
using -np.inf instead of np.nan for the statistics makes the change in code simpler, and it would preserve a ranking check with the critical values.

I can loosen the check a bit, but a tiny idiosyncratic noise ends up easily with r_squared==1, and we end up in the corner case for near colinearity.

(PR coming up)
