### ISSUE TITLE
BUG: parameter 'seasonal_period' without any effect on model creation, if specified without 'seasonal'

### ISSUE THREAD

**Issue by drSeeS** [statsmodels/statsmodels#3249]
Hi guys,
just a small (but possibly annoying) bug:

in statsmodels/tsa/statespace/structural.py, class UnobservedComponents:

Following the docstring and setting parameter 'seasonal_period' to any int does not seem to have any effect on the model, i.e., it is fitted w/o estimation of any seasonal component. This is the only seasonality-related parameter mentioned in the doc string

Only looking into its  __init__ (line 313):
        self.seasonal_period = seasonal if seasonal is not None else 0
        self.seasonal = self.seasonal_period > 0

makes clear that if only 'seasonal_period' is specified but not 'seasonal', 
self.seasonal will always be set to 'False', even if seasonal_period supplies a value.

You would have to:
1) add 'seasonal' as a parameter to the docstring (ONLY 'seasonal_period' is mentioned at this time, NO HINT TO parameter 'seasonal')
and/or
2) make sure self.seasonal is set to TRUE if 'seasonal_period' supplies a number to the constructor

All in all Great work guys!
Thanks
Christof

PS: am quite new to this git thing, sorry for not changing and pull-requesting myself yet, next time...

**Comment by ChadFulton** [comment]
Hi, thanks for the bug report! Looking at this, I think it is just a documentation bug. The `seasonal_period` argument shouldn't be in the list of parameters all, and `seasonal` should be there.

**Comment by drSeeS** [comment]
Thanks, yes agreed. Adding 'seasonal' to the documentation and removing seasonal_period will make it crystal clear.

If you anyway take up the documentation, two more suggestions for adding a few lines: 
estimating a custom model, following examples/.../statespace_local_linear_trend.ipynb:
two things get not quite clear while working through the notebook (and I could not find any other docs on custom state space models in statsmodels):

1) Explanation on k_states and k_posdef, required in __ init__:
explanation Point 1 is not really understandable, what does it resemble exactly?
size of the state error vector anyway could have been implicitly inferred from size of selection matrix (self.ssm['selection']), and size of states from transition matrix. Why these vars?

2) in __ init__:
`        # Cache some indices `
`        self._state_cov_idx = ('state_cov',) + np.diag_indices(k_posdef)`
what exactly is happening here with the tuple and why is it needed (k_psdef is just an int anyway), how do you have to adapt it in case the structure of your model is different (like I would like to add a trignometric seasonal instead of period dummies to the state equation)?

Nice you follow Commandeur Koopman (2007), makes it easy to follow!

**Comment by ChadFulton** [comment]
> 1) Explanation on k_states and k_posdef, required in __ init__:
explanation Point 1 is not really understandable, what does it resemble exactly?
size of the state error vector anyway could have been implicitly inferred from size of selection matrix (self.ssm['selection']), and size of states from transition matrix. Why these vars?

The selection matrix isn't a required input. So that things like `self['selection', 0, 0] = 1` make sense, its dimensions need to be known at `__init__`.

> 2) in __ init__:
# Cache some indices
self._state_cov_idx = ('state_cov',) + np.diag_indices(k_posdef)
what exactly is happening here with the tuple and why is it needed (k_psdef is just an int anyway), how do you have to adapt it in case the structure of your model is different (like I would like to add a trignometric seasonal instead of period dummies to the state equation)?

This is just creating an index for use below, you can completely ignore it if you like. `np.diag_indices(k_posdef)` creates a tuple with index locations of the diagonals of a k_posdef x k_posdef matrix. By adding the first part with the name of the matrix, I can index like `self[self._state_cov_idx]` and set all the diagonal elements of the state covariance matrix.

**Comment by drSeeS** [comment]
Thanks for clarifying, appreciate your explanations!
