### ISSUE TITLE
Please declare dependencies at least for the wheels

### ISSUE THREAD

**Issue by anntzer** [statsmodels/statsmodels#3373]
When building a wheel, it is safe to declare dependencies at least for packages for which a wheel is available (i.e. everything but scipy).  This ensures that the dependency on patsy gets filled when someone installs statsmodels from the PyPI wheel (which currently declares no dependencies).

Note that scipy itself recently switched to this approach regarding its dependency on numpy (https://github.com/scipy/scipy/pull/6563, also see the implementation which checks whether "bdist_wheel" is in sys.argv).

As a side note, pip recently gained the [`--upgrade-strategy=only-if-needed`](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption--upgrade-strategy) option, which fixes the original problem (you can just stick it into yout pip.conf and be done with it).

**Comment by josef-pkt** [comment]
just a comment about the original intention, given that I haven't kept up much in recent years.

The main reason why we did not include patsy or similar in requirements, was recursive updating by pip, at least at that time. Because patsy did specify numpy as a requirement, when I used pip with just patsy in the requirement, I still got a new numpy by default whether I wanted it or not (which in my use case on Windows was always NOT.).

**Comment by jbrockmendel** [comment]
A few Issues regarding Wheels appear to have been resolved semi-recently.  Is this among them?

**Comment by jbrockmendel** [comment]
@bashtage closable?

**Comment by bashtage** [comment]
This is fixed in 0.10.0.
