### ISSUE TITLE
statsmodel wls gets stuck during the .fit() process 

### ISSUE THREAD

**Issue by elexira** [statsmodels/statsmodels#3468]
I am training a weighted least square model with around 100k data points. There is some strong co-linearity among some of the features. I have also added regularization .fit_regularized(alpha = 10, L1_wt=0, maxiter = 15) to alleviate that. 
the code occasionally gets stuck (no error message, no progress) during the fitting process. I have to kill the kernel or otherwise nothing happens. 
I do not get any errors ... is there anyway for me to figure out why the model training is stuck ?

**Comment by kshedden** [comment]
I don't think we have tested fit_regularized with wls.  fit_regularized is
a generic method so should work, but there may be something specific about
wls that is causing a problem.

You are using fit_regularized, which is elastic net, but since L1_wt = 0
you are actually doing ridge regression.  Ridge regression for WLS/OLS can
be done in non-iteratively, but fit_regularized does not know this and uses
a much slower coordinate descent algorithm.

We have a recent PR (#3106) now in master that does the one-shot
calculations for OLS, but we did not think to do that for WLS.

Kerby

**Comment by josef-pkt** [comment]
@Sadrpour Do you know which BLAS/LAPACK library your numpy is using?
Getting stuck so that the process needs to be killed sounds like a nan or inf in some of the linear algebra libraries.  The behavior in that case depends on which LAPACK library is used.

If you don't have nans or infs in your data, then we have to check whether there is code in the coordinate descend that might create them. I don't have a guess where something like this might happen, and it most likely depends on some ill conditioned feature of the data.

**Comment by josef-pkt** [comment]
Also, Do OLS and WLS fit without penalization work with your data?  Is the rank reduced? IIRC, it might be `model.rank`.   (OLS and WLS use pinv by default, and drop singular values below a threshold as "regularization", so it still works with collinear data.)

**Comment by josef-pkt** [comment]
I'm keeping this open for 0.10 as part of possible redesign with nan and inf checks

**Comment by noamelf** [comment]
Hi,
We get the same error - process hanging. We reduced the error to this code snippet:

```python
import statsmodels.regression.linear_model as lm
from numpy import array, nan

endog = array([0.2995, 0.2995, 0.2995, 0.2995, 0.2995, 0.2995, 0.2995])
exog = array([[1, 0],
              [1, 1],
              [1, 2],
              [1, 3],
              [1, 4],
              [1, 5],
              [1, 6]])
weights = array([0., 0., nan, nan, nan, nan, nan])
wls_results = lm.WLS(endog, exog, weights=weights).fit()
```

Using `blas` instead of `openblas` solves this issue, but `openblas` is what coming packed with the pypi version for linux.

### System info:
```
numpy==1.14.2
statsmodels==0.8.0
libopenblasp-r0-39a31c03.2.18.so
Python 3.4.4
```

Thanks for your work on statsmodels!

**Comment by josef-pkt** [comment]
AFAIR, we don't check for nan/missing values by default.

If missing='drop' or 'raise', then endog exog are checked for nans. Additional arrays like weights should be checked, but, AFAIR, that is not consistently implemented across all cases and models. 

MKL raises an exception in the nan, inf case.

(I have a PR to check exog for nans as a byproduct of another check for nans, but that wouldn't catch nans in `weights`.)

**Comment by noamelf** [comment]
Testing with MKL, it issues a warnning:
```
RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
```

**Comment by josef-pkt** [comment]
If this still happens with a recent openblas, then we might have to rethink our nan/missing policy.
I have been using only MKL in recent years and was hoping at openblas also switches to checking for invalid values.

(WLS was also an internal work horse, in GLM, RLM and similar, and at the beginning of statsmodels we didn't want the overhead of additional redundant checks in the models. We have now using a simplified version of WLS in GLM that avoids any overhead. Also, as statsmodels became more widely used, I think choosing defaults that make it easier or safer for users became more important.)

@noamelf  Can you also check how openblas behaves if you replace the nans in `weights` by np.inf?
In a separate process that you can kill, because most likely it also hangs.

**Comment by jbrockmendel** [comment]
On both OSX and Linux (both with openblas), the example above shows a warning but does not freeze

**Comment by josef-pkt** [comment]
This is now redundant AFAICS,
openblas also raises instead of hangs
