### ISSUE TITLE
Unable to import statsmodels

### ISSUE THREAD

**Issue by rishabmarkand** [statsmodels/statsmodels#3527]
I get the following error when I attempt to import statsmodels. (using python version 3.5.2)
```python
ValueError: statsmodels.tsa.statespace._kalman_filter.sKalmanFilter has the wrong size, try recompiling. Expected 5168, got 5792
```
I have tried recompiling as well but to no avail. I'm quite new to this, so I might be overlooking a simple fix to the problem.

**Comment by rishabmarkand** [comment]
When I use python 2.7.12 I get 
```python
ImportError: cannot import name _representation
```

**Comment by josef-pkt** [comment]
Make sure that you have compiled it for the python/numpy/scipy version that you actually use or install statsmodels with.

This sounds a lot like http://stackoverflow.com/questions/17709641/valueerror-numpy-dtype-has-the-wrong-size-try-recompiling/18369312#18369312
when versions are not compiled with the matching numpy or other dependencies.

**Comment by josef-pkt** [comment]
If you are installing from github checkout or building on top of an existing statsmodels version, then you might have to clean cython and binary files from the relevant directories.

aside
when I run the "wrong" python version I get the `numpy.dtype has the wrong size` error

```
>>> import statsmodels.api as sm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
<...>
    from . import _statespace
  File "__init__.pxd", line 155, in init statsmodels.tsa.statespace._statespace
(statsmodels/tsa/statespace/_statespace.c:94371)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
```

**Comment by ChadFulton** [comment]
On Wed, Mar 1, 2017 at 12:36 PM, Josef Perktold <notifications@github.com>
wrote:

> If you are installing from github checkout or building on top of an
> existing statsmodels version, then you might have to clean cython and
> binary files from the relevant directories.
>
>
> Yes, this is my guess for the problem. I have run into this in the past,
and that solved the problem. Right now I can't remember exactly what the
issue is, but basically it happens when `_kalman_filter.pyx.in` doesn't
change, so `cythonize.py` thinks that it doesn't need to re-compile it, but
due to changes in other Cython files (maybe the `.pxd` files? I can't
remember), it should be re-compiled.

I guess we should re-configure cythonize.py to rebuild all state space
files if any of them have changed?

**Comment by josef-pkt** [comment]
@ChadFulton 
Doesn't the re-compile hash and check each file separately?
Right now we are not on a scale where rebuilding the entire statespace binaries would be a heavy burden. So rebuilding all files sounds fine to me, and is more user friendly. (Because I have other untracked modules in the checkout tree that I don't want to delete, I have to figure out which files to manually delete in this case.)

**Comment by rishabmarkand** [comment]
Cleaning and building again works
```shell
python setup.py clean -a
python setup.py build_ext --inplace
```
Able to import now :)
