### ISSUE TITLE
Naming conventions for loglike?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3546]
I noticed there are a couple of loglike-resembling methods with names "llf" or "logL".  Is this an intentional decision?  If not I'd be happy to put together a PR normalizing to "loglike".

**Comment by josef-pkt** [comment]
where did you see logL? It shouldn't be in use outside of old code in the sandbox.

we have `loglike` for the log-likelihood function (as function of `params` and possibly auxiliary parameters like scale) and `llf` for the value of the loglikelihood at the MLE. So these two are different and our standard names.
We also have loglike_obs for the loglikelihood contribution for each observation.

GenericLikelihoodModel has negloglikelihood or similar which was an idea for refactoring to avoid having to take the negative of `loglike` but it was never expanded to the core models.

**Comment by jbrockmendel** [comment]
> It shouldn't be in use outside of old code in the sandbox.

Good to know.  I mistakenly assumed that the sandbox was for newer, not-fully-vetted code.  And yes, the only place I see logL is in sandbox/panel/mixed.py.


> GenericLikelihoodModel has negloglikelihood or similar

I've seen a few "nloglike" methods around.

**Comment by josef-pkt** [comment]
We mostly stopped using the sandbox as staging ground. You can check the history of a module, which should have at most compatibility changes.
There are a very few newer parts in it. And some of the sandbox code is "official" but linked through a regular module, e.g. tukeyhsd in multitest.

`mixed` predates statsmodels and it's doubtful whether it will be "reactivated". GAM is another precursor module, but most likely I will continue with that as a model for partially nonparametric models because the backfitting algorithm has some different use cases than the joint estimation.
