### ISSUE TITLE
NameErrors in grouputils

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3558]
"g" is not defined at this point: https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tools/grouputils.py#L114

One of the arguments is "group".  Is that supposed to be `x[group==cat]` ?

Same thing here: https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tools/grouputils.py#L180

**Comment by josef-pkt** [comment]
Yes, The first one should be group instead of g

I'm not sure about the second one. I never added the sparse version of the sandwiches to statsmodels, where I think I used this. I have a new version of the sparse dummy matrix function in one of the sparse/absorb panel data PR. 

given that groups is supposed to be consecutive integer similar to arange, I think g should be `groups` in the second case.

**Comment by jbrockmendel** [comment]
NameError no big deal.  Closing.
