### ISSUE TITLE
Unreachable code in statespace?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3602]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/statespace/_statespace.pyx.in#L1625

```
            if self.inversion_method & INVERT_UNIVARIATE and self.model.k_endog == 1:
                self.inversion = {{prefix}}inverse_univariate
            elif self.inversion_method & SOLVE_CHOLESKY:
                self.inversion = {{prefix}}solve_cholesky
            elif self.inversion_method & SOLVE_LU:
                self.inversion = {{prefix}}solve_lu
            elif self.inversion_method & INVERT_CHOLESKY:
                self.inversion = {{prefix}}inverse_cholesky
            elif self.inversion_method & INVERT_LU:
                self.inversion = {{prefix}}inverse_lu
```

The ALL_CAPS are non-zero module-level constants that I don't expect users to override.  So it looks like the solve_lu, inverse_cholesky, and inverse_lu branches are never reached.  Is that a) correct and b) intentional?

More generally, is there an older non-blas/lapack version of the cython code?  I'm having a hard time following a lot of what's going on, and when I try to remove redundant code I end up Breaking Everything.

**Comment by ChadFulton** [comment]
>The ALL_CAPS are non-zero module-level constants that I don't expect users to override. So it looks like the solve_lu, inverse_cholesky, and inverse_lu branches are never reached. Is that a) correct and b) intentional?

The `&` there is a "bitwise and", and the `self.inversion` is a bit mask, where `self.inversion` is set in the `KalmanFilter` class, so all those paths are reachable.

> More generally, is there an older non-blas/lapack version of the cython code? I'm having a hard time following a lot of what's going on, and when I try to remove redundant code I end up Breaking Everything.

Unfortunately no. Also `_statespace.pyx.in` is the old version of the Cython code where everything was stuffed into one file. the `_representation.pyx.in`, `_kalman_filter.pyx.in`, ... files are the new version.

I don't know what to recommend w.r.t. the Cython code - other than that I'll try and help explain what's going on when questions come up.

**Comment by jbrockmendel** [comment]
> The & there is a "bitwise and", and the self.inversion is a bit mask, where self.inversion is set in the KalmanFilter class, so all those paths are reachable.

Seems to shore up my claim 
> I'm having a hard time following a lot of what's going on

>  Also _statespace.pyx.in is the old version of the Cython code where everything was stuffed into one file

That explains why there is so much apparent overlap there.

> I don't know what to recommend w.r.t. the Cython code - other than that I'll try and help explain what's going on when questions come up.

I'd like to choose a small chunk of the cython code and write a non-lapack version of it so I can get a better handle on it.  I've hit a stumbling block in converting from the `{{cython_type}} * _foo` views into np arrays that I can actually work with.  If you can help me figure that out, I should be able to make some headway.

Let's take `companion_predicted_state_cov` from `_filters._univariate.pyx.in`.  

```
cdef void {{prefix}}companion_predicted_state_cov({{prefix}}KalmanFilter kfilter, {{prefix}}Statespace model):
    cdef:
        int i, j, idx
        int inc = 1
        {{cython_type}} alpha = 1.0
        {{cython_type}} beta = 0.0
        {{cython_type}} tmp

    # $P_{t+1} = T_t P_{t,n} T_t' + Q_t^*$
    
    # `tmp0` array used here, dimension $(p \times m)$  
    # $\\#_0 = \phi_t P_{t|t} $

    # $(p \times m) = (p \times m) (m \times m)$
    blas.{{prefix}}gemm("N", "N", &model._k_posdef, &model._k_states, &model._k_states,
          &alpha, model._transition, &model._k_states,
                  kfilter._filtered_state_cov, &kfilter.k_states,
          &beta, kfilter._tmp0, &kfilter.k_states)
                
    # $P_{t+1} = 1.0 \\#_0 \phi_t' + 1.0 \\#$  
    # $(m \times m) = (p \times m) (m \times p) + (m \times m)$
    blas.{{prefix}}gemm("N", "T", &model._k_posdef, &model._k_posdef, &model._k_states,
          &alpha, kfilter._tmp0, &kfilter.k_states,
                  model._transition, &model._k_states,
          &beta, kfilter._predicted_state_cov, &kfilter.k_states)
```

My understanding is that this should be roughly equivalent to:

```
transition = omega_operator(model._transition)
kfsc = omega_operator(kfilter._filtered_state_cov)
predicted_state_cov = np.dot(np.dot(transition, kfsc), transition.T)
kfilter._predicted_state_cov[:] = np.asfortranarray(predicted_state_cov)
```

Where `omega_operator` is defined as "the operator that takes the thing you have and returns the thing you need".  I've tried a bunch of variants of `np.asarray` and cythonize objects to all of them.  Suggestions?

**Comment by ChadFulton** [comment]
Fortunately this has an easy explanation: all the Cython attributes beginning with an `_` are pointers to some memory block of a memoryview object which has the same name but is not prefixed by an underscore.

So `model._transition` is a pointer to a location in `model.transition`, where `model.transition` is a memoryview so that `np.array(model.transition)` will work just fine.

Since `_statespace.pyx.in` is essentially deprecated, I'll ignore it and talk about the other version (although the same basic ideas map over, but just maybe different places in the code / different method names).

The pointers are set at each iteration of the Kalman filter or smoother in the `{{prefix}}Statespace.seek` method and in the `initialize_statespace_object_pointers`, `initialize_filter_object_pointers`, and `initialize_smoother_object_pointers` methods of `{{prefix}}KalmanFilter` and `{{prefix}}KalmanSmoother`.

So for example when the Kalman filter is performing the time `t` iteration, `model._transition` is a pointer either to `model.transition[0, 0, 0]` if the transition matrix is time invariant or `model.transition[0, 0, t]` if it is time-varying.

This makes it convenient for the actual filtering / smoothing functions to (mostly) not have to worry about time-varying matrices, etc. Instead, they just ready and write data from the correct arrays just by using the pointer.

**Comment by jbrockmendel** [comment]
Excellent, thanks.  This seems to _mostly_ work in when I tried to de-lapack the call to `_representation.{{prefix}}select_cov` from inside `initialize_stationary`.  The function `select_cov` is basically just two calls to `gemm`:

```
    if k_posdef > 0:
        blas.{{prefix}}gemm("N", "N", &k, &k_posdef, &k_posdef,
              &alpha, selection, &k,
                      cov, &k_posdef,
              &beta, tmp, &k)
        # $Q_t^* = 1.0 * \\#_0 R_t'$  
        # $(m \times m) = (m \times r) (m \times r)'$
        blas.{{prefix}}gemm("N", "T", &k, &k, &k_posdef,
              &alpha, tmp, &k,
                      selection, &k,
              &beta, selected_cov, &k)
```

The original call inside `initialize_stationary` is:

``` 
        {{prefix}}select_cov(self.k_states, self.k_posdef,
                                   &self.tmp[0,0],
                                   &self.selection[0,0,0],
                                   &self.state_cov[0,0,0],
                                   &self.selected_state_cov[0,0,0])
```

Which I replaced with:

```
        state_cov = np.array(self.state_cov[0, 0, 0], dtype={{dtype}})
        selection = np.array(self.selection[0, 0, 0], dtype={{dtype}})
        selected_cov = np.dot(np.dot(selection, state_cov), selection.T)
        
       {{prefix}}select_cov(self.k_states, self.k_posdef,
                                   &self.tmp[0,0],
                                   &self.selection[0,0,0],
                                   &self.state_cov[0,0,0],
                                   &self.selected_state_cov[0,0,0])
        
        if self.k_posdef > 0:
             # Check that the selected_cov matches the results of `select_cov`.
             v1 = np.array(self.selected_state_cov[0, 0, 0], dtype={{dtype}})
             assert (v1 == selected_cov).all(), (v1, selected_cov,)
             # self.selected_state_cov[0, 0, 0] = selected_cov
```

When I run it exactly as above, the tests pass.  When I assert  that `np.dot(selection, state_cov)` matches self.tmp[0,0], it goes through.  When I un-comment the line `# self.selected_state_cov[0, 0, 0] = selected_cov`, it is still OK.  But when I go all the way to commenting out the call to `select_cov`, tests start failing.

I get 2 errors and 6 failures (out of 699 tests) with what looks like numerical approximation issues:
```
======================================================================
FAIL: tsa.statespace.tests.test_dynamic_factor.TestSUR_autocorrelated_errors.test_bse_approx
----------------------------------------------------------------------
Traceback (most recent call last):
[...]
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-05

(mismatch 20.0%)
 x: array([  8.357961e-05,   4.208827e-08,   8.498468e-06,   4.258066e-09,
         1.102768e-07,   5.265173e-09,   2.519241e-09,   1.921052e-01,
         8.593638e-04,   1.321027e-02])
 y: array([  8.357000e-05,   4.209000e-08,   8.402000e-06,   4.222000e-09,
         1.103000e-07,   5.110000e-10,   1.259537e-02,   1.938210e-01,
         8.593600e-04,   1.321035e-02])
```

In a few of the other cases the numerical mismatches are more severe, and the errors that show up are 
```
    raise np.linalg.LinAlgError('Non-positive-definite forecast error'
LinAlgError: Non-positive-definite forecast error covariance matrix encountered at period 0
```

My next guess was that `self.tmp` gets assigned to in the first call to `gemm` and that maybe that state needed saving, so I tried adding

```
    if self.k_posdef > 0:
        tmp = np.dot(selection, state_cov)
        self.tmp[0, 0] = np.asfortranarray(tmp, dtype={{dtype}})
```

(Also tried a variant that assigned to `self.tmp[:]`) This did not appear to impact the failures above.

**Comment by ChadFulton** [comment]
```python
state_cov = np.array(self.state_cov[0, 0, 0], dtype={{dtype}})
selection = np.array(self.selection[0, 0, 0], dtype={{dtype}})
selected_cov = np.dot(np.dot(selection, state_cov), selection.T)
```

Is this the code you're using? To allow for multivariate models you'd need to select the entire matrix: 

```python
state_cov = np.array(self.state_cov[:, :, 0], dtype={{dtype}})
selection = np.array(self.selection[:, :, 0], dtype={{dtype}})
selected_cov = np.dot(np.dot(selection, state_cov), selection.T)
```

although if you were using the former code, then I would think a lot of tests should fail

**Comment by ChadFulton** [comment]
I assume this is all mostly exploratory on your part? Or was there some specific aim you have?

**Comment by jbrockmendel** [comment]
> I assume this is all mostly exploratory on your part? Or was there some specific aim you have?

I'm especially interested in the tsa models and want to actually understand what's going on behind the scenes (especially since you've suggested more of the functionality will be inheriting from statespace going forward).  I also have a suspicion that this section of the code has been less-audited than other sections, so the marginal value of a pair of eyes may be high.

> although if you were using the former code, then I would think a lot of tests should fail

All of the tests pass when I use the `[0, 0, 0]` version.  The code I am using verbatim:

```
        # Create selected state covariance matrix
        state_cov = np.array(self.state_cov[0, 0, 0], dtype={{dtype}})
        selection = np.array(self.selection[0, 0, 0], dtype={{dtype}})
        tmp = np.dot(selection, state_cov)
        selected_cov = np.dot(tmp, selection.T)

        # 2017-04-07 12:26 commenting out the next line breaks things for reasons i dont understand
        {{prefix}}select_cov(k_states, self.k_posdef, &self.tmp[0, 0], &self.selection[0, 0, 0], &self.state_cov[0, 0, 0], &self.selected_state_cov[0, 0, 0])
        
        #v1 = np.array(self.selected_state_cov[0, 0, 0], dtype={{dtype}})
        #v1tmp = np.array(self.tmp[0, 0], dtype={{dtype}})
        #assert (v1 == selected_cov).all(), (v1, selected_cov,)
        #assert (v1tmp == tmp).all(), (v1tmp, tmp,)
        # assert False # 2017-04-07 08:55 this got hit
        
        if self.k_posdef > 0:
            #self.tmp[0, 0] = np.asfortranarray(tmp, dtype={{dtype}})
            self.selected_state_cov[0, 0, 0] = np.asfortranarray(selected_cov, dtype={{dtype}})
            # The v1 == selected_cov and v1tmp == tmp assertions pass, but commenting out
            # the select_cov call breaks tests for some reason
            # Assigning to self.tmp doesn't seem to help.

```

**Comment by ChadFulton** [comment]
If you use the [0, 0, 0] version, then you're only setting the top left element of the selected state covariance matrix. Since in general it is a `k_states x k_states` matrix, the rest of the matrix is being set by the `{{prefix}}select_cov` function so that likely explains why things break when it's commented out.

**Comment by ChadFulton** [comment]
> I'm especially interested in the tsa models and want to actually understand what's going on behind the scenes (especially since you've suggested more of the functionality will be inheriting from statespace going forward). I also have a suspicion that this section of the code has been less-audited than other sections, so the marginal value of a pair of eyes may be high.

Sounds great, I'm sure that you'll turn up some useful improvements.

**Comment by jbrockmendel** [comment]
> If you use the [0, 0, 0] version, then you're only setting the top left element of the selected state covariance matrix.

So in some contexts [0,0,0] is a pointer to the entire array, and in others it is just one element like usual?

Anyway, I've tried a bunch of variants with [:, :, 0], [:, :, :],... and they are all breaking in dramatic ways:

```
        # Create selected state covariance matrix
        state_cov = np.array(self.state_cov[:, :, 0], dtype={{dtype}})
        selection = np.array(self.selection[:, :, 0], dtype={{dtype}})
        tmp = np.dot(selection, state_cov)
        selected_cov = np.dot(tmp, selection.T)

        {{prefix}}select_cov(k_states, self.k_posdef, &self.tmp[0, 0], &self.selection[0, 0, 0], &self.state_cov[0, 0, 0], &self.selected_state_cov[0, 0, 0])

        if self.k_posdef > 0:
            v1 = np.array(self.selected_state_cov[:, :, 0], dtype=selected_cov.dtype)
            fselected_cov = np.asfortranarray(selected_cov)
            np.testing.assert_allclose(v1, fselected_cov)
            self.selected_state_cov[:, :, 0] = fselected_cov
```

The assertions frequently fail, but not reliably.  The assignment to `self.selected_state_cov` often raises `TypeError: only length-1 arrays can be converted to Python scalars`.  In versions where I compare `tmp` to `self.tmp`, I get shape mis-match errors.

This is just a single matrix multiplication; should be about the simplest case we can find.  To skip a few steps of me guessing, do you know of a just-numpy way of cutting out the `select_cov` call?

Related: are the tmpN arrays needed in between calls?  i.e. if I instantiated new arrays instead of using the pre-allocated ones, would it make a difference for anything other than performance?

**Comment by ChadFulton** [comment]
A couple of things:

1. As far as I know, you can't generally assign a numpy array to a memoryview as you're doing in `self.selected_state_cov[:, :, 0] = fselected_cov`. I guess it maybe works for a scalar entry, which is why you get the `TypeError`.
2. `np.array` has `copy=True` by default, so if you want to convert from a memoryview to a numpy array and then assign values to that numpy array in such a way that it affects the memoryview, you must use `copy=False`.

However, if you want a numpy array and a memoryview to share data, you have to be pretty careful to make sure that nothing goes wrong.

So you can comment out the `{{prefix}}select_cov(...)` call and replace it with the following:

```python
R = np.array(self.selection[:, :, 0])
Q = np.array(self.state_cov[:, :, 0])
view = np.array(self.selected_state_cov, copy=False)
view[:, :, 0] = np.asfortranarray(R.dot(Q).dot(R.T))
```

**Comment by jbrockmendel** [comment]
Thanks, you've gone above-and-beyond on this one.  That seems to work on that example and in a few other places I've tried it.  This will get me a long way towards getting a handle on this.

**Comment by ChadFulton** [comment]
No problem, glad it was helpful. 

> Related: are the tmpN arrays needed in between calls? i.e. if I instantiated new arrays instead of using the pre-allocated ones, would it make a difference for anything other than performance?

I forgot to answer this earlier - the tmpN arrays are important and not using them will probably break some things. They are called tmpN for two reasons: first, when we just had the filter, they really were temporary and weren't stored. But they're needed for the smoother too, so I ended up changing them to no longer be temporary. The second reason is that I didn't have any good names for them.

**Comment by jbrockmendel** [comment]
Follow up question on indexing:

In _kalman_filter.pyx.in, `self._forecast_error_cov` is set to `&self.forecast_error_cov[0, 0, forecast_t]`.  

Then in _filters._conventional.{{prefix}}forecast_conventional , this is accessed with a single index:

```
if not kfilter.converged:
    # $\\# = H_t$
    for i in range(model._k_endog): # columns
        for j in range(model._k_endog): # rows
            kfilter._forecast_error_cov[j + i*kfilter.k_endog] = model._obs_cov[j + i*model._k_endog]
```

Is accessing `kfilter._forecast_error_cov[j + i*kfilter.k_endog]` equivalent to something like `kfilter._forecast_error_cov[i, j]`?

This pattern seems to show up a lot, so grokking it will be a big boost.

**Comment by ChadFulton** [comment]
`kfilter._forecast_error_cov` is a pointer to the memory location of `kfilter.forecast_error_cov[0, 0, t]`, and so `kfilter._forecast_error_cov[i]` does some pointer arithmetic to retrieve the memory location corresponding to the i-th "data element" where data element depends on the size of the datatype.

Since the arrays are stored in column-major order (i.e. Fortran order), `kfilter._forecast_error_cov[0]` corresponds to the [0, 0, t] element of kfilter.forecast_error_cov, `kfilter._forecast_error_cov[1]` corresponds to the [1, 0, t] element, and `kfilter._forecast_error_cov[j + i*kfilter.k_endog]` correponds to the [j, i, t] element.

**Comment by jbrockmendel** [comment]
That indexing point helped resolve a big chunk of my remaining issues.  Next up is a softball question:

Are the pure-python versions of representation.py, kalman_filter.py, and kalman_smoother.py still used outside of compatibility mode?

**Comment by ChadFulton** [comment]
> Are the pure-python versions of representation.py, kalman_filter.py, and kalman_smoother.py still used outside of compatibility mode?

> Update: Never mind; obviously "no".

Actually, they are still used, and there's no plan to drop them. The Cython classes allow us to run the filter itself with little overhead, but their inputs have strict requirements. In particular, they're tied to a specific datatype (e.g. `dKalmanFilter` can only handle double precision floating point) and the arrays must be passed in Fortran order.

The Python classes `Representation`, `KalmanFilter`, `KalmanSmoother`, and `SimulationSmoother` act as an interface layer, so that users don't have to worry about datatypes, etc. (one of the biggest reasons for supporting multiple datatypes is that by default the Hessian is computed using complex-step derivatives).

However, `_pykalman_smoother.py` is a pure python implementation of the Kalman smoother routines, and it is not used outside of compatibility mode.

**Comment by jbrockmendel** [comment]
Woops, I mis-counted the negatives in my update.  I meant that they were clearly not-superfluous.  The clarification re: the interface layers is helpful.

I've spent enormously too much time on this over the last week, so it's time to lay it to rest.  Here are my take-aways from going pouring over this section of the code:

1) Tempita is neat.

2) Making tons of calls to `np.asfortranarray` and the other kludges I needed to get rid of some blas/lapack calls slow down the tests by about a factor of 4.

3) The ability to profile the code would be helpful.  For all I know `np.asfortranarray` is harmless and the slowdown could be coming from use of `np.dot`.

4) Code coverage would be helpful.  I ended up putting `assert False` statements all over the place to figure out what was actually hit.

5) There are a bunch of functions/methods that are never hit (if there's an interest, I can put together a list).

6) The np.asfortranarray/copy=False technique you suggested above works in many but not all places.  I have a hard time predicting when it will and won't work.  An example:

In _smoothers._univariate, I can successfully replace

```
blas.{{prefix}}gemm("T", "N", &model._k_states, &model._k_states, &model._k_states,
                                      &alpha, model._transition, &model._k_states,
                                              smoother._scaled_smoothed_estimator_cov, &kfilter.k_states,
                                      &beta, smoother._tmp0, &kfilter.k_states)
```

with

```
m_k_states = model._k_states
scaled_smoothed_estimator_cov = np.array(smoother.scaled_smoothed_estimator_cov, copy=False)
tmp0 = np.array(smoother.tmp0, copy=False)
transition = np.array(model.transition, copy=False)
tmp0[:m_k_states, :m_k_states] = np.asfortranarray(
    np.dot(
         transition[:m_k_states, :m_k_states, transition_t].T,
         scaled_smoothed_estimator_cov[:m_k_states, :m_k_states, scaled_t]
         )
    )
```

But several lines above I _cannot_ replace

```
blas.{{prefix}}gemv("T", &m_k_states, &m_k_states,
            &alpha, &model.transition[0, 0, transition_t],
            &m_k_states, &smoother.scaled_smoothed_estimator[0, scaled_t], &inc,
            &beta, &smoother.scaled_smoothed_estimator[0, period-1], &inc)
```

with 

```
        scaled_smoothed_estimator = np.array(smoother.scaled_smoothed_estimator, copy=False)
        transition = np.array(model.transition, copy=False)
        scaled_smoothed_estimator[:, period-1] = np.asfortranarray(
            np.dot(
                transition[:, :, transition_t].T,
                scaled_smoothed_estimator[:, scaled_t]
                )
            )
```

7) Same goes for `blas.{{prefix}}copy` vs np.ndarray's copy method.  Example:

In _filters._univariate, the following are apparently _not_ equivalent:
```
blas.{{prefix}}copy(&kk_states, &kfilter.predicted_state[0, predicted_t], &inc, &kfilter.filtered_state[0, filtered_t], &inc)
kfilter.filtered_state[:, filtered_t] = kfilter.predicted_state[:, predicted_t].copy() # Regardless of whether I keep the ".copy()" or not.
```

On the flip side, in _filters._inversions, the following _are_ equivalent:
```
blas.{{prefix}}copy(&kfilter.k_endog2, kfilter._forecast_error_cov, &inc, kfilter._forecast_error_fac, &inc)
kfilter.forecast_error_fac[:, :] = kfilter.forecast_error_cov[:, :, forecast_t]
```

8) Also `blas.{{prefix}}axpy`, skipping the example on this one.

9) The way model._* gets filled in `_select_missing_partial` makes it difficult to work with e.g. model._obs_cov later on because if the unpredictable dimension.  Would it be feasible to keep the shapes constant and fill in NaNs in the partially-missing case?

10) Where possible, I advocate (and volunteer to help with) making methods into functions (e.g. in _simulation_smoother the `transform_variates` and `cholesky` methods never use `self`).  Making these stateless functions would make them much easier to test.

**Comment by ChadFulton** [comment]
>Making tons of calls to np.asfortranarray and the other kludges I needed to get rid of some blas/lapack calls slow down the tests by about a factor of 4.

> The ability to profile the code would be helpful. For all I know np.asfortranarray is harmless and the slowdown could be coming from use of np.dot.

Since e.g. `np.dot` calls `?gemm`, the difference in timing is due to "overhead". Much of the overhead is due to numpy checks (e.g. make sure there are no `nan` values) and some of the overhead is converting the Numpy array to something that can be used by Fortran. So both are harmful, I don't know how much of the timing different can be attributed to each. I do know that excessive conversions between memoryviews and Numpy arrays (which is done when you use `np.asfortranarray`) destroys the performance boost from using Cython.

> The ability to profile the code would be helpful. For all I know np.asfortranarray is harmless and the slowdown could be coming from use of np.dot.

You can profile to a certain extent by adding the directive `# cython: profile=True` into the files, but that effects performance so we don't want it in master. Although I should note that because some of the functions are assigned dynamically to pointers, they don't profile well.

> Code coverage would be helpful. I ended up putting assert False statements all over the place to figure out what was actually hit.

I don't know how to determine coverage in Cython, but this would be a great improvement, I agree.

> There are a bunch of functions/methods that are never hit (if there's an interest, I can put together a list).

Sure, that would be great. My impression (which could be wrong!) is that this is probably not true, but many of the functions are only hit in special cases.

> The np.asfortranarray/copy=False technique you suggested above works in many but not all places. I have a hard time predicting when it will and won't work. An example:

Part of the reason for using Cython is the ability to have finer-grained control of e.g. memory structures, so it's not too surprising to me that it doesn't always map over 100%. If there are specific issues we can diagnose them.

> The way model._* gets filled in _select_missing_partial makes it difficult to work with e.g. model._obs_cov later on because if the unpredictable dimension. Would it be feasible to keep the shapes constant and fill in NaNs in the partially-missing case?

This is not possible because Fortan will die if it is passed arrays with NaN, and it needs contiguous data.

> Where possible, I advocate (and volunteer to help with) making methods into functions (e.g. in _simulation_smoother the transform_variates and cholesky methods never use self). Making these stateless functions would make them much easier to test.

This is probably a good idea; I never personally found the cost-benefit ratio to work out such that I would actually do it, but I would be happy to support such an effort.

**Comment by ChadFulton** [comment]
> The way model._* gets filled in _select_missing_partial makes it difficult to work with e.g. model._obs_cov later on because if the unpredictable dimension. Would it be feasible to keep the shapes constant and fill in NaNs in the partially-missing case?

Also, I should mention that there are some functions in `_tools.pyx.in` that reorder time-varying matrices to retrieve the matrix you want. I use them to reconstruct the arrays at the end (i.e. in the `FilterResults` class, I think) when there are partially missing observations. Unfortunately they're probably not too well documented.

**Comment by jbrockmendel** [comment]
>> You can profile to a certain extent by adding the directive # cython: profile=True into the files,

>> I don't know how to determine coverage in Cython, but this would be a great improvement, I agree.

These both seem to work better in theory than in practice.  See #3588 

>> Although I should note that because some of the functions are assigned dynamically to pointers, they don't profile well.

How much mileage is gained from assigning those functions to pointers?  In reading the code I incur a non-trivial penalty in keeping track of them.  The current setup also requires that each of the referenced functions have identical signatures.  Losing that requirement would simplify the making-functions-functional goal.

>> My impression (which could be wrong!) is that this is probably not true, but many of the functions are only hit in special cases.

I should clarify: when I say never hit, I mean specifically in the tests.

>> I never personally found the cost-benefit ratio to work out such that I would actually do it, but I would be happy to support such an effort.

I'll start making some small PRs and chip away at this.

**Comment by ChadFulton** [comment]
> How much mileage is gained from assigning those functions to pointers? In reading the code I incur a non-trivial penalty in keeping track of them. The current setup also requires that each of the referenced functions have identical signatures. Losing that requirement would simplify the making-functions-functional goal.

It's a matter of when to deal with the different options (filtering method, inversion type, etc.). This way, the actual filter iteration in `__next__` is straightforward (well pretty straightforward). Otherwise you need a bunch of conditional statements each time call the updating step, the prediction step, etc.

> Losing that requirement would simplify the making-functions-functional goal.

I'm not sure that's my goal :)

> I'll start making some small PRs and chip away at this.

Just to warn you, there are two things that make it more difficult to make changes to the Cython code:

1. It's much easier to introduce subtle bugs (for example #3386)
2. It's somewhat easy to make a change that seems innocuous but ends up creating a performance regression.

For the latter, I wish we had a benchmarking suite set up (because I'm pretty sure that as I've added features I've accidentally introduced some performance hits), but we don't yet.

**Comment by jbrockmendel** [comment]
... And I've managed to spend another day not getting real work done.  Tomorrow I'm declaring a github moratorium.

> It's a matter of when to deal with the different options (filtering method, inversion type, etc.). 

The alternative I'm envisioning is to define `prediction`, `forecasting`, `updating`... methods directly and then within those methods do the various checks and dispatch to the appropriate function.  `__next__` would be pretty much untouched.  There would be some overhead from redundant checks.  My prior is that it would be small, but you may have a more informed opinion on the subject.

> This way, the actual filter iteration in `__next__` is straightforward (well pretty straightforward).

'straightforward' is a major part of what I'm trying to maximize.

> Otherwise you need a bunch of conditional statements each time call the updating step, the prediction step, etc.

At least in _kalman_filter.pyx.in, `initialize_function_pointers` gets called once in each iteration of `__next__`.  Evaluating the conditionals separately within prediction/forecasting/updating means checking these ~4 times as often, which again I expect would be small, but merits measurement.

>> Losing that requirement would simplify the making-functions-functional goal.

> I'm not sure that's my goal :)

Fair enough.  This is your house.  But it sounds like thorough testing and benchmarking are among your goals, and the lack of coverage reports make that especially difficult.  I claim that cleaner separation will improve several of these things.  When I crawl out from under the pile of real work that I've let build up, we'll see if that theory pans out.

**Comment by jbrockmendel** [comment]
Several comments back we touched on the various tmpN arrays and whether they contain persistent state information.

> They are called tmpN for two reasons: first, when we just had the filter, they really were temporary and weren't stored. But they're needed for the smoother too, so I ended up changing them to no longer be temporary. The second reason is that I didn't have any good names for them.

I think this merits the marginal effort to give meaningful names to the subset of these that need to be persisted.  1) They don't _all_ contain state information, and it would be helpful to know which is which.  2) `smoother` and `kfilter` both have `tmp0`, `tmp00`... which presents an easy way to screw up.

It looks like the most relevant cases are kfilter's tmp[1-4].  These have brief descriptions in the comments:

tmp1 --> `# $\\#_1 = P_t Z_t'$`
tmp2 --> `# $\\#_2 = F_t^{-1} v_t$`
tmp3 --> `# $\\#_3 = F_t^{-1} Z_t$`
tmp4 --> `# $\\#_4 = F_t^{-1} H_t$`

Here I think $Z_t$ corresponds to `model._design`, $v_t$ is `forecast_error`, $F_t$ is "Forecast error covariance matrix for time t", and $H_t$ corresponds to `model._obs_cov`. 

The $F_t^{-1}$ are normalizations, so how about aliasing tmp2, tmp3, and tmp4 to "normalized_forecast_error", "normalized_design", and "normalized_obs_cov", respectively?  Not sure what to call tmp1.

**Comment by jbrockmendel** [comment]
Functions/branches not hit in tests:

`_inversions.{{prefix}}inverse_cholesky`
`_inversions.{{prefix}}inverse_lu`
`_filters._univariate.{{prefix}}companion_predicted_state`
`_filters._univariate.{{prefix}}companion_predicted_state_cov`

Note: in `_filters._univariate.{{prefix}}prediction_univariate`, the `not model.companion_transition` is always `True` in tests.
In `_filters._univariate.{{prefix}}temp_arrays`, among others, the `model.subset_design` condition is never `True` in tests.

**Comment by ChadFulton** [comment]
> Functions/branches not hit in tests:

Thanks for going through the effort to check this.

> _inversions.{{prefix}}inverse_cholesky
_inversions.{{prefix}}inverse_lu

Good catch. These should be tested. I guess they could be removed, because the linear solver routines (solve_cholesky, solve_lu) are probably almost always better. But I think it'd be easy to test them, we just need to add some tests with `mod.ssm.set_inversion_method(0, invert_cholesky=True)` and similar for `invert_lu`.

> _filters._univariate.{{prefix}}companion_predicted_state
_filters._univariate.{{prefix}}companion_predicted_state_cov

To be honest I forgot these were in there, along with the `subset_design` options. There is no public interface option to use this option yet, because there are no unit tests for it and because it only applies (as far as I remember) to the univariate approach.

To give a brief idea: these are setup to get some cheap "sparse computations" in the special cast of a companion form transition matrix. For example, if a dynamic factor model has 4 factors with 13 lags, then there are 52 state variables, but only the first 4 of them are relevant for a lot of operations. The transition matrix is in companion form, and there were some simplifications I was able to come up with for improved performance. Similarly, the design matrix would be sized k_endog x 52, but columns 5-52 are simply zeros, so that is what `subset_design` means. This was mainly for large dynamic factor models I was working with. 

In the long run, we might consider more of these optimizations, if there was enough of a speed benefit to offset the increased code complexity. A couple of other simple ones include diagonal observation or state covariance matrices, or when the observation covariance is all zeros.

**Comment by ChadFulton** [comment]
> The $F_t^{-1}$ are normalizations, so how about aliasing tmp2, tmp3, and tmp4 to "normalized_forecast_error", "normalized_design", and "normalized_obs_cov", respectively? Not sure what to call tmp1.

I'm not sure that these particular matrices are really "normalizations", any more than any matrix muliplied by another matrix is a normalization. `tmp2` is the closest, but it seems to me that it's really the Cholesky factorization that standardizes it.

I agree that more explicit names are better, but the problem with naming things is that then you have to keep around the names for potentially a long time, so a bad name can stick around. What do you think about e.g. just replacing `tmp_1` with `tmp_PZ` or even `tmp_predicted_state_cov_design`?

**Comment by jbrockmendel** [comment]
Agreed that `tmp2` is the main case for which "normalization" is the appropriate term.  I don't have a strong opinion on what these names should be, just that it should be very clear which things contain state information (or conversely, which things I can mess around with without breaking things).

For arrays that exist only to have pre-allocated memory within function calls, the most important characteristic is its shape.  So how about baking those into the names?  `kfilter.tmp0` is `k_states` x `k_states`, so its pointer could be `kfilter._tmp_ss`.  `smoother.tmp00` is `k_states` x `k_endog`, so its pointer could be `smoother._tmp_se`.

> the problem with naming things is that then you have to keep around the names for potentially a long time, so a bad name can stick around

These are pretty well marked as private (both by `_foo` convention and `cdef` implementation).  But your point is well-taken.

Side-note before I forget: in the _smoother* classes, there are `tmp0`, `tmp00`, `tmp000`, tmp_autocov, `tmpL`, and `tmpL2`.  I haven't looked at these as carefully as the _filter* classes, but it looks like `tmpL` is the only one of these that carries state across function calls.

Another possible simplification: `model.k_states == model._k_states == kfilter.k_states`.  Same with `k_posdef`.  It's only `k_endog` that can differ.

There are a couple of patterns that I saw in a bunch of places that might merit refactoring out into functions.  In particular `X = A'BA` or sometimes `X = A'BA + C`.

**Comment by jbrockmendel** [comment]
@chadfulton looking over kalman_loglike.pyx, is there a reason why in some case you use `ndarray[double, ndim=2]` and in others `double[:, :]`?  I thought the latter was strictly preferred at this point.

**Comment by ChadFulton** [comment]
yes, I think you're right. `kalman_loglike.pyx` was written before my time and I think is just being kept as-is for now to maintain backwards compatibility with `arima_model.py`, etc.
