### ISSUE TITLE
October 17 Comment Clarification

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3650]
A [comment](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/regression/linear_model.py#L1983) in `compare_lr_test`:

```
        # See mailing list discussion October 17,

        if large_sample:
            return self.compare_lm_test(restricted, use_lr=True)
```

Despite my best efforts, there is an October 17 every year.  Any idea which thread this refers to?  This method is not hit in unit tests, so I'm hoping the thread contains an example.

**Comment by josef-pkt** [comment]
looks like 2010 searching my gmail archive (which is the oldest discussion on compare_lr_test that I find)
https://groups.google.com/d/msg/pystatsmodels/BDL9wsjzaGk/lNOGsWQJZZsJ "Comparing models"

there were some changes since then to the function.
no unit test is not good.
(in discrete models we have llnull for LR test against constant-only model, but I don't know if Stata has it for OLS.)
