### ISSUE TITLE
patsy inversion?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3655]
I'm focusing a lot on test coverage, and there are bunch of one-line patsy cases that are missing.  e.g. from `regression._prediction.get_prediction`:

```
    ### prepare exog and row_labels, based on base Results.predict
    if transform and hasattr(self.model, 'formula') and exog is not None:
        exog = patsy.dmatrix(self.model.data.design_info.builder, exog) # TODO: not hit in tests
```

Rather than writing an entirely new test to hit this line, I'd like to take an existing test and patsify it using a hypothetical `to_formula` method.  Something like:

```
def test_case():
    model = SomeModel(...)
    [existing test]

    (formula, data) = model.to_formula()
    model2 = SomeModel.from_formula(formula, data)
    [copy/paste of existing test]
```

(Come to think of it, I probably wouldn't want `to_formula` in the model namespace, but it might be a reasonable `tools._testing` function).

I don't work with patsy much, so don't know what a `to_formula` implementation would look like.  Before I dig into this: any thoughts?

**Comment by josef-pkt** [comment]
I'm not sure about this.

formulas could be easily created from the existing model, but only with a variable defined by each column of exog. This wouldn't test the `transform` part, because there is no transform like calling a function or converting categoricals.

My guess is that it would be better to attach this test assert to an existing unit test that already uses formula. Possibly we need to add more test cases with formulas.

`get_prediction` is still partially WIP. (I'm not completely sure about the design and API yet.)

**Comment by jbrockmendel** [comment]
Thanks.  I've got enough irons in the fire, am happy to leave this one be.
