### ISSUE TITLE
cov_struct.Nested AttributeError 'vcomp_coeff'

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3668]
Implemented a smoketest locally to hit `genmod.cov_struct.Nested.summary`, got:

```
    for k in range(len(self.vcomp_coeff)):
AttributeError: 'Nested' object has no attribute 'vcomp_coeff'
```

It looks like `vcomp_coeff` gets set in `update` but not `__init__`.  This test happens to call `summary` immediately after instantiation, so breaks.  Seems like the fix is to either a) set `vcomp_coeff={}` in `__init__` or b) prevent early calls to `summary`.  I'll circle back to this in a few days if no one else has gotten to it.

**Comment by josef-pkt** [comment]
AFAIU:  
This is currently only used a part of GEE and not designed for standalone use (*). Fine if there are obvious fixes, but I'm not in favor of raising intentional exception for internal use as in `b) prevent early calls to summary` (also given that there is already an exception that is at least partially informative)

Also, unless you put code in a PR, it is useful to have a full example attached to the issue.

(*) I tried once to (mis)use the cov_struct for other examples outside of GEE, but they are currently very tightly integrated with the GEE usecase.
