### ISSUE TITLE
statespace optimizations

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3699]
`MLEModel` and its subclasses use numeric derivatives for `score` and `hessian`, which means their `loglike` methods get called _a lot_.  If we could calculate `score` as part of the intermediate calculations within `filter`, there is a pretty big performance win available.  I think a bunch of second-order terms will wash away nicely and we'll be left with a bunch of linear chain-ruling.  But since its cython, I can only offer semi-skilled labor at best.

**Comment by ChadFulton** [comment]
Sounds like a good idea, although I'm not quite sure what you're suggesting. Are you thinking of something like automatic differentiation, or are you thinking of something like Harvey's method (section 3.4.6, for future reference) for computing the analytic derivatives by adding some extra recursions to the filter? Or are you thinking of something different?

Another option is [this paper](http://scholar.harvard.edu/files/score92.pdf); I implemented it in Cython and tested it out with high dimensional dynamic factor models, but I found it to be inferior to just using the EM algorithm. Also, it is model-specific, so we would have to set it up for each model we wanted to use it with. Finally, for models with a smaller number of parameters, the likelihood function is so fast to compute it doesn't make sense to run the smoother, since a lot more needs to be computed and saved then. After finding these things out, I lost interest in computing the exact score :)

**Comment by jbrockmendel** [comment]
> Are you thinking of something like automatic differentiation, or are you thinking of something like Harvey's method 

Very roughly, the thought was that the loglike is quadratic in the forecast_error, that each period's conditional forecast_error[n] is linear in params and the previous state, and that the previous state is itself linear [...].  Ideally we'd be able to augment `{{prefix}}forecast_conventional` (guesswork here, since the cython in statespace still holds some mystery for me) to calculate `∂ forecast` at the same time as `forecast`.  From there the hope is that the score would be relatively straightforward.

It isn't obvious to me if we'd be able to do this in "one pass" or if we'd need to do something resembling back-prop.

> (section 3.4.6, for future reference)

Of what?  In Lutkepohl (2005) that points at an equation for VAR loglikes.

> Another option is this paper; I implemented it in Cython and tested it out with high dimensional dynamic factor models, but I found it to be inferior to just using the EM algorithm.

I'll take a look at that.

> Also, it is model-specific, so we would have to set it up for each model we wanted to use it with.

Yah, that's a pretty big drawback.

> Finally, for models with a smaller number of parameters, the likelihood function is so fast to compute it doesn't make sense to run the smoother, since a lot more needs to be computed and saved then. After finding these things out, I lost interest in computing the exact score :)

I'll take your word for that.  The main observation I have is that when running the tests locally `MLEModel.loglike` is getting called 44888 times for a total of 113.880 seconds (about 22% of test runtime).  `fit` is called 135 times (74.7s) and `hessian` 990 times (87.9s).  The implicit assumption I'm working off of is that an analytic score will make a significant difference in cutting down those loglike calls and give a nice performance win.
