### ISSUE TITLE
dtype with large number of dummies

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3731]
Consider a use case where a few million rows and 5-10 exog variables, 2-3 of which are Categorical.  If there are 10-20 values for each of these Categories (states, countries, NAICS codes...), then after `pd.get_dummies` the full `exog` can start pushing up against memory constraints.

A reasonable response to this scenario is "don't do that thing you just said."  But dauntless, we persevere.

If a large fraction of the `exog` columns are dummies, then storing them as `np.float64` is pretty  wasteful.  Using `np.bool` or `np.uint8` could lighten the footprint quite a bit.  But splicing together arrays inside other steps is not a business I want to be in.  Could e.g. dask's chunk-based structure handle some of this?

**Comment by josef-pkt** [comment]
dtype will not help much because we still need to do higher precision computation.
e.g. float32 is currently not ruled out as dtype but not actively supported (and computation might switch th float64 semi/un-intentionally.

categoricals are inherently sparse, but if they are not of main interest, then they can be absorbed in a linear model. For GLM, and discrete it is more difficult and we need to splice the linear predictor between a dense and a sparse component (no plans yet, but there is a discussion somewhere).

issues #2568 #2710
PRs #2774, #2774

**Comment by jbrockmendel** [comment]
I'll take a look through the suggested links, thanks.
