### ISSUE TITLE
difference between VAR and VARMAX, interpretation of VAR results

### ISSUE THREAD

**Issue by tryfonch** [statsmodels/statsmodels#3825]
Suppose I have 5 endogenous variables (all are stationary) in a dataframe (it has 150 rows, 5 cols, datetimeIndex) with index of a date form and I want to model a VAR(2). If I use a VARMAX of order (2,0) and _None_ exogenous variables will I get the same results of coefficients and p-values as the VAR(2) model? 

I tried it but they were not the same. 

Also when I ran the VARMAX I got the following warning : ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals. Does it affect the VARMAX results? My maxiter argument in the fit function is set to 10000. How could I fix this?

Also what is the interpretation of the results in each model? In the VAR model I do not reject the coefficients with prob values more than, say, 0.05 whereas in the VARMAX model I do not reject the coefficients with P>|z| values less than, say, 0.05. Is that correct?

Here are the modules I imported
import statsmodels.api as sm
import statsmodels.tsa.api as smt

**Comment by ChadFulton** [comment]
VAR(2) and VARMAX(2, 0) are theoretically identical models, however in statsmodels the VAR(2) model is fit via conditional maximum likelihood (i.e. least squares) and the VARMAX(2, 0) model is fit via exact maximum likelihood.

You will generally not get the same coefficients, for two reasons:
(1) Conditional MLE is only *asymptotically* the same as exact MLE
(2) The maximum likelihood estimates in VARMAX are found numerically, and there may be difficulties finding the maximum and / or there may be numerical noise.

Convergence warnings in VARMAX are common, because vector autoregressions typically have poor identification for many of the parameters.

You're correct about the interpretation.

Unless you know you want VARMAX for some reason, it is more robust to stick with VAR.

**Comment by tryfonch** [comment]
@ChadFulton I have also a question regarding the lag parameter.  I use the .select_order(maxlags) to find the order of lag. I set the max lags to be a relatively big number e.g. 15. 
The result is the following: {'aic': 1, 'bic': 0, 'fpe': 1, 'hqic': 0}

However, after looking at the result summary, I can see that all my prob values of the coefficients are above 0.05 (I fit a VAR(2) model). This does not seem very intuitive. Given that all of the variable coefficients seem to be of significance isn't it contradicting to the .select_order result? I used a .diff() function to every column of my dataframe before applying the model in order to make it stationary (also checked them using the adf test and are indeed I(1)).

Thanks in advance!
