### ISSUE TITLE
AttributeError: module 'scipy.stats' has no attribute 'chisqprob'

### ISSUE THREAD

**Issue by srivathsadv** [statsmodels/statsmodels#3931]
Error:
c:\program files (x86)\python35-64\lib\site-packages\statsmodels\discrete\discrete_model.py in summary(self, yname, xname, title, alpha, yname_list)
   2756                 yname_list=None):
   2757         smry = super(BinaryResults, self).summary(yname, xname, title, alpha,
-> 2758                      yname_list)
   2759         fittedvalues = self.model.cdf(self.fittedvalues)
   2760         absprederror = np.abs(self.model.endog - fittedvalues)

c:\program files (x86)\python35-64\lib\site-packages\statsmodels\discrete\discrete_model.py in summary(self, yname, xname, title, alpha, yname_list)
   2548                      ('Log-Likelihood:', None),
   2549                      ('LL-Null:', ["%#8.5g" % self.llnull]),
-> 2550                      ('LLR p-value:', ["%#6.4g" % self.llr_pvalue])
   2551                      ]
   2552 

c:\program files (x86)\python35-64\lib\site-packages\statsmodels\tools\decorators.py in __get__(self, obj, type)
     95         if _cachedval is None:
     96             # Call the "fget" function
---> 97             _cachedval = self.fget(obj)
     98             # Set the attribute in obj
     99             # print("Setting %s in cache to %s" % (name, _cachedval))

c:\program files (x86)\python35-64\lib\site-packages\statsmodels\discrete\discrete_model.py in llr_pvalue(self)
   2403     @cache_readonly
   2404     def llr_pvalue(self):
-> 2405         return stats.chisqprob(self.llr, self.df_model)
   2406 
   2407     @cache_readonly

AttributeError: module 'scipy.stats' has no attribute 'chisqprob'

To reproduce the error:
Dataset information - http://www.statsmodels.org/dev/datasets/generated/ccard.html

Code:
```
df = sm.datasets.ccard.load_pandas().data
df['intercept'] = 1
df = df[['intercept', 'AGE', 'INCOME','OWNRENT']]
model = sm.Logit(df.OWNRENT, df[['intercept', 'AGE', 'INCOME']])
result = model.fit()
result.summary()
```

Issue:
File - statsmodels\discrete\discrete_model.py
Function - llr_pvalue(self)

This returns - stats.chisqprob(self.llr, self.df_model)
But the function stats.chisqprob is depricated as of statsmodel 1.7 (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chisqprob.html) and should be replaced with stats.distributions.chi2.sf

Ouput of sm.show_versions()
~~~~~~~~~~~~~~~~~~~~
INSTALLED VERSIONS
------------------
Python: 3.5.3.final.0

Statsmodels
===========

Installed: 0.8.0 (c:\program files (x86)\python35-64\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.13.1 (c:\program files (x86)\python35-64\lib\site-packages\numpy)
scipy: 1.0.0b1 (c:\program files (x86)\python35-64\lib\site-packages\scipy)
pandas: 0.20.3 (c:\program files (x86)\python35-64\lib\site-packages\pandas)
    dateutil: 2.6.1 (c:\program files (x86)\python35-64\lib\site-packages\dateutil)
patsy: 0.4.1 (c:\program files (x86)\python35-64\lib\site-packages\patsy

**Comment by josef-pkt** [comment]
Thanks for checking and reporting. I didn't know we still use those functions.
Based on a file search it is the only use of `chisqprob`, but there are a few more removed distribution function.

Note this is in DiscreteResults so it will cause errors in all discrete models, i.e all `summary` will be "dead".

@srivathsadv Did you run the statsmodels test suite with scipy 1.0 candidate? Are there other errors?

workaround is to assign the missing function to scipy.stats

```
>>> from scipy import stats
>>> stats.junk = lambda chisq, df: stats.chi2.sf(chisq, df)
>>> stats.junk(10, 3)
>>> 0.018566135463043251
>>> stats.chisqprob(10,3)
>>> 0.018566135463043251
```

**Comment by srivathsadv** [comment]
No, I did not run the statsmodels test suite. Just used the summary function of the discrete model.
Thanks for the workaround.

**Comment by VincentLa14** [comment]
Running into this issue myself now. Is there a way for me to run stuff before `0.9.0` comes out?

**Comment by Merry-Yundi** [comment]
Hello @avishaylivne is your problem fixed? 
I have had a similar problem with you but have no idea of it
![935144565](https://user-images.githubusercontent.com/28687848/34202238-1eedd484-e5b2-11e7-97ef-20cfa8c571cd.jpg)

**Comment by kennmyers** [comment]
I was still getting this error so I ran an environment with scipy 0.19.0 instead of 1.0.0 and it worked.

**Comment by Merry-Yundi** [comment]
Thank you I've got it. When using different environment, the problems just disappear.

**Comment by Will-So** [comment]
Seems to have been deprecated and removed in scipy. [source](https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.stats.chisqprob.html). [Alternative](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2.html). Will try to fix.

**Comment by NaderNazemi** [comment]
Was this fixed in scipy version 1.0.0 
I am still getting an error

**Comment by NaderNazemi** [comment]
Thank you for the workaround solution.

**Comment by mynamerahulkumar** [comment]
**results.summary2()** will work

Model: | Logit | No. Iterations: | 6.0000
-- | -- | -- | --
Dependent Variable: | converted | Pseudo R-squared: | 0.000
Date: | 2018-05-29 13:35 | AIC: | 215704.9004
No. Observations: | 294478 | BIC: | 215726.0864
Df Model: | 1 | Log-Likelihood: | -1.0785e+05
Df Residuals: | 294476 | LL-Null: | -1.0785e+05
Converged: | 1.0000 | Scale: | 1.0000

**Comment by Abraham-Leventhal** [comment]
@VincentLa14 

Warning: I am a total python noob. I am using sm version `0.8.0` and this is my output of sm.show_versions():

<details>
  <summary>Click to expand</summary>
 INSTALLED VERSIONS
------------------
Python: 3.6.4.final.0
OS: Darwin 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

Statsmodels
===========

Installed: 0.8.0 (/anaconda3/lib/python3.6/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.27.3 (/anaconda3/lib/python3.6/site-packages/Cython)
numpy: 1.14.0 (/anaconda3/lib/python3.6/site-packages/numpy)
scipy: 1.0.0 (/anaconda3/lib/python3.6/site-packages/scipy)
pandas: 0.22.0 (/anaconda3/lib/python3.6/site-packages/pandas)
    dateutil: 2.6.1 (/anaconda3/lib/python3.6/site-packages/dateutil)
patsy: 0.5.0 (/anaconda3/lib/python3.6/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 2.1.2 (/anaconda3/lib/python3.6/site-packages/matplotlib)
cvxopt: Not installed

Developer Tools
================

IPython: 6.2.1 (/anaconda3/lib/python3.6/site-packages/IPython)
    jinja2: 2.10 (/anaconda3/lib/python3.6/site-packages/jinja2)
sphinx: 1.6.6 (/anaconda3/lib/python3.6/site-packages/sphinx)
    pygments: 2.2.0 (/anaconda3/lib/python3.6/site-packages/pygments)
nose: 1.3.7 (/anaconda3/lib/python3.6/site-packages/nose)
virtualenv: Not installed
</details>

I ran into the `'scipy.stats' has no attribute 'chisqprob'` error when trying to create a summary of a multinomial logit model. Specifically, I used the mnlogit function as such:
```
model = statsmodels.formula.api.mnlogit(formula = (my formula), data = (my data)).fit()
model.summary()
```

After checking out this help page, I ran the code you suggested:
```
from scipy import stats
stats.chisqprob = lambda chisq, df: stats.chi2.sf(chisq, df)
```
in the cell that has the rest of my imports, then tried to do `model.summary()` again. 

Now, instead of getting an error, my summary contains tons of `nan`, as in, a `nan` for every coefficient, standard error, and t-stat in the summary. Also the summary outputs a `nan` for the pseudo r-squared, log-likelihood, etc. Worse, I seem unable to get my jupyter notebook to go back to the old (retrospectively comforting) chisqprob error! If I delete the code: 

```
from scipy import stats
stats.chisqprob = lambda chisq, df: stats.chi2.sf(chisq, df)
```
and run my model again, then try to print the summary, i get the same issue - tons of nan's. Literally any time I make an mnlogit model on any data, and I run the model and try to use the summary() method, I get `nan`. Even if i switch notebooks and never run the above stats.chisqprob code. 

What have I done? Help would be appreciated, and please let me know if this comment is missing crucial information. I'd love to know if I can undo this, and why on Earth this happened in the first place.

Thanks!

**Comment by kennmyers** [comment]
@Abraham-Leventhal things you should try:

1) Restarting the kernel and rerunning the code (if you just delete the code and rerun, the assignment of the lambda function to `stats.chisqprob` will still be stored in memory and that's why you're getting the same result. Doing this will probably replicate your original error though
2) Restart the kernel and try `summary2()` instead of `summary()`. `summary2()` seemed to be the fix a lot of us needed. 
3) If those fail, try downgrading you scipy version to 0.19.0

If the code runs after performing steps 2 and/or 3, and you're still seeing all of the NaNs, there is probably something wrong with your model and/or data.

**Comment by josef-pkt** [comment]
instead of downgrading scipy, it's better to upgrade statsmodels.
statsmodels 0.9 has the compatibility fixes

**Comment by Abraham-Leventhal** [comment]
@kennmyers , @josef-pkt 
Thanks for the prompt replies! 

I went and updated Anaconda and statsmodels (And some other packages that were automatically included) and ran into another problem when trying to run model.summary(). Now I again am looking at a summary full of `nan`, which may have to do with this error that appears in red above the cell output: 

/anaconda3/lib/python3.6/site-packages/statsmodels/discrete/discrete_model.py:2127: RuntimeWarning: overflow encountered in exp
  eXB = np.column_stack((np.ones(len(X)), np.exp(X)))
/anaconda3/lib/python3.6/site-packages/statsmodels/discrete/discrete_model.py:2128: RuntimeWarning: invalid value encountered in true_divide
  return eXB/eXB.sum(1)[:,None]
/anaconda3/lib/python3.6/site-packages/statsmodels/base/optimizer.py:271: RuntimeWarning: invalid value encountered in greater
  oldparams) > tol)):

Any help would be of great benefit, thanks!

**Comment by avibrazil** [comment]
You can also use `summary2()` to workaround:

```
model=smf.logit(thefunction, dataframe[selector]).fit()
model.summary2()
```
