### ISSUE TITLE
base.data.ModelData handles two unrelated tasks

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3932]
`base.data.ModelData` is instantiated with a `Model` and handles nulls.  Then we don't hear from it for a while, and post-estimation, it handles wrapping of outputs.  These responsibilities are unrelated and should be separated.

In particular, a `LabelWrapper` class or whatever would consist mainly of things we want to keep for a light-weight results-only object, while the `ModelData` class holds `_data_attr` objects that get stripped out.

**Comment by jbrockmendel** [comment]
Open to a PR that separates these tasks?

**Comment by josef-pkt** [comment]
No, I think that needs more thought.

The main link between the two tasks is that the output/return wrapper depends on the original data, so those two are related, e.g. pandas in - pandas out, with the same index if applicable.
If it ain't broken, then core refactoring gets low priority. Meaning, there are many things that can go wrong which requires a very large review effort. so the potential/expected benefit needs to be large.

e.g. I haven't reviewed #3203 yet because I would like to test it for smaller, e.g. stats, function first, but I haven't been in that area in a while.

The main problem is that this was Skipper's work and unless/until we get another maintainer familiar with this area, it takes me a lot of effort to figure out potential benefits and "damages" (i.e. things that might get broken). I'm willing to spend the time for specific needs or fixes but not for generic or abstract reasons. This is core code used by all models, so it will have a very wide impact, and is not safe to experiment with..
It's much easier with parts that I'm really familiar with because there I have much better guesses or expectations about the impact.

(aside: I'm getting a bit depressed by how many high priority topic weeks I can come up with when triaging or looking at issues and PRs, and stackoverflow questions and twitter comments. https://github.com/statsmodels/statsmodels/wiki/Topic-Weeks and I just started the page.)

**Comment by jbrockmendel** [comment]
I see two issues here: the Immediate Issue of the ModelData class, and the Larger Issue of the systematic roadblocks to addressing technical debt.  Starting with the former.

I don't expect "trust me, I've given it a lot of thought" to be a compelling argument, but I have given it a lot of thought.

> The main link between the two tasks is that the output/return wrapper depends on the original data

That is a _thematic_ link, not a link in the code's logic.  The methods/properties can be partitioned such that the resulting classes do not refer to each other.  Besides which names/labels are things we want to be able to hold on to separate from the underlying arrays (I think you opened an issue discussing something to the effect of `ResultsNoData`).

Moreover, splitting this into more narrowly focused classes will make them easier to grok, making this less of a problem next time work needs to be done in this area (which it will when we get to `MNLogit` Week)

> The main problem [...]

The larger issue is that you/we don't trust the tests.  If we're not confident in the tests for something this central, that's a massive red flag.  The question becomes: how do we robustify the tests to the point where we can confidently address technical debt?

This is a problem that only gets worse with time.  If contributors aren't allowed to improve these parts of the code, then you'll never have a reason to get familiar enough with it to break the cycle.

Consider the incentives this gives contributors; if I want a  Kaplan-Meier estimator, I'm better off implementing a new one rather than trying to improve/fix/finish something from `sandbox.km_class`,  `sandbox.survival`, `sandbox.survival2`.  Inevitably I'm going to implement just as much as much as I need and then add it to the pile.


OK enough about that for now.  To your last point about topic weeks: I'll volunteer for the MNLogit VAR, and cov_type weeks.

**Comment by josef-pkt** [comment]
I'm not convinced yet that you can separate the two. The (pandas) results wrapper needs to know that pandas was used as data type and needs to have that information. So, the two parts have to be connected.

However, the main point is that I don't trust or we cannot trust our unit tests. As example, we added pandas returns directly to predict. But, IIRC we needed 3 follow up bugfixes to handle cases that were not considered in the initial merge. Our unit tests are pretty good in verifying numbers, and that's where the emphasis is. pandas integration, other data handling, API issue and dtypes of inputs have very incomplete test coverage.
(Actually just for pandas it might not be so bad anymore, we have many test cases across the models, sothe test coverage might be **ok**. However, one special case MNLogit + pandas + formulas was never checked for pickling https://github.com/statsmodels/statsmodels/issues/3958#issuecomment-333548284 )

I'm not saying our code could not be improved by refactoring, there are several cases where I have through several classes until I find the method that actually does the thing that I'm looking for in a specific case. 
But I'm risk averse (on behalf of the users and our repuration) and need to allocate my time and patience. In contrast, refactoring and adding to more isolated models or parts is a lot easier, both because it is easier to figure out what the likely impact is and because possible problems are more localized.

Experimenting with designs is also easier in other localized cases. I assume ResultsNoData and ModelFromSummaryStats will come initially as separate classes and full integration with the generic code will only come once we see how it works and how large the required changes are. Right now my plans/specs are too vague in the details to start with splitting up our base model into reusable parts or mixins, because I only have a vague idea what would need to be in the separate parts., 

> To your last point about topic weeks: I'll volunteer for the MNLogit VAR, and cov_type weeks.

Thanks, given our recent discussion and recent issues, MNLogit will be the highest on my list for 0.10

**Comment by jbrockmendel** [comment]
> I'm not convinced yet that you can separate the two. The (pandas) results wrapper needs to know that pandas was used as data type and needs to have that information. So, the two parts have to be connected.

I'm open to the possibility that I've over-estimated the separability.  Non-degenerate priors and all.

> However, the main point is that I don't trust or we cannot trust our unit tests. 

This seems like the main point on which we agree.  Rather than go in circles, let's figure out what it will take to change this.  Brainstorming:

- Version of coverage statistics that exclude smoke tests so we have a better idea what the tests actually cover (#3893)
- Topic Week for `base` to at least identify a subset of the code that _is_ reliable, then we can incrementally work on expanding that.
- Less code --> Less to reason about (#3796, #3714, #3442, this could become a list unto itself)
- Improve consistency/predictability of what attributes exist (and where they are set) (#3920, #3890, #3889, #3840, #3787, #3689)
- Code quality tools (#3771)
- (Somehow) get coverage information for cython modules.
- Get AR/ARIMA/VAR/... models to conform to the standard class hierarchy (i.e. fewer special cases)

In the interim, I'm going to go back to pushing small fixups that improve standardization (e.g. #3970), focusing on my long-time hangup of df_model&df_resid.

**Comment by josef-pkt** [comment]
part of it requires writing more unit tests, to make bugs during refactoring less likely

e.g. pandas integration and formulas:
It has improved over time, but there are still models or model types and results that don't have unit test coverage when pandas or pandas + formulas are used. Verifying the number often relies on numpy examples. Whether some Series returned by a results instance have correct indices relies on correctness of the wrapper, but AFAIK is not tested. Those cases might break in non-standard models, e.g. the MNLogit results conf_int. 
Similar correctness of parameter names in results are not tested, AFAIK.  
Most likely we also have some cases where a univariate endog or extra data keyword works with a pandas Series but breaks with a (2-D) DataFrame.

Related to smoke tests: The main two problems and large tasks are to add proper unit tests for the summary() and for the plots/graphics. Each of those is a lot of work, and I never got beyond a few trial cases and experiments.

Many of these API issues are not much tested. However, they are much easier for users to find and the problems are "obvious" as problems. While the main purpose of the unit tests is to prevent that we **silently** return wrong numbers because of bugs, or, at least, make that very unlikely.

One possibility for some of these required unit tests is to use more generic unit tests.
Currently there are two cases handled in the `base` tests which I wrote for generic pickling/remove_data support and for the Wald based inference (excludes tsa and excludes MNLogit, AFAIR).
`tsa` has additional tasks or problems with datetime indices. I have no idea how good the test coverage is in there. Based on the number of open issues, we don't have enough.

**Comment by josef-pkt** [comment]
just one detail that I just saw while investigating an issue #2727

outlier_test after OLS uses

```
if labels is None:
        labels = getattr(model_results.model.data, 'row_labels', None)
```

the `model.data` instance currently holds our internal API to access information about the original data (as provided to the model) 
(except for extra data like weights or offset which don't go through the data handling except for missing value treatment)

**Comment by jbrockmendel** [comment]
> the model.data instance currently holds our internal API to access information about the original data 

I was coincidentally just looking at something similar.  Ideally the `model.data` attribute should be semi-internal, referenced in as few places as possible.  Two easy wins on that front would be to have model inherit `data.row_labels`, and for `tsa_model` to inherit `data.dates`.
