### ISSUE TITLE
BUG/MAINT: update setup.py

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3977]
setup.py still shows python 2.6 support

version number of statsmodels master should be 0.9

check minimum version of requirements to conform with travis test environment.

**Comment by jbrockmendel** [comment]
I'm tinkering with setup.py now in order to try to get a proof-of-concept for cython-coverage working.  A lot of stuff in this file (and in tools/cythonize.py) looks pretty ancient.  The coverage build is tentatively working, but I'd be a lot more confident in it if we could bring the setup/cythonize files into the 21st century.

In particular, I think a lot of the cython caching/tempita stuff is now handled internally by cython.

**Comment by bashtage** [comment]
@josef-pkt This probably can be closed now. There are newer PRs that address this issue, and I think it was corrected for 0.9.
