### ISSUE TITLE
Unicode/TeX in docstrings

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3993]
Going through addressing flake8 complaints, one of the harder ones to fix is "E501 line too long" when the line is a TeX expression in a docstring.

I doubt this is supported, but it would be neat if we could substitute in e.g. `u'α'` for `'\\alpha'` in some of these cases.

**Comment by jbrockmendel** [comment]
Doesn't really merit an issue.

**Comment by jbrockmendel** [comment]
Really small question about docstrings:

In a handful of places `math::` (i.e. TeX) blocks have long lines wrapped by ending lines with `\\`.  In other places (not as many of these, e.g. `GeneralizedPoisson.loglikeobs`) long lines are wrapped without the `\\`.  And in most cases, the lines just go un-wrapped.

What is the convention for wrapping these lines in rst?

**Comment by josef-pkt** [comment]
First no greek letters or unicode in code outside of proper names. I think Julia is silly with this, first I don't know how to pronounce any except the most common greek letters, and then often it is not clear what key combination will create that letter. (*)

About the Latex/math
AFAIK, we don't have much of a convention. We break line length if necessary or if it improves readability to just go a little bit over the limit.
The main criterion for docstrings is whether it's valid rst and valid Latex in math and renders properly in the sphinx generated docs, and then whether the rendered math in docstrings "looks good".
(Very often I need to check the rendered docs because I don't remember the rst or Latex rules and syntax.)
Isn't `\\` the Latex line break? or is it the continuation symbol?
e.g. the rendered GeneralizedPoisson.loglike formula is in one line and looks pretty good, but could possibly be split up into a multiline math formula because the expression is a bit long for one rendered line.

maybe not directly related: In general, multi-line string continuation in code is currently without convention. 
I (personally) don't like silent string concatenation, so most of the time I don't use the python feature of concatenating strings that are on consecutive lines.

(*) When I was younger, I only used Scientific Workplace for Latex. But that was just a nice GUI, the underlying "source" was still plain Latex in ASCII or whatever format.

**Comment by jbrockmendel** [comment]
Question answered, thanks
