### ISSUE TITLE
ARIMA problem

### ISSUE THREAD

**Issue by DeepWolf90** [statsmodels/statsmodels#4047]
I'm using ARIMA to predict time series data, and i use grid search with AIC to find the best combination of ARIMA parameters (p,d,q) and it give me (12,2,1), but when i start to fit, it give me the following error message:
 ValueError: The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.

**Comment by josef-pkt** [comment]
Can you provide an example to investigate and use for unit tests?

Two possibilities

- ARIMA start_params search is still not very robust, and there might be problems there
- misspecified model: maybe using differencing order = 2, overdifferences. Often not finding stationary or invertible start_params means that the specification doesn't agree with the data.

How did you manage to get the estimate in the grid search?
If you have good start_params from the grid search or the estimate of a similar, then you can provide those start_params in fit, and see whether the optimization converges. If you get a converged estimate that looks reasonable, then our start_params search might need improvement for this case.

BTW: I don't know if d=2 is fully supported.

**Comment by DeepWolf90** [comment]
This the notebook file
[ARIMA_CPI.zip](https://github.com/statsmodels/statsmodels/files/1398903/ARIMA_CPI.zip)

**Comment by josef-pkt** [comment]
just an observation: Running the final forecast loop over test data uses 50% CPU in quad-core with 8 virtual processors, on Windows with MKL

problem is with start_params in the shorter train dataset. If I use the full sample params as start_params, and recursively the previous params in the loop, then results finish, with one convergence warning

here is an updated notebook https://gist.github.com/josef-pkt/2cf5ff292b1a25d7c632b0280e3d401b
I didn't rerun everything because it's too slow
in cell 14 I assign `model_fit0 = model_fit` to keep the full sample results available
in cell 27 I add start_params, and I needed to adjust predict start and train sample length, because diff=2 doesn't seem to be fully supported or needs adjustment in user code for the extra missing initial observation.

BTW: using previous estimate as start_params should speed up estimation inside the test loop

I'm not sure what the insample prediction in the final plot is. I was mainly fixing start_params and didn't really read or check the details of the code.

**Comment by josef-pkt** [comment]
This looks like a good example and test case to improve some parts there, but for 0.10 because it would take too much time for 0.9.

As possible recommendation: Given that the lag search and the acf indicate a one year seasonal effect it might be useful to switch to SARIMAX, because then the seasonal lags can be specified without having to estimate also all the intermediate lags.

**Comment by DeepWolf90** [comment]
So, the problem is in start_params. I need to set the start_params as the previous estimate.
NOTE: why, it gives very bad prediction, although i'm using the suggested parameters.
should i go back and perform another grid search.
Thank you very much for your help, and i'm really looking forward for 0.9 and 0.10.

**Comment by josef-pkt** [comment]
I just remembered but cannot check quickly because I shut down the notebooks.

`predict` in ARIMA has a `typ` keyword. This needs to be set to `typ='level'` otherwise the prediction is in terms of the differenced process. With 'level' the prediction is in terms of the original level, i.e. integrated to compensate for the differencing.
http://www.statsmodels.org/dev/generated/statsmodels.tsa.arima_model.ARIMAResults.predict.html
If level doesn't work correctly, then there might be problems with the initial observation in the double differenced case. AFAIR, I never checked the second order differencing case.

According to the docstring `forecast` is always in levels.

**Comment by DeepWolf90** [comment]
i actually noticed that, typ ="level", but still not very good forecasting. i will try with single differenced d = 1.
thank you again, really appreciated.

**Comment by josef-pkt** [comment]
I'd like to keep this open for now. I don't have time to check the details now, but both start_params and diff order=2 need another look and improvements if possibly or if buggy.

**Comment by DeepWolf90** [comment]
Can i use the results i get from the ARIMA model in a paper. Like i said before, i'm comparing its performance with another neural network model. i'm not confident of the ARIMA model, cause you said the start_params search is still not very robust. What do you think, should i publish the paper.

**Comment by josef-pkt** [comment]
If the model converges, then the estimate should be fine.
However, if the model is very misspecified compared to the data, e.g. estimate an ARMA (without trend) in a non-stationary or trending case, then it is often possible that the model does not converge, which is an indication of model misspecification and not of numerical problems.

What I would do if the model doesn't find start_params or doesn't converge is to also try very simple start_params e.g. with all lag parameters set to zero, (and e.g. only the mean at non-zero).

Also non-convergence rates are often reported for Monte Carlo studies, i.e. the fraction of simulations where the model did not converge or broke down for other reasons. That might be misleading if non-convergence happens because of numerical problems or start_params problems in the statsmodels implementation. But using a reasonably specified model and trying a second set of start_params should keep this rate very low, I would expect. 

(Also reporting outlier robust performance measures, like median absolute prediction error or similar,  has less distortion in the result if those would be dominated by a small fraction of very bad cases when using averages.)

**Comment by DeepWolf90** [comment]
Thank you for your help....

**Comment by bashtage** [comment]
Closing as won't fix. THe legacy ARIMA is deprecated. Use statsmodels.tsa.arima.model.ARIMA instead.
