### ISSUE TITLE
Not Nearly Enough

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4063]
Team, we have a problem.

It's hard for me to say this since we've all put so much effort into this, but we've reached a breaking point.

We don't have _nearly_ enough modules named "tools".

Now granted, people have made some tremendous efforts in this area.  I'm really impressed by how various modules within `tsa` import [tsa.stattools as tsa](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/tests/test_tsa_tools.py#L13), or [tsa.tsatools as tools](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/tests/test_tsa_tools.py#L14), or [tsa.tsatools as tsa](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/vector_ar/irf.py#L17).  The new title-holder of course is [vecm](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/vector_ar/vecm.py#L623):

```
    import statsmodels.tsa.tsatools as tsat
    mlag = tsat.lagmat
```

Honorable mentions to the spice of life: `stattools as tsast`, `stattools as stt`, and `stattools as tss`.

Our ancient forefathers led the way with their towering works: `sm.tools`, `sm.tools.tools`, `sm.stats`, and `sm.stats.stattools`.  We can't just let that legacy go to waste.  We need to do _more_.  Brainstorming:

- `sm.stats.tools`
- `import scipy.stats as tools`
- `sm.tools.statstools`
- `sm.tsa.tools`
- `sm.tools.tsastats`
- `sm.util`
- `sm.utils`
- `sm.stats.toolstools`

**Comment by bashtage** [comment]
What about `sm.tools.tools.tools.tools.tools.tools`?

**Comment by bashtage** [comment]
Related, variable naming (and module naming, which are just variables in some dict somewhere) is hard. 

http://hilton.org.uk/blog/why-naming-things-is-hard

**Comment by josef-pkt** [comment]
"If all you have is a hammer, then ..."
"If you have 15 tool boxes, then you need to think what to put into your tool belt."

"Hey, give me that thingie that has two handles, looks a bit like scissors but can cut wires, and I think it is in the light blue toolbox."
"There are three of those, which one do you want?"

In almost every enhancement PR I have to think and worry about names for hours or for days.

https://groups.google.com/d/msg/pystatsmodels/yGIAfz2ofDk/BHfxPJ8A4cgJ
https://github.com/statsmodels/statsmodels/pull/3763#issuecomment-318852450

Module names are tough because we don't want to rename them after they are established both because of github's lack of history and because of backwards compatibility.

We have generic tools and tools.tools, and we have subpackage/folder specific tools. Similarly large subpackages can have their own `base` modules

shortcut aliases are not standardized and we don't have a convention for them.

The other related design problem is where to put things that don't have an obvious location, e.g. do we put all robust thingies in statsmodels.robust, or do we add `robust` modules to the main subfolders, stats.robust or robust.stats or do we put the outlier robust version together with the non-robust versions, stats.correlation.cov_mve?

(One advantage that we have is that the import paths for users don't have to be the same as the actual module or file paths.)

Everyone is invited to join the naming game! The rules of the game are less restrictive before a merge or release.

**Comment by jbrockmendel** [comment]
How unthinkably Anglo-centric are we?  Since we're transitioning to py3-only before long anyway, let's try to be a little bit multi-cultural here:

- sm.stats.toøls
- sm.tools.ståttools
- import ast as tsa

Snark aside:
1) The tsa examples mentioned above are pretty egregious, should be fixed.
2) Personally I like gerunds for module names "optimizing, testing, fitting, logging..." because they are unlikely to overlap with class/instance noun-like names.

**Comment by bashtage** [comment]
The cycle is complete ;)

**Comment by thequackdaddy** [comment]
> The cycle is complete ;)

I keep worrying statsmodels is going to show up on http://reddit.com/r/subredditdrama
