### ISSUE TITLE
pvalues tests in test_discrete

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4082]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/discrete/tests/test_discrete.py#L77

`def pvalues` instead of `def test_pvalues`.  This test isn't getting run.  When changed, a bunch of NegativeBinomial tests fail.

**Comment by josef-pkt** [comment]
The test failures in negative binomial seems to come from not overriding the test_pvalues
e.g. in several NB test classes pvalues are tested in `test_zstat`

CheckModelResults.test_pvalues would need lower precision for some NegBin, but there are also several shape mismatches in the test failure, I guess the extra dispersion parameter is not always included.

Also, some NegBin tests have comment in test_zstat `# Low precision because Z vs. t`
but this should be standardized, we should also be using normal distribution by default. Needs checking.

**Comment by josef-pkt** [comment]
I put milestone 0.10, because the results still look good. i.e. precision is still ok even if it's lower in Negbin than others.
