### ISSUE TITLE
test_sandwich_cov questions

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4088]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/discrete/tests/test_sandwich_cov.py#L281

```
    def setup_class(cls):
        cls.res2 = results_st.results_poisson_clu
        mod = smd.Poisson(endog, exog)
        mod = GLM(endog, exog, family=families.Poisson())
```

Is the first `mod` supposed to be used?  Or possibly a copy/paste leftover?

Second, there are a whole bunch of blocks in `setup_class` methods of the form

```
        cls.bse_rob = cls.res1.bse
        nobs, k_vars = mod.exog.shape
        corr_fact = (nobs) / float(nobs - 1.)
        # for bse we need sqrt of correction factor
        cls.corr_fact = np.sqrt(1./corr_fact)
```

But in this last line some of them have `np.sqrt(1./corr_fact)` and others have `np.sqrt(corr_fact)`.  Whats the reasoning for when to use which?

**Comment by jbrockmendel** [comment]
It looks like the `1/corr_fact` is used iff `cov_type='HC1'`

**Comment by josef-pkt** [comment]
> Is the first mod supposed to be used? Or possibly a copy/paste leftover?

most likely copy-paste leftover, or because I was checking that both have the same correct results.
In either cased unused, redundant and can be deleted

to corr_fact versus 1/corr_fact

In general there is no systematic meaning to it. In some cases it might have a specific meaning, but most likely whatever I "felt" like using in a specific case, i.e. in some cases it is compensating for a "known" documented correction factor, in other cases it is mainly the numerical compensation from reverse engineering the Stata results

**Comment by jbrockmendel** [comment]
> most likely whatever I "felt" like using in a specific case  [...] in other cases it is mainly the numerical compensation from reverse engineering the Stata results

That's ... not reassuring.  This sounds like the sort of thing that should be A Problem.  Am I misunderstanding?

> In either cased unused, redundant and can be deleted

I'll hold off on that for now, will hold out hope that the pace of merging trivial PRs will pick up after the next release (or the [teamwork](https://github.com/statsmodels/statsmodels/issues/4071) idea will catch on).

**Comment by josef-pkt** [comment]
> That's ... not reassuring. This sounds like the sort of thing that should be A Problem. 

It's just a local variable in a unit test, and it doesn't matter whether we start out with a/b or b/a. But in some cases one or the other makes more local sense.
The corr_factor itself are necessary because we intentionally don't follow Stata's definitions or inconsistencies, and we no hard information that Stata's definition is better.

(Aside: How I "feel" about code has been trained for many years, even though it's sometimes "not important enough to worry about it" or "too time consuming to come up with a better solution for now" or "no strong feeling about which of the similar or equivalent solutions will have better trade-offs in the long run".)
