### ISSUE TITLE
Extracting table of calculated factors

### ISSUE THREAD

**Issue by Tych0n** [statsmodels/statsmodels#4147]
Hello! Thank you for excellent tool.

Is there any way to extract table of calculated factors per observation from fitted model? Say, I have 'ar.L1' factor - how i can check what value it takes at each timestamp of my training dataset? I have checked http://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.mlemodel.MLEResults.html?highlight=mleresults and not found clear reference to my need.

Thank in advance!

**Comment by josef-pkt** [comment]
Do you mean the contribution of each part in the one step ahead prediction equation?
e.g. in OLS it would just be elementwise product  `results.model.exog * results.params`.

I don't know how to get that information out of the statespace representation. I don't think there is a ready way for it.
@ChadFulton ?

**Comment by ChadFulton** [comment]
Sorry, but I'm not sure quite what you're looking for - do you have a reference for this?

Is your model an AR(1)? Or are you running a Dynamic Factor model? Or something else?

**Comment by Tych0n** [comment]
@josef-pkt @ChadFulton actually i'm trying to select statistically viable exogen variables from [this](https://pastebin.com/g8wG00A0) model. I planned to take a set of calculated factors and to put them into smthng like stepwise regression in order to not manually iterate through them to get best set for my model.

**Comment by josef-pkt** [comment]
I just remembered: This sounds like what Hannan-Rissanen was intended for in the old times, i.e. faster specification searches than computing the full MLE for each specification

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/arima_model.py#L449
first compute an artificial AR with many lags (there are open issues about how many), then compute residuals, then create lag matrices and add them to an OLS model

```
                lag_endog = lagmat(endog, p, 'both')[endog_start:]
                lag_resid = lagmat(resid, q, 'both')[resid_start:]
                # stack ar lags and resids
                X = np.column_stack((lag_endog, lag_resid))
                coefs = GLS(endog[max(p_tmp + q, p):], X).fit().params
```

used in ARIMA only to compute start_params

Also, our ARIMA/SARIMAX implementation are for linear model plus arma residuals. So variable selection of the exog based on OLS could precede lag selection and estimation of a full ARMAX model.

**Comment by Tych0n** [comment]
@josef-pkt correct me please if i am mistaken - in this package arma is calculated separately from exogen factors, which are added after. Because of that i can firstly select exogen factors using some algorithm, and then just add resulting set to arma? Sorry, i don't understand what is meant by your code snippet - you wanted to tell that i can get calculated lags reproducing those steps, or it is just an explanation of how this package works?

**Comment by josef-pkt** [comment]
Yes to the first. OLS can consistently (*) estimate the parameter for the exogenous variables, so first doing separate variable selection should work.  
(*) parameter estimates converge to true parameter values as sample size increases.
(There are some assumptions if lagged values show up in `exog` for consistency to hold. I don't remember the details but it requires a stronger definition of "exogenous" in the ARMAX case.)
(The standard errors for the parameters in OLS will not be correct in this case because of the serially correlated residuals and we would need to use `cov_type='HAC'` or similar autocorrelation robust standard errors if those are needed.)

To the second: 
We use Hannan-Rissanen internally for the start_params, but it could be used more generally for specification searches. The code snippet and the ARIMA method compute an approximate solution to the ARMA model, specifically it creates an approximate estimate of the residuals and the corresponding lag matrices. This could be extracted and used separately from the ARIMA model. It's only an approximate solution and the model should still be fit by a full ARIMA/SARIMAX model, but some references mentioned its use for fast specification searches. 
I never tried it myself except for the start_params use that we have internally.

**Comment by ChadFulton** [comment]
> i'm trying to select statistically viable exogen variables along with ar&ma ones from sarimax model with params=(35,1,5)(0,0,0)0 and output. I planned to take a set of calculated factors and to put them into smthng like stepwise regression in order to not manually iterate through excluding\adding them to get best set for my model.

I guess you're thinking of a conditional MLE type of approach where you can estimate the AR parameters by regression on lags of the left hand side variable. The first issue is that you can't do the same kind of thing with MA terms (except for maybe the Hannan-Rissanen approach (which I don't know too much about), as Josef mentions, but see my note below about integration).

If you just had a pure AR or ARI model (integration is okay here), what you'd be after is the filtered (or smoothed, they're pretty similar in this case) estimates of specific state variables (where "state" refers to the state space formulation of the model). But with MA terms, the state variables don't coincide directly with something that I would think of as an "ar.L1" factor.

In this case, I think your best bet is to actually run the full model each time.

> Yes to the first. OLS can consistently () estimate the parameter for the exogenous variables, so first doing separate variable selection should work.

I don't know if this is still true in this case, with the error term integrated?

**Comment by Tych0n** [comment]
@josef-pkt got it after reading a bit about Hannan-Rissanen method. @ChadFulton correct me if i'm wrong - MA terms aren't pre-calculated. They are calculated recursevly until MLE converges and their values are valid only for specific model fitted state?

**Comment by josef-pkt** [comment]
> Yes to the first. OLS can consistently () estimate the parameter for the exogenous variables, so first doing separate variable selection should work.

>I don't know if this is still true in this case, with the error term integrated?

Maybe I have to take this back, I never looked at the integrated ARIMAX case (with I and X). I don't even know how it's defined in statsmodels. Are we differencing the residuals from the linear model of y on x or difference y?
The problem is that if y = x b + u and u ~ ARIMA(p, 1, q), then y needs to be integrated (unless x and u are cointegrated). So, something sounds strange to me in that case.

**Comment by Tych0n** [comment]
Ok guys, thak you for your support! I don't want bother you with such specific question anymore as i have walked another route and managed to do my job.
