### ISSUE TITLE
results.save(remove_data=True) modifies its argument

### ISSUE THREAD

**Issue by frexvahi** [statsmodels/statsmodels#4201]
```python
> model = sm.OLS(endog, exog)
> results = model.fit()
> results.save('results.pickle', remove_data=True)
> results.summary()
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```
I was expecting `results.save(remove_data=True)` to remove the data from the [object written to the] pickle, not from the results object itself.

i.e. something like:
```python
def save(self, path, remove_data=False):
    if remove_data:
        other = shallow_copy(self)
        other.remove_data()
        other.save(path, remove_data=False)
        return
    ...
    # Code to do the saving
```

**Comment by josef-pkt** [comment]
It's inplace modification by design.

We have currently no tested way to make a copy of model/results instances and I don't know if shallow_copy would do the correct thing. The main thing to check is that mutable objects attached to results and model instances don't get modified in the original when the copy is modified. My guess is that this will be difficult to do and check.

**Comment by frexvahi** [comment]
I had a look at the implementation, fair enough, this is more difficult than it would appear from superficial inspection.
