### ISSUE TITLE
Cant import statsmodels.tsa.arima_model, docstring is None

### ISSUE THREAD

**Issue by nzahasan** [statsmodels/statsmodels#4242]
I am unable to import statsmodels.tsa.arima_model it always spits out this error

```
Traceback (most recent call last):
  File "/home/nazmul/WorkDir/ECORR/ARIMA.py", line 3, in <module>
    from statsmodels.tsa.arima_model import ARIMA
  File "/home/nazmul/WorkDir/ECORR/statsmodels/tsa/arima_model.py", line 30, in <module>
    from statsmodels.tsa.ar_model import AR
  File "/home/nazmul/WorkDir/ECORR/statsmodels/tsa/ar_model.py", line 601, in <module>
    class ARResults(tsbase.TimeSeriesModelResults):
  File "/home/nazmul/WorkDir/ECORR/statsmodels/tsa/ar_model.py", line 804, in ARResults
    preddoc = AR.predict.__doc__.split('\n')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by josef-pkt** [comment]
How did you install statsmodels?

For example -OO removes docstrings, which I guess we don't support because of the programmatic docstring generation in many places.

**Comment by nzahasan** [comment]
thorugh pip3 in ubuntu 16.04

**Comment by josef-pkt** [comment]
check what `AR.predict.__doc__` is, and if it is None, check the source whether the AR.predict method still has the docstring.

e.g. I get
```
>>> print(AR.predict.__doc__)

        Returns in-sample and out-of-sample prediction.

        Parameters
```

**Comment by josef-pkt** [comment]
Checking the source might not help much.

I guess there would by `.pyo` files in the installed `statsmodels\tsa\__pycache__`. Check if you have .pyo files or only .pyc files in there.

**Comment by nzahasan** [comment]
removed the pyo files and its working now! @josef-pkt  thanks.

**Comment by josef-pkt** [comment]
cross-link to a previous discussion #1167, with possible workarounds. Deleting pyo files seems to be a reasonable solution to me.

I'm keeping this open as a FAQ issue in case it shows up again.

**Comment by nzahasan** [comment]
@josef-pkt  added a try/except statement in `tsa/ar_model.py` @ line 81 in case this issue dosent occur in future.

**Comment by josef-pkt** [comment]
@nzahasan   Was this the only problem you had with the optimized away docstrings or are there more?

We use generated or templated docstring now in many places, and I never tried to figure out how much we would have to change to make `-oo` work.
(My guess is still that there at most marginal benefits to `-oo`.)

**Comment by nzahasan** [comment]
@josef-pkt so far I have noticed the problem only for tsa.

**Comment by Lunde89** [comment]
the problem also goes for other sub-modules. I haven't been able to find any .pyo files to erase, so the problem persists. Can somebody please explain what the "-oo" means" If i just install Python for windows, i don't seem to have any option to choose -oo or -o?

**Comment by josef-pkt** [comment]
Looks like pyo files are not used anymore in python >= 3.5
https://www.python.org/dev/peps/pep-0488/

description of `-o` and `-oo` options is on this page
https://docs.python.org/3/using/cmdline.html

As workaround
You can delete the content of the `__pycache__` directory in the relevant directories of statsmodels, which will delete the pyc files.
(I didn't read pep 488, pyc with optimization seem to have a postfix in the filename.

When pyc files are missing, then they should be recreated at the next run of the modules, But I don't know if there is a setting that it would recreate `-oo` pyc files. (if yes, then they can explicitly be recreated without any `-o`)

(Aside: Do not delete any `.pyd` files because those contain the binary extensions. Just in case they have been moved around. At least up to python 3.4 they are in the source folders.)

I still have no idea why `-oo` is used and by which install program this is done.
