### ISSUE TITLE
DOC/BUG: `py_hamilton_filter` doesn't handle time-dependent transition probabilities the same as `cy_hamilton_filter`.

### ISSUE THREAD

**Issue by gbrunick** [statsmodels/statsmodels#4248]
The documentation for statsmodels.tsa.regime_switching.markov_switching.py_hamilton_filter suggests that it can handle time-dependent transition probabilities, but the following script fails when I run it.

`
import sys
import numpy as np
import statsmodels
import statsmodels.tsa.regime_switching.markov_switching as ms

print "Python version:", sys.version
print "Numpy version:", np.version.full_version
print "statsmodels version:", statsmodels.version.full_version

np.random.seed(10)
k_regimes = 2
nobs = 4
order = 1

_initial_probabilities = np.arange(1, k_regimes + 1, dtype='float64')
initial_probabilities = _initial_probabilities / np.sum(_initial_probabilities)

_regime_transition = np.random.exponential(size=(k_regimes, k_regimes, nobs))
regime_transition = _regime_transition / np.sum(_regime_transition, axis=0)

conditional_likelihoods_shape = (1 + order) * (k_regimes,) + (nobs,)
conditional_likelihoods = np.random.exponential(size=conditional_likelihoods_shape)

res1 = ms.cy_hamilton_filter(initial_probabilities, regime_transition, conditional_likelihoods)
res2 = ms.py_hamilton_filter(initial_probabilities, regime_transition, conditional_likelihoods)
`

Result on my machine:

C:\Data\python\venv\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Numpy version: 1.13.3
statsmodels version: 0.8.0
Traceback (most recent call last):
  File "temp/example.py", line 26, in <module>
    res2 = ms.py_hamilton_filter(initial_probabilities, regime_transition, conditional_likelihoods)
  File "C:\Data\python\venv\lib\site-packages\statsmodels\tsa\regime_switching\markov_switching.py", line 198, in py_hamilton_filter
    regime_transition[..., transition_t] *
IndexError: index 3 is out of bounds for axis 2 with size 3

This may just be a documentation bug, as it looks like `regime_transition` needs to be longer than `nobs`, but then it seems like the cython version should also fail above.

**Comment by ChadFulton** [comment]
Thanks for the report!

In this case there are two things going on:

First, the documentation is incorrect on `py_hamilton_filter` and `cy_hamilton_filter`. The `conditional_likelihoods` array should have last dimension `nobs - order` rather than `nobs`. This is because if `order >= 1`, then you can't compute conditional likelihoods for first `order` periods.

So if you modify your example so that:

```
conditional_likelihoods_shape = (1 + order) * (k_regimes,) + (nobs-order,)
```

then it will work.

The second thing going on here is that, to maximize the speed of the Cython code, we have used the option `boundscheck=False`. This means that Cython will essentially never raise an `IndexError`, but if you pass arrays with the wrong sizes then the results will likely be wrong and maybe a memory error could happen if Cython is trying to access memory it shouldn't. Of course if we use this option, we should have the correct array sizes in the documentation :)

**Comment by gbrunick** [comment]
Makes sense.

I could probably throw together a pull request that updates the docstrings and does some validation on the dimensions of the inputs for both functions.  Would that be useful?  Does that require any paperwork?  I don't see anything about paperwork here http://www.statsmodels.org/stable/dev/index.html.  This would be a pretty trivial improvement, so its may not be worth it if the pain of code review and/or paperwork outweighs the benefits.

Thanks for prompt response.

**Comment by ChadFulton** [comment]
A PR would be great! No paperwork required. Thanks again!

**Comment by gbrunick** [comment]
Finally circled back to this.  PR is #4280.
