### ISSUE TITLE
Cointegration test between series with nan values

### ISSUE THREAD

**Issue by tcloaa** [statsmodels/statsmodels#4281]
Hi,

I saw a TODO for `def coint`:
```python
    TODO: We could handle gaps in data by dropping rows with nans in the
    auxiliary regressions. Not implemented yet, currently assumes no nans
    and no gaps in time series.
```

May I ask that, how can I test cointegration for 2 series (may have nan value independently)?

It should be similar to something like `corr()` from `pandas` with compute pairwise correlation of columns, excluding NA/null values.

Thanks,

**Comment by josef-pkt** [comment]
`corr` or similar will not help because we need an auxiliary OLS regression. Once we have the setup for those OLS regressions, we could drop rows with nans in them. 
That was the idea, although I don't have any direct references for it. Note this will drop rows for an observations if it or any observation within maxlag (or actual number of lags ?) is nan.

One alternative would be to impute values, but that would distort the results if there are more than a tiny or small fraction of observations that are nan.

**Comment by bashtage** [comment]
If two series are cointegrated and have missing values at random, you can simply test the subset that are not missing. If the original series are CI, the subsets are also CI.
