### ISSUE TITLE
iolib tests are... special

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4317]
- The entirety of iolib.tests.test_summary is in its `__name__ == '__main__'` block, and it doesn't contain any assertions.

- Not really sure what to make of iolib.tests test_summary_old.  Is it an old test for the current summary or an up-to-date test for something deprecated?

- Does iolib/notes_table_update.txt need to exist?
- is iolib.stats_summary_examples in the right place?
- iolib.table's docstring has a section "Potential problems for Python 3" that suggests it is written with py2.5 support in mind.  It could use a fresh coat of paint.

**Comment by josef-pkt** [comment]
(I just found an open browser tab with this month old comment that I never posted.)

iolib.table  was taken from econpy where it was initially maintained.
notes_table_update.txt were the notes for the naming and formatting changes when we copied a new version of the original table code. There haven't been changes in a long time, and I haven't looked at the original table code in a long time.

Some of the rest are workarounds or partial attempts to check the content of the summary. Almost all summary() tests in the various modules are only smoke tests.
The main problem is that summary() is not reproducible because of date and possibly tiny numerical fluctuations.
Same with plots, we have almost only smoke tests, and verifying the content requires visual inspection.
