### ISSUE TITLE
coverage settings overstates actual coverage

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4331]
The settings in .coveragerc include both tests/* and results/*, each of which have disproportionately high coverage.   These constitute ~4/9 of the codebase.  Including them gives coverage of 73452/90504 (81%), without gives 35781/50504 (71%)

**Comment by josef-pkt** [comment]
results could be excluded but not tests
I am also checking sometimes that tests are actually run.

The absolute number for test coverage is not very relevant because it is now heavily biased by zero coverage modules in the sandbox.

**Comment by jbrockmendel** [comment]
You're right, there _is_ a ton of unused, unusable junk in the sandbox directory that should absolutely be removed.

**Comment by josef-pkt** [comment]
Some of that junk could be turned into gold or silver with some unit tests and a bit of TLC.

**Comment by jbrockmendel** [comment]
In the year that I’ve been involved I’ve seen nothing to suggest that will ever actually happen.  you’re the only person who plausibly could do that. For everyone else it’s 10k lines of unusable junk that makes it harder to find the worthwhile bits.

And that’s not getting into the large chunks of code that are redundant with non~junk that for some reason still gets hoarded.

**Comment by josef-pkt** [comment]
my time horizon is always 10 years, not 1.

Once we have 10 additional reviewers with expertise in their area, I can retire some of my code or take half a year or a year off from maintenance and PR reviewing to finish up some of my old and not so old stuff.
Until then, I need my "junk" whether it's in the sandbox, in issues or in stalled/dormant PRs, because it's >10 years of learning computational statistics/econometrics and python coding.

How about working for a few weeks on copulas #4046, if you want to convert/resurrect some "junk"?

**Comment by jbrockmendel** [comment]
Thank goodness none of the rest of us have any need for reliable software until 2028.

**Comment by josef-pkt** [comment]
In case you missed it. 
Large parts of statsmodels are beyond 1.0 and have been stable for many years. But we still don't have treatment effects, unit tested copulas, xtbond, sparse models, more post-estimation methods and a very large number of other things. To get there we need a 10 year plan. (But the plan does not include timings because it relies on volunteer work.)

(Even 100% test coverage does not mean much for software reliability in our case, except that it indicates that we have unit tested exceptions.)

**Comment by jbrockmendel** [comment]
I call BS.  Eg Iolib.tests.test_summary has been in the the same useless shape it is now since at least 2011.

It’s great that you’re focused on getting new features, no snark.  But maintenance is non-existent, and you’ve ignored or FUDded attempts to help.

**Comment by josef-pkt** [comment]
If test_summary bothers you so much, then why don't you figure out and implement a way to replace our smoke test for `summary()` by real unit tests.

R has a good set of copula functions, you or somebody else can write unit tests with verified numbers for copulas so we can get them out of the sandbox.

Same for a lot of other things that need a second or third round of reviewing/refactoring/enhancements and unit tests, things that haven't been touched in some time.

**Comment by jbrockmendel** [comment]
test_summary does bother me, but its one of hundreds.  There are dozens of PRs offering small fixes which get ignored.

The OP was about the fact that the advertised coverage numbers are misleading for potential users.  What's really bothersome is the notion that "its OK because the number are _actually_ meaningless" makes that OK.

**Comment by josef-pkt** [comment]
Actually, having around 80% coverage sounds about right, -10% for counting test files +10% for counting unused files. (The latter was roughly the drop when switching from nosetest to pytest)
The actual coverage is much higher for core modules than for supporting modules.

and I didn't say "meaningless"
I said "The absolute number for test coverage is not very relevant"

We still get a pretty accurate count for the change in coverage made by a PR. 
And to me it's more important to use coverage for maintenance than for advertising. (which was the first part of my initial comment)
