### ISSUE TITLE
SARIMAX forecast has strange down ward trend

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4420]
https://stats.stackexchange.com/questions/337766/statsmodels-sarimax-forecast-has-downward-slope

includes notebook and data

I don't find any explanation for why the forecast is down ward trending. The effect of exog is to small to affect the level so strongly.

**Comment by josef-pkt** [comment]
@ChadFulton  Can you look at this?

An explanation for this would be very helpful.
If it's not a bug, then maybe there is something that is "unintuitive".

**Comment by ChadFulton** [comment]
At first look, seems like a bug

**Comment by ChadFulton** [comment]
On the other hand, the R function `Arima` from Hyndman's `forecast` package yields identical results and forecasts, so it may not be a bug.

**Comment by ChadFulton** [comment]
Stata agrees as well, so I guess it's something unintutive. I'll try think about what's going on here, and I'll reply on stack exchange if I figure it out.

**Comment by ChadFulton** [comment]
I guess the answer is as follows:

They are specifying an I(2) process, so the change in the time series is itself integrated. The forecast for the *change* of the series is then like a random walk (i.e. it won't die out). This estimate of this change (and so the forecast going foreward) is given by the last estimated state.

Because the change of the series is fixed (either positive or negative depending on the last estimated states), the forecast will trend up or down, regardless of the AR and MA coefficients.

Since the model is seasonal, there will also be a seasonal pattern, but the same general explanation applies to a non-seasonal ARIMA model with d=2.

For future reference, it's easy to replicate the result with a very simple setup:

```python
np.random.seed(1234)

endog = np.random.normal(size=100)
mod = sarimax.SARIMAX(endog, order=(0, 1, 0), seasonal_order=(1, 1, 0, 4))
res = mod.smooth([0, 1.])
plt.plot(res.forecast(100))
```

![download](https://user-images.githubusercontent.com/280864/38286043-3a3a87e2-3791-11e8-918f-e205a794b5fa.png)

**Comment by ilia-sharafutdinov** [comment]
So will this be fixed?

**Comment by bashtage** [comment]
There is nothing to fix.  The forecast is correct give the model.  The solution to a problem like this is to revisit the model since I(2) processes are highly sensitive to small changes drifts especially over long horizons.

**Comment by bashtage** [comment]
Closing since no action.
