### ISSUE TITLE
VARProcess `exog` vs `intercept`

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4436]
`VarProcess.__init__` takes an `exog` argument where the docstring says it takes `intercept`.  The latter makes much more sense to me in context. e.g. `VARProcess.mean` I'm not sure what to make of the `self.exog` there...

**Comment by josef-pkt** [comment]
Most likely the docstring wasn't adjusted when the VECM PR added exog.

But I don't know or remember any details without digging back into this.

**Comment by jbrockmendel** [comment]
Looks like the `mean` method (the motivating case) is not hit in tests.

**Comment by jbrockmendel** [comment]
... and it looks like this is in fact broken

```
from statsmodels.tsa.vector_ar.var_model import *
endog = np.random.randn(100, 3)
exog = np.random.randn(100, 1)
model = VAR(endog=endog , exog=exog)
res = model.fit(maxlags=2)
>>> res.mean()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "statsmodels/tsa/vector_ar/var_model.py", line 820, in mean
    return np.linalg.solve(self._char_mat, self.exog)
  File "/usr/local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 390, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 100 is different from 3)
```

**Comment by josef-pkt** [comment]
The mean method is conceptually wrong.

- AFAICS, instead of exog there should be the constant mean value, i.e. the old `intercept` were params[0], the parameters for the constant.

- The Lutkepohl formula for long term mean is only constant if there are no exog except for a constant.  
   in analogy to AR long run constant = 1/ (1 - ar(1)) * constant_short_run
   I don't know what the analogue would be if there are seasonal dummies, or what the definition would be if there is a trend and y -> inf as t -> inf

I guess VAR uses the short-run parameterization for the constant, while ARIMA/SARIMAX use unconditional mean. Again, I'm not sure how seasonal effects and trend enter here.

If exog vary, then long run mean depends on exog, and for example could be defined for the long run mean (expected value or average over subperiods as in seasonal cycles) of the exog.

So, I guess fixing this requires either doing some math or checking Luetkepohl or similar, or defining `mean` for constant only, assuming other exog have long run mean equal to 0.

**Comment by josef-pkt** [comment]
one possible fix: use constant only by default and add exog arg, 

- constant only  
  replace `exog` in the formula by the params for the constant  (if available), e.g. `params[0]` if 0 is the const index  
  If there is no constant, then long run mean is zero.

- use exog assuming exog is the long run mean for it  
  replace `exog` in the formula by the linear prediction for the exog part, `exog.dot(params[index_exog])` where index_exog selects the appropriate part of `params  
  this could also default to using "mean", i.e. `exog = model.exog.mean(0)`

In this case, I don't like "mean" as a name, I think it should be something like "mean_long_run"

**Comment by jbrockmendel** [comment]
The easiest fix is to support only the no-exog case and revert to using `self.intercept` instead of `self.exog`.  Before jumping into handling the remaining cases, its worth asking if the new(ish) `exog`-using code is right elsewhere?  It isn't clear to me that it is tested.

**Comment by josef-pkt** [comment]
> its worth asking if the new(ish) exog-using code is right elsewhere?

My guess would be that there are still problems in some of the extra results with exog. `exog` was mainly added to support cointegrating factors for the short run VAR corresponding to a VECM.
There is too much post-estimation functionality in VAR/VECM to test all of them in a single already large PR.
Even when there are unit test, they might not cover enough cases.
e.g. #3819

aside: exog in VECM (and I guess VAR) is mainly for deterministic parts or for exog with a very strong exogeneity assumption

**Comment by jbrockmendel** [comment]
OK, skipping over assorted snide remarks, what's the gameplan from here?

**Comment by josef-pkt** [comment]
see #3775

What I usually start with is to try out different examples and try to find "holes", things that look suspicious or don't work, or confirm that thinks look good.

The other approach is to check test coverage and try examples specifically for the parts that don't have enough coverage.

The third approach is to let users find bugs or problems, which is not too bad if they end up with an exception, but silently returning wrong numbers is very bad and will get prio-high and bug_wrong labels. The latter still happens every once in a while but new code is considered experimental. Usually the core results are unit tested well enough, but there are always auxiliary results that will or might have not enough test coverage.

(Note this is nothing specific to VAR/VECM. The same applies to almost all new enhancements, and more so to big enhancements or enhancements that rely on a large amount of inheritance.)

**Comment by jbrockmendel** [comment]
I understand we have different thoughts on the acceptability of the status quo, but let me suggest an alternative course of action, which includes an offer of free labor:

1) Revert vecm.
2) Give me a relatively free hand to get var_model (and ideally ar_model and arima_model which you're planning to deprecate anyway) into pristine condition, with thorough test coverage.  irf.py, which is essentially untested right now, can also go into the "offer of lots of free labor" pile.
3) Then vecm can be implemented on top of a rock-solid foundation.
4) When vecm is re-implemented, we'll do it incrementally and make sure it is well-tested (with non-junk tests) along the way.

Upsides:
- This gets fixed thoroughly and in a timely manner.
- In the interim, confirmed-as-wrong code is taken out of master.
- Chad, Kevin and I are all qualified to work in this area, so this can be taken off of your plate.
- Single-commit PRs can avoid the git history/blame issues discussed elsewhere.
- A precedent is set for delegating responsibility for corners of the code-base.

Downsides:
- it involves putting a modicum of trust in other people, including a known rabble-rouser (me)
- vecm goes out of master for a while, might not be in 0.9.0 depending on timelines

**Comment by josef-pkt** [comment]
No, that's not going to happen. (We would be giving up good code with no assurance that we would get anything much better.)

VECM is around 1.5 * 4 or more months of work, including a lot of design work. So far there is only `mean` in VAR confirmed as wrong code. AFAIK most/all the basic parts/almost all of VECM is solid. 

We have already a PR with a VAR rewrite/refactor that stalled because of too many backwards incompatible changes. VAR has some problems, especially with the names, but overall I don't see any need for changing the structure or for a full rewrite, i.e. if I had to rewrite VAR, then most things would stay the same.

There is no code that is "rock-solid" until it has been battle-tested for several years. To try to make something "rock-solid" at the first merge sounds impossible given our time and work limitations, and often would not even be possible in a commercial setting.

There are cases where a new start makes sense, like SARIMAX on top of the, at the time, new statespace framework, but in my view VAR/VECM is not one of those.
Actually, we do need a second version of VAR based on general SUR/reg3 and nonlinear optimization to handle linear restrictions on the parameters, e.g. zeros in the matrix of lag coefficients, but that (most likely) won't replace the current VAR/VECM because it will be much slower for the unconstrained case.

SVAR, IRF confidence intervals have larger problems, but that's only marginally related to VECM or VAR themselves. (I think even SVAR has a solid core, it is just missing test coverage and *extras*).

Related to the previous discussion about agile programming. We need iterations and rounds of improvement, but we don't need to start from scratch each time.
That is, I think working on improving and unit testing the extra parts of VAR/VEM/SVAR or writing a new nonlinear optimization based SUR/VAR/VECM is a much better use of our time than starting a full rewrite of existing code.

**Comment by jbrockmendel** [comment]
Disappointed but not surprised.  The offer stands.

> [...] than starting a full rewrite of existing code.

If I gave the impression that the idea was a full rewrite, then that was a miscommunication.  The idea is to take the pre-vecm code that was _relatively_ reliable, clean it up, make sure it has good test coverage with meaningful (i.e. non-smoke (with the possible exception of plotting)) tests.  Then port over vecm in smaller increments (e.g. changes to test_whiteness and test_normality could be independent PRs) making sure these are each well-tested as we go.

> We need iterations and rounds of improvement

I'm very much on board with a "lots of small improvements" model, now we just need to convince the guy in charge of that green button.

> There is no code that is "rock-solid" until it has been battle-tested for several years

Define the terms however you like.  I think the meaning "much better than the existing code, especially seeing as how we _don't even know what is currently tested_" is clear in context.

> VAR has some problems, especially with the names

Agreed.  I very much don't want to get stuck with both "test_whiteness" and "test_whiteness_new".

> We would be giving up <s>good</s> code

FTFY.  I'm not saying its necessarily bad code (except for the tests; the tests are bad code), just that we really don't know if the code is good.

> with no assurance that we would get anything much better

I think this gets back to your personal git style discussed elsewhere, namely the frictional costs of merging a PR.  If that friction were reduced (setting aside for now _how_ it could be reduced), then the "much" part of "much better" would not be a constraint.  Many small improvements could add up.

Spitballing here: is there a corner of the code where we could test-run the development/maintenance model I'm suggesting?  i.e. delegate merge privileges/responsibility with an agreed-upon limited scope, then see if fast turnaround and many incremental improvements a) materialize, b) result in better code, c) affect contributor behavior.

**Comment by josef-pkt** [comment]
> frictional costs of merging a PR
> "test_whiteness" and "test_whiteness_new"

Problems with many refactorings of existing code are backwards compatibility consideration and watching out that changes don't introduce bugs in existing code.
This is always a lot of work for the reviewer (i.e. mostly for me), but it's much easier with new code which is defined as experimental and doesn't have backwards compatibility constraints.
For test_whiteness I bailed out. I just didn't want to think about whether or how to change it in a backwards compatible way, given that I had to review a few thousand other lines of code.

> just that we really don't know if the code is good.

Most parts of VECM is good, and I know it! 
It's just the fringes that I didn't review carefully and where some problems might still exist.

> is there a corner of the code where we could test-run the development/maintenance model I'm suggesting?

It's easiest with new(er) code, unused code or parts that are your "own areas". (The last applies eg. to Kerby, Chad, mostly to Kevin and to others that have their specific areas).

Examples in this neighborhood that do need a lot of work and unit tests are SVAR and the non-functioning IRF confidence intervals where backwards compatibility considerations either don't apply or are pretty weak.
Other cases would be to take over a stalled PR.

The problem is that somebody still needs to check/review that it follows statsmodels code and API patterns. In some cases that's easy and only needs a quick skimming of the code, in other cases a PR needs considerable changes to make it consistent with statsmodels structure and usage patterns.
(example: GSOC projects are a lot of work for the mentor and maintainers to get the code into a mergable state. And when mentors and maintainers don't spend that much time, we end up with something like SVAR, and not like VECM where I did spend a lot of time on it as both mentor and maintainer/reviewer/merger.)
My frictional cost of merging depends on whether a quick reading or skimming doesn't raise any red flags that I need a much closer, more time consuming look at the changes. And then, how easy it is for me to adjust my view or opinion or for the code to be "fixed".)

**Comment by jbrockmendel** [comment]
> Problems with many refactorings of existing code are backwards compatibility consideration and watching out that changes don't introduce bugs in existing code.

No one is suggesting a thousand-monkeys approach.  A major part of the goal is to get the tests to the point where they can _actually be relied upon_ to detect bugs caused by potential changes down the road.

> This is always a lot of work for the reviewer (i.e. mostly for me),

The proposal is very specifically to get some of this off of your plate.

> Most parts of VECM is good, and I know it!

I'm happy that you're happy, but on the off-chance that there is value in anyone _else_ being confident, readability counts and non-junk tests count.

Quick: how many tests pass a non-None `exog`?  Are any non-trivial `exog` values passed?  (AFAICT the answers are "a few hundred, as measured by having a warning emitted by `VARProcess.__init__` when this occurs" and "eyeballing these warning messages it looks like all stacked identity matrices, so probably not")

I think we're done here.  I'll check back in 2028 to see if this has been fixed.

**Comment by josef-pkt** [comment]
This is still a bug issue, and should stay open until it is fixed.

Why do you go to the extremes? 
Nothing prevents you from adding more unit tests and fix the parts that are wrong.
Unit tests against R or Stata will be easier to convert to good looking unit tests, because they don't just print their results. (Although they might use other definitions for some parts that are not the same as Luetkepohl/statsmodels.)

You found one bug in VAR/VECM.  So, thank you for the report.
Next steps: Did you check whether and what Luetkepohl says about this case? What's the behavior of R or Stata, or ... for this case? How do they define long run mean?

Did you run the notebook or examples for VECM to see if there are other things that don't work correctly?

There is a large amount of work that can be done short of a rewrite.

VECM supports deterministic that are in the code similar to exog, which works, e.g. #3819
(In VECM the main difficulty was in whether deterministic exog go into the cointegrating equation or into the short term difference equation or in both. We did not have enough time to fully look into case for strongly exogenous stochastic exog.)

BTW: It is NOT friendly to call someone's code junk if it represents weeks of work and provides unit tests that covers large part of the code, and does it against the book/reference authors' program. The parsing and code structure are only partially related to what the unit tests actually cover. 
In contrast to your statements about "junk", I think VECM was a very good and successful GSOC project for a first time GSOC student, and one of the best that I have seen. But there is easily enough work left for a second GSOC sized project.

**Comment by jbrockmendel** [comment]
> There is a large amount of work that can be done short of a rewrite.

Again, no one has called for a rewrite.

> You found one bug in VAR/VECM. So, thank you for the report.

See also #4439.
  - irf_errband_mc and irf_resim would raise AttributeError if they were ever called

> Why do you go to the extremes?

Huh?  You mean closing the issue?  Because we've gotten to the point in this process where trading messages is frustrating and unproductive.

> BTW: It is NOT friendly to call someone's code junk if it represents weeks of work and provides unit tests that covers large part of the code

That's a fair point, and I'll make a point of giving the author positive reinforcement next time we're on the same thread.  But the fact remains that the tests are effectively useless for the purpose of reading and evaluating what has actually been tested.

As we've discussed elsewhere, you put a lot of effort into the statistics side of things, and I _do_ appreciate that.  But the code quality side of things remains more or less ignored.  As long as _you_ are the only person who needs to be convinced the code is OK, this system works (see also discussion of coverage reports); but that is too low a bar for an important (and along many dimensions very good) project.

>Did you run the notebook or examples for VECM to see if there are other things that don't work correctly?

Of course not.  The notebooks and example files are filled with years-old refuse, with no indication which parts of which parts are actually usable (e.g. the old GMM vs garch sandbox discussion)

> Nothing prevents you from adding more unit tests and fix the parts that are wrong.

Well, you do.  See the large number of PRs that try to make incremental improvements that go nowhere.  Why would I put time into making a bigger PR when obviously-correct tiny PRs are ignored for months on end?

**Comment by jbrockmendel** [comment]
Closing in faor of #4442.
