### ISSUE TITLE
Anything worth saving from garch?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4484]
I'm going through the various `information` methods to check if they're internally consistent (spoiler: no) and finding it would be easier if there weren't half-finished Model classes to take into account.

In particular `sandbox.tsa.garch` has a copy/pasted version of LikelihoodModel, one that has probably fallen out of date since it was pasted.  Could we just import the real one and get rid of the copy/paste?  Grokking this module would be easier if the contents were limited to the relevant bits.

- garch.miso_lfilter_old has apparently been copied to filtertools.miso_lfilter.  Can we just import that?

- garch.TSMLEModel appears copy/pasted from tsa.mlemodel.  The tsa.mlemodel version is _also_ unfinished, but de-duplicating it would make things more manageable.

**Comment by jbrockmendel** [comment]
> [...] if there weren't half-finished Model classes to take into account.

@josef-pkt can we please take a little time to triage these classes between "worth fleshing out" vs "kept around for reference/nostalgia"?

There have been a number of issues where a sticking point has been "we don't know if X is applicable to all existing model/results classes", which would be much easier to address if could at least pin down what those classes are.

**Comment by josef-pkt** [comment]
It's a lot of work to figure out in which way development should or will go.
E.g. we need heteroscedastic models in general, GARCH is not urgent because Kevin covers it. But we need at least Gaussian and GLM variants with estimated heteroscedasticity.
Similarly, we need time series filters, most likely with numba for non-gaussian models, like the Poisson-ARMA that was my numba trial versions.
I don't know what will be reusable.

as for the duplicated code:

> one that has probably fallen out of date since it was pasted.

Which means that the rest of the functions/classes in the sandbox might not work with the new official version. That is, it needs a compatibility check before deleting the old version, otherwise it make reusing any of the old code more difficult because it has more sources of refactoring bugs.

**Comment by jbrockmendel** [comment]
> Which means that the rest of the functions/classes in the sandbox might not work with the new official version. That is, it needs a compatibility check before deleting the old version, otherwise it make reusing any of the old code more difficult because it has more sources of refactoring bugs.

That is a bad reason.  a) the code doesn't work at the moment anyway (for _starters_ it imports `numdifftools` which is no longer a listed dependency), b) it is easy to check that the non-trivially out of date code is in `fit`, and the up-to-date code is compatible with the older version, and c) even if it weren't the appropriate response is to override `fit` in `GARCH`.
