### ISSUE TITLE
NegativeBinomial not getting wrapped correctly

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4529]
The non-transparams case returns CountResultsWrapper instead of NegativeBinomialWrapper.

Making an effort to be systematic would help prevent this kind of thing.

**Comment by josef-pkt** [comment]
bug or intentional?

I've never looked at that.
It looks intentional.
NegativeBinomialResults is almost the same as CountResults, except for some code about the extra params. 

It still looks like a bug, because we also use transparams is false for NB1 and NB2 depending on the optimizer

```
        self._transparams = False # always define attribute
        if self.loglike_method.startswith('nb') and method not in ['newton',
                                                                   'ncg']:
            self._transparams = True # in case same Model instance is refit
        elif self.loglike_method.startswith('nb'): # method is newton/ncg
            self._transparams = False
```

actually I'm not sure, the code in NegativeBinomialResults might have been intended for some transformed case, but I cannot tell what this is doing without looking closer at it and trying an example.

```
    @cache_readonly
    def lnalpha(self):
        return np.log(self.params[-1])

    @cache_readonly
    def lnalpha_std_err(self):
        return self.bse[-1] / self.params[-1]
```

I'm labeling this as a bug candidate. Even if there is no bug, this sounds fragile.

**Comment by josef-pkt** [comment]
If you have an example script to show a possible bug or shows that there is no bug (in the numbers), then it would be helpful if you add it to a comment in this issue.

**Comment by jbrockmendel** [comment]
That's plausible, albeit a bit unfortunate naming-convention-wise.
