### ISSUE TITLE
statsmodels-0.9.0: No module named 'numpy'

### ISSUE THREAD

**Issue by Haber-He** [statsmodels/statsmodels#4651]
Collecting statsmodels>=0.8.0 (from -r requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/67/68/eb3ec6ab61f97216c257edddb853cc174cd76ea44b365cf4adaedcd44482/statsmodels-0.9.0.tar.gz (12.7MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hferqxy1/statsmodels/setup.py", line 347, in <module>
        from numpy.distutils.misc_util import get_info
    ImportError: No module named 'numpy'
    
    ----------------------------------------
[91mCommand "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hferqxy1/statsmodels/

**Comment by Thomasillo** [comment]
Same for me

**Comment by jbrockmendel** [comment]
Similar 0.9.0 installation issues:

- running `tox` on a package that has statsmodels as a dependency raises the numpy error in the OP.
- python3 on ubuntu 16 pip3 install goes through OK but on import raises `ImportError: cannot import name '_representation'` (no such problem on py2) (this occurs both with and without `tox`)

**Comment by matthew-brett** [comment]
Hi.   Try again now?  I am hoping that the wheels will have fixed the _install_ problems.

You will still need to install numpy and scipy and pandas in order for statsmodels to import correctly.

For reference the `numpy` error is because the numpy package is a build-time dependency of statsmodels.   Funnily enough, `ImportError: cannot import name '_representation` , is because of a hidden build-time dependency on Scipy.   That is, if you want to install statsmodels from source, you need scipy installed already, and if you don't, statsmodels builds incorrectly.

**Comment by zertrin** [comment]
Note: On Linux, this works for Python 3.5 and 3.6 but not for 3.4 because [there is no Linux `cp34` wheel for statsmodels 0.9.0](https://pypi.org/project/statsmodels/0.9.0/#files) (version [0.8.0 had Linux wheels for py34](https://pypi.org/project/statsmodels/0.8.0/#files)).

Consequently, cannot use requirements.txt with statsmodels for py34 as of version 0.9.0.

A workaround for requirements.txt is to pin the statsmodels version for py3.4 to something before 0.9.0:

```
statsmodels; python_version >= '3.5'
statsmodels<0.9; python_version == '3.4'
```

**Comment by zertrin** [comment]
As a matter of fact, this is part of my requirements_dev.txt now :wink:

```
numpy
pandas; python_version >= '3.5'
pandas<0.21; python_version == '3.4'
scipy
statsmodels; python_version >= '3.5'
statsmodels<0.9; python_version == '3.4'
```
