### ISSUE TITLE
Can SARIMAX model output the confidence intervals of forecasts like ARIMAResults?

### ISSUE THREAD

**Issue by samosun** [statsmodels/statsmodels#4806]

**Comment by ChadFulton** [comment]
Yes, if you use the `SARIMAXRresults.get_forecast` method. For example:

```python
import numpy as np
import statsmodels.api as sm

np.random.seed(1234)
x = np.random.normal(size=100)
mod = sm.tsa.SARIMAX(x)
res = mod.fit()
fcast = res.get_forecast(10)
print('Forecast:')
print(fcast.predicted_mean)
print('Confidence intervals:')
print(fcast.conf_int())
```

yields

```
Forecast:
[ 0.10982 -0.02356  0.00505 -0.00108  0.00023 -0.00005  0.00001 -0.
  0.      -0.     ]
Confidence intervals:
[[-1.79673  2.01636]
 [-1.97349  1.92637]
 [-1.94685  1.95695]
 [-1.95308  1.95091]
 [-1.95176  1.95223]
 [-1.95205  1.95195]
 [-1.95198  1.95201]
 [-1.952    1.95199]
 [-1.952    1.952  ]
 [-1.952    1.952  ]]
```

**Comment by samosun** [comment]
thanks a lot!

**Comment by EdTheEagle** [comment]
The resulting model  of your example above is (1,0,0), which requires the previous value to predict the next one. By making multiple predictions the model uses predicted values to predict the next one. Why does the confidence interval not grow when predicting further out ? I've tried with predicting 100 values out, but the confidence interval does not grow. Is that expected behavior or am I missing a setting?

Thanks

**Comment by ChadFulton** [comment]
This is expected behavior. In stationary models, the forecasts will converge to a fixed value with fixed error bands, corresponding to the unconditional distribution of the model.

On the other hand, if you have a non-stationary model (such as `order=(1, 1, 0)`), then the confidence intervals will grow without bound over time.

**Comment by rurjais** [comment]
I was trying to deal with this issue, but I think I need clarification on 3 main issues:

1- when here you talk about "confidence intervals" what we are talking about is actually "prediction intervals"? Furthermore, what one is assuming from your answer about the converging to a fixed value with fixed error bands when talking about stationary models, is that there is NO "feedback" of the predictions into the model itself right?

2- If an ARIMA model is order=(3,0,1), then, after h=3 the model starts converging to the mean of the series right? In this case, the prediction intervals will have a stable distance because the fitted residuals are normal. But, if one wanted to create this "feedback" loop of \hat{y} in the series to predict much further than those h=3, what would be the behavior of these prediction intervals? would they keep the same distance along all this horizon? If not, what formula should we use to calculate those?

3- I still don't get quite clearly why prediction intervals grow when a model as a D\geq1. Can you provide any source on this?

**Comment by bashtage** [comment]
>  when here you talk about "confidence intervals" what we are talking about is actually "prediction intervals"? Furthermore, what one is assuming from your answer about the converging to a fixed value with fixed error bands when talking about stationary models, is that there is NO "feedback" of the predictions into the model itself right?

The output of what Chad showed is the prediction interval. 

> 2- If an ARIMA model is order=(3,0,1), then, after h=3 the model starts converging to the mean of the series right? I
No.  Depending on the parameters it could oscillate or still have a peak more than 3 period ahead before eventually mean reverting.  All you are guaranteed is that if the model parameters are consistent with covariance stationarity that it will eventually mean revert.

> In this case, the prediction intervals will have a stable distance because the fitted residuals are normal. But, if one wanted to create this "feedback" loop of \hat{y} in the series to predict much further than those h=3, what would be the behavior of these prediction intervals?

They will tend to keep widening for some horizon but eventually stabailize.  If the model is consistent with covariance stationarity, the long run forecast error variance is that same as the variance of the time series (implied by the model parameters).

> It would they keep the same distance along all this horizon? If not, what formula should we use to calculate those?

You need to get the impulses for your horizon for you parameters of your ARMA. See https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_process.ArmaProcess.impulse_response.html#statsmodels.tsa.arima_process.ArmaProcess.impulse_response


> I still don't get quite clearly why prediction intervals grow when a model as a D\geq1. Can you provide any source on this?

D=1 coresponds to a random walk (plus short run components).   See https://people.duke.edu/~rnau/411rand.htm for a basic explanation for a simple random walk.

**Comment by rurjais** [comment]
Thank you for your prompt reply.

I don't think I understood quite right the issue with the impulses though :) Is there any source (apart from the link you sent) that can help me on that and understanding its relationship with the prediction intervals and the feedback of \hat{y}?

Furthermore, is there also any reference, even from code, that displays how, in my case, `y_pred = model.get_forecast(steps=2, exog=x_input)` is calculated? Because it is not clear for me how SARIMAX (in my case) gets h\geq2 without this feedback loop of the previously predicted value. What I am missing...?
