### ISSUE TITLE
arima summary ValueError: xnames and params do not have the same length

### ISSUE THREAD

**Issue by ggrrll** [statsmodels/statsmodels#4870]
Hi, 

after fitting with
```
my_arima = sm.tsa.ARIMA(endog=y_train.values,exog=x_train,order=(0, 1, 0)).fit()
```

 `my_arima.summary()` gives

`ValueError: xnames and params do not have the same length`

I don't understand what's going on as I am not giving any `exog_names` 

Thanks for support.
ps: find attached the `y_train` -- for `x_train` you can use simply `np.arange(0,35)`

pps: thanks for the module...It's the first time I am using it (with ARIMA). It's nice that it covers many topics. However, would be nice to have a better documentation, given that many attributes, functions are still empty, or with very little documentation.

[y_train_arima.txt](https://github.com/statsmodels/statsmodels/files/2278225/y_train_arima.txt)

**Comment by josef-pkt** [comment]
This might be a bug or feature (?) if there are no parameters to estimate.
I don't remember the details, but the `constant` will be one parameter in this model (which can be or is included in exog). We explicitly included the no lags case as reference model for model comparison. So this is more likely a bug, unless constant is also dropped (trend='nc').

SARIMAX and the statespace models have now better documentation than ARIMA, and are better maintained.
However, I don't know if that supports a "no-parameter" model.

Empty `params`, or no estimated `params` has an open issue, IIRC, that I don't find anymore. 
There is no generic support, e.g. in summary or similar for that case.

**Comment by josef-pkt** [comment]
#3567 is the no estimated params issue

**Comment by ggrrll** [comment]
I see -- thanks @josef-pkt 

For the 'pps': do you always suggest to use SARIMAX instead?

**Comment by josef-pkt** [comment]
> do you always suggest to use SARIMAX instead?

In general yes. 
There might be a few cases where the availability of results or performance might differ.
However, SARIMAX is the more "modern" version, and ARIMA is largely in bug-fix mode. But, ARIMA has been around for a long time and also works well. 
There can be problems in optimization in "not nice" cases in either model, those cases are more likely to be fixed in SARIMAX.

Deprecation of ARIMA is discussed in #3884, but hasn't been decided yet, and even if/when ARIMA is deprecated it will stay in statsmodels for a longer time given its large historical user base.
