### ISSUE TITLE
Method of adding a constant

### ISSUE THREAD

**Issue by zxdawn** [statsmodels/statsmodels#4946]
As shown in this [post](https://stackoverflow.com/questions/51917377/different-results-of-seaborn-and-statsmodels), the method of adding constant may results in misunderstanding (It's adding a constant in regression not adding x as constant values). 

So, it's better that add an option to `sm.OLS(y, X).fit()`, like `'constant=true'` (default is false), instead of  adding `X = sm.add_constant(x)` manually.

**Comment by bashtage** [comment]
This is just a terminology issue.  In many parts of Econometrics and some statistics, constant is widely used to mean the intercept.  It won't be possible to change `fit` to have `intercept=True` since this would completely change every model.  The `exog` should contain all variables you want to include in your model, including a constant (a column of ones).

In any model of the form

y = a + b * x + eps

there is a hidden 1 next to the a,

y = a * 1 + b * x + eps
