### ISSUE TITLE
De-duplicate HoldIt class

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4994]
Defined in tools.dump2module but not used elsewhere within statsmodels (useful externally?).  A not-quite-identical class is defined in statsmodels/sandbox/tests/maketests_mlabwrap.py and used both there and in statsmodels/sandbox/tests/savervs.py

**Comment by bashtage** [comment]
You should see how many `class Bunch` definitions there are.

**Comment by josef-pkt** [comment]
We don't have yet a proper class hierarchy for Bunch/Holder classes, so the easiest is to just define them where they are needed. For hypothesis tests they get sometimes converted to some kind of Results classes with extra methods.
Design for inheritable Bunch/Holder/TestResults classes is still open.

(My Stata export `do` file defines new Holder classes each time.)

**Comment by N-Wouda** [comment]
All `class Bunch` definitions 'out there' follow one of the following two templates, (i),
```python
class Bunch(dict):
    def __init__(self, **kw):
        dict.__init__(self, kw)
        self.__dict__  = self
```
And (ii),

```python
class Bunch(dict):
    def __init__(self, **kw):
        dict.__init__(self, kw)
        self.__dict__  = self

        for i,att in enumerate(['params', 'bse', 'tvalues', 'pvalues']):
            self[att] = self.params_table[:,i]
```

I have some spare time and could consolidate this, i.a., into a proper class hierarchy, and then redirect current definitions to use one of the two classes. After that, I'm very willing to look at Hold(It/er) and TestResults, but I do not know how much time I'd have left.

@josef-pkt @bashtage where'd you suggest to place the `Bunch` definition in the code base? My initial thoughts was a module `parameter_objects` in `sm/tools` , which would then expose these classes.

**Comment by josef-pkt** [comment]
The problem is that I actually don't like `Bunch` classes (subclass of dict) anymore, i.e. I never use the dictionary access, and only like attribute access as in our Model Results classes.

based on a file search:
tsa (Chad in newer code) uses them quite a bit, but imported:
`from statsmodels.tools.tools import Bunch`

there are some miscellaneous uses where a Bunch class is not always a Bunch(dict), but are just what I switched to calling Holder classes.
And there are many Bunch classes in Stata results, but those are part of the do file, i.e. autogenerated. (Those could be Holder classes because we only use attribute access AFAIK)

for test results as replacement of Bunch and Holder classes
#277 first open issue from 2012
#1182 initial discussion from 2013 
with still no general outcome, just a lot more special cases
