### ISSUE TITLE
Replace coveralls integration with codecov.io

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#5060]
Codecov.io is more reliable and provides both a better report and better interaction examining coverage. 

Reporting to codecov is already enabled, https://github.com/statsmodels/statsmodels/blob/master/.travis.yml#L140 
so only the integrations need to be enabled (and coveralls disabled).

**Comment by josef-pkt** [comment]
We had codecov before, but we lost the PR comments a while ago, most likely because github is reorganizing webhooks and apps.
I installed the codecov integration but there was no "success" feedback, so we need to see whether it works correctly.

We can keep both. I like coveralls better than codecov for browsing files. I find codecov is hiding the files too much and it takes me each time too long to find them. 
(i.e. IMO codecov is too much change set oriented)

**Comment by bashtage** [comment]
I think they moved to a github app https://github.com/apps/codecov 

If you get the codecov extension for chrome you can see coverage on github when you look at changes in a PR.

**Comment by bashtage** [comment]
Working again.

**Comment by jbrockmendel** [comment]
Want part of the issue here that coveralls incorrectly reports small decreases in coverage, making red/green icons non-meaningful?
