### ISSUE TITLE
Is smoothers_lowess_old needed?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5142]

**Comment by josef-pkt** [comment]
I'm not going to look for an answer, for now.
I'm trying to catch up with PRs that are not authored by jbrockmendel and have been neglected too long.

**Comment by jbrockmendel** [comment]
> I'm not going to look for an answer, for now.

So... should I close and open a duplicate in a couple weeks?

> I'm trying to catch up with PRs that are not authored by jbrockmendel and have been neglected too long.

Part of that is great... the other part is petty. bashtage pointed out a whole bunch of perfectly trivial ones.  Delegation is the way to go buddy.

**Comment by josef-pkt** [comment]
> the other part is petty. bashtage pointed out a whole bunch of perfectly trivial ones. Delegation is the way to go buddy.

You have 90 open PRs, almost twice as many as I do.
I have to wade through 3 pages of jbrockmendel pulls to find the ones that are neglected, and I'm not looking anymore through yours to find the 5 or 10 that I would like to merge.
Give it a break, work on discontinuity design and let reviewers and maintainer catch up, and prepare a release.
Also, I will stop all your CI pull testing when I push some PRs because I don't want to wait for 24 hours to get some results back.

(grumpy old man)

**Comment by jbrockmendel** [comment]
I’m very happy to help triage, by temporarily closing if necessary.  The fact remains that this is not a one person job and treating it as such does a disservice to the community.  Don’t let the fact that the messenger is obnoxious turn you off to the idea of teamwork.

> (grumpy old man)

Yah... that part I can increasingly relate to.

Will step away for a while, encourage bashtage to take over my more painfully obvious PRs in the interim.  All the best.
