### ISSUE TITLE
Does GMM use different patterns on purpose?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5183]
@josef-pkt I'm looking over gmm.py and tests, looks like it deviates from standard patterns in a few places (e.g. `get_bse`).  Are these intentional changes or legacy patterns?

**Comment by josef-pkt** [comment]
> Are these intentional changes or legacy patterns?

I guess both. 
GMM predates cov_type, i.e. the first generation of the sandwich code was in GMM. GMM is more complicated than `cov_type` in `fit` because we need the covariance estimate of the moment conditions also for the weights. So we need extra code and extra modularity so weights and final cov_params can share the code for the estimation of the covariance of the moment conditions/score_obs.

Trying to figure out the common pattern across models is always work in progress, e.g. #1790.
(to some extend #2096)

**Comment by josef-pkt** [comment]
In general, we have or will have some `get_xxx` methods when we need options, args and kwargs, when the underlying `xxx` method is a (cached) attribute.
i.e `get_bse` is an intentional change to allow for options in bse, but I don't know whether it should survive in the long term. e.g. cov_type moved eventually into fit without any alternative officially supported option to get bse for other cov_types (except some special cases in OLS, GEE and RLM :).
