### ISSUE TITLE
SUMM: FAQ-D

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5190]
There are 161 open issues with the FAQ label.  9 of the first 25 have "FAQ-D" in the title.  Doing a search for FAQ-D gives 60 results, some of which have neither "FAQ-D" in the title nor the FAQ label.

Issues marked as FAQ-D are AFAICT for developer reference.  The biggest upside to using GH issues for these is the ease with which they can be opened.  Jotting down a quick note-to-self is a piece of cake.

I propose that these continue to be used as an "inbox" for jotting down these notes, but that a more organized, curated, long-term version be put somewhere else, e.g. in the repo or in the GH Wiki.  By organizing these we can see where there are gaps in the "institutional memory".  Also to the extent that GH Issues represent Things That Need Attention, these can be distracting.

**Comment by josef-pkt** [comment]
FAQ issues were intended to become a FAQ doc page.
The problem is that it is work which I never did. For my workflow it is much faster to work with and searching issues than searching the docs.  (see missing chm htmlhelp discussion)

> Also to the extent that GH Issues represent Things That Need Attention, these can be distracting.

215 `type-bug` issues versus 839 `type-enh` and 278 mostly older `design` issues.
With me as main issue author, the issues tracker was never restricted to being a bug tracker.

eg.
Once I thought the Wiki might be useful for design notes, see SMEP drafts https://github.com/statsmodels/statsmodels/wiki/_pages
Once I thought I should use a Wiki in a private repo https://github.com/josef-pkt/misc/wiki/_pages

But the only stable state is using statsmodels issues, and SUMM issues.

**Comment by jbrockmendel** [comment]
> FAQ issues were intended to become a FAQ doc page.  The problem is that it is work which I never did.

I'll offer to provide a big chunk of the labor, if a consensus is reached that this is a worthwhile goal.

> For my workflow it is much faster to work with and searching issues than searching the docs.

Presumably such a change would be an inconvenience to your workflow at least in the short run.  My hope is that if we organize the resulting DevDocs well enough, it will be comparable in the longer run.

Also keep in mind that the status quo is very well optimized for your workflow, but much less so for others'.  That is not a problem in itself, but I think there's value in making onboarding easier for newcomers.
