### ISSUE TITLE
tsa.stattools.acovf is slow and is missing nobs options

### ISSUE THREAD

**Issue by wesm** [statsmodels/statsmodels#52]
Original Launchpad bug 661222: https://bugs.launchpad.net/statsmodels/+bug/661222
Reported by: josef-pktd (joep).

I was trying an example from nitime

> > > X.shape
> > > (20480,)
> > > sm.tsa.stattools.acovf(X)[:order+1]    #slow
> > > 
> > > sm.tsa.stattools.acovf(X, fft=True)[:order+1]   #fast

I think it would be good to add an "auto" option that picks the fastest way of calculating the acovf

Also, code completion doesn't show an option to get only a small number of acovs

**Comment by bashtage** [comment]
@josef-pkt This ancient issue can be closed.  Both are fixed in master (fft on its way to becoming true, and nobs)

**Comment by josef-pkt** [comment]
What about the "auto" options?
I was looking at this issue earlier today and wasn't sure about "auto"

**Comment by bashtage** [comment]
I think auto isn't worth much since the difference between the methods when the time series is slow is in the `us` range while the difference when the series is long is in the `s` range. Always using fft is the simplest way to ensure good performance when it matters.

Additionally, the auto can't really exist since it is platform dependent and it is possible that fft may be faster or slower for any (small) size due to the implementation of the fft and whether it makes use of uarch features of the cpu being used.

**Comment by josef-pkt** [comment]
thanks, closing then
