### ISSUE TITLE
Ljung-Box test for residues from external model generates very small p-values

### ISSUE THREAD

**Issue by ispmarin** [statsmodels/statsmodels#5209]
Hi all, 

I'm testing the fbprophet library and came up with a very contrived example:

```
import statsmodels.api as sm
from fbprophet import Prophet
import pandas as pd
import numpy as np

idx = pd.date_range('2016-01-01', '2016-05-04', freq='D')
phase = np.pi / 2
len_idx = len(idx)
points = np.arange(0, len_idx)
df = pd.DataFrame({'y': np.sin(points * 2 * np.pi / 30 + phase) + points / 100}, index=idx)
df['ds'] = df.index

mdl = Prophet()
mdl.add_seasonality('monthly', period=30, fourier_order=5)
df_result = mdl.predict(30, 'D')
_ = mdl.model.plot(df_result)
```

generating a result like this:
![image](https://user-images.githubusercontent.com/12247/45551221-8a546700-b803-11e8-9060-adba0393422b.png)

so I generate a out of sample forecast, 
```

df_train = df.iloc[:100]
df_test = df.iloc[100:]
mdl = Prophet()
mdl.add_seasonality('monthly', period=30, fourier_order=5)
df_forecast = mdl.predict(df_test)
df_forecast.index = df_forecast.ds
residue = df_test.y - df_forecast.yhat
nlags = 20
sm.stats.diagnostic.acorr_ljungbox(residue, nlags)
```
```
(array([26.58531982, 37.54004325, 39.75143298, 39.87513462, 39.87724859,
    39.87823833, 39.87841515]),
 array([2.52152459e-07, 7.05152716e-09, 1.20293579e-08, 4.59357440e-08,
    1.58094709e-07, 4.81312117e-07, 1.32806258e-06]))
```

and the p-values of the Ljung-Box test are very small. If I understood correctly the test, the null hypothesis would be valid if the residues don't have autocorrelation, but in this case the p-values are very small. The residues look like this:

![image](https://user-images.githubusercontent.com/12247/45551291-c982b800-b803-11e8-970c-0297190ae218.png)

Am I misunderstanding the test or how to use the function?

**Comment by ispmarin** [comment]
Hi @josef-pkt, thank you for your answer.

The forecast is just splitting the data into train and test, training the model with the training and forecast with the test dataset. 

I agree that the errors will be serially uncorrelated if the model captures the past information. That's why I'm trying to use the Ljung-Box test: to test if the residuals of the forecast versus the test data show any correlation. My understanding is that if the model captures the data well, the test p-values will be larger than alpha and the null hypothesis of the test cannot be rejected.

For me, it seems that the forecast is very good, residuals are very small and with low autocorrelation, but the test is telling me the opposite: very small p-values, meaning that the residuals of the forecast compared with the test data are correlated, and hence my question.

**Comment by josef-pkt** [comment]
I never used Prophet.
The main question is whether you are using a sequence of one-step ahead forecast or a varying horizon forecast starting at fixed date. Because I don't know prophet, I cannot tell from your code which is the case.

> If I understood you correctly, what you are trying to say is that independently if the model is capturing the data well, if there are serial correlation in my data and I generate a prediction for several forecast horizons, the residuals will have autocorrelation. Is this correct?

Yes, that has to be the case if there is serial correlation in the underlying data, which has to be the case to use time series forecasting. (*)
In the ARIMA model we can see the future impact of a shock in the impulse response function. 

(terminology: For forecast it is better to use prediction or "forecast error" instead of "residual" to emphasize that it's out of sample.
"residual" in the model is a sequence of one-step ahead prediction errors in the usual time series models.)

(*) If I have to be picky, then I would qualify that serial correlation is only a second moment, and in non-linear models it could be about other moments.

**Comment by bashtage** [comment]
Closing as answered. No action needed.
