### ISSUE TITLE
Erroe: fcast = mu + np.dot(arparams, endog[i:i+p]) 

### ISSUE THREAD

**Issue by Martin1937** [statsmodels/statsmodels#5258]
from statsmodels.tsa.ar_model import AR
import numpy as np

sample = np.array([0.46341460943222046, 0.46341460943222046, 0.39024388790130615, 0.4146341383457184, 0.4146341383457184, 0.4146341383457184, 0.3414634168148041, 0.4390243887901306, 0.46341460943222046, 0.4390243887901306])
model = AR(sample)
model_fit = model.fit(disp=0) 
output = model_fit.predict(start=10,end=12)
print(output)

The python code is as above, When I run this code, I got following error, 
  File "AR_test.py", line 8, in <module>
    output = model_fit.predict(start=10,end=12)
  File "D:\anaconda\envs\tensorflow\lib\site-packages\statsmodels\base\wrapper.py", line 95, in wrapper
    obj = data.wrap_output(func(results, *args, **kwargs), how)
  File "D:\anaconda\envs\tensorflow\lib\site-packages\statsmodels\tsa\ar_model.py", line 795, in predict
    predictedvalues = self.model.predict(params, start, end, dynamic)
  File "D:\anaconda\envs\tensorflow\lib\site-packages\statsmodels\tsa\ar_model.py", line 237, in predict
    out_of_sample)
  File "D:\anaconda\envs\tensorflow\lib\site-packages\statsmodels\tsa\ar_model.py", line 49, in _ar_predict_out_of_sample
    fcast = mu + np.dot(arparams, endog[i:i+p])
ValueError: shapes (6,) and (7,) not aligned: 6 (dim 0) != 7 (dim 0)

Could anyone suggest how to fix this issue? Thanks in advance.

**Comment by jtweeder** [comment]
I believe this has to do with the `maxlag` default setting in `AR.fit()`
```
round(12*(nobs/100.)**(1/4.))
```
Which in this case comes out to 7.   Using the example data I can get a return with no error if I set `maxlag` to anything 6 or less.  Looking through the test cases it looks like a `maxlag` is set every time `AR.fit()` is called.  

That would suggest that maybe that default `maxlag` should be floor of the calculation instead of the rounded value?  I cannot currently get to the full text of the referenced article in the `AR.fit()` docstring to see if that formula is suggested.

**Comment by josef-pkt** [comment]
This got lost without label.
temporarily prio-high to figure out what's going on.

**Comment by jbrockmendel** [comment]
@jtweeder is right.  Before the call to `add_trend` column 3 is constant, so `add_trend` silently changes trend from "c" to "nc", but that information doesn't make it back to the `AR` object, which still has `k_trend` set to 1.

If instead of calling `res = model.fit()` we do:

```
res = model.fit(trend="nc")
output = res.predict(start=10, end=12)

>>> print(output)
[0.44687422 0.45608137 0.47046381]
```

Note that `res.params` here matches `model_fit.params` the OP would have gotten.  The only difference is that `model.k_trend` (the fact that this is a model attribute is a different can of worms) attribute is correctly set to 0.

Two options for how to fix this:
- in `_stackX` pass `has_constant="raise"` to `add_trend`, and if it raises then tell the user to try passing `trend="nc"`
- have `add_trend` return an updated `k_trend`
