### ISSUE TITLE
summary() methods with arguments hard-coded

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5270]
GenericLikelihoodModelResults, GMMResults, QuantRegResults, and RegressionResults all have in their `summary` methods a block of code _almost_ identical to:

```
        if title is None:
            title = self.model.__class__.__name__ + ' ' + "Regression Results"

        # create summary table instance
        from statsmodels.iolib.summary import Summary
        smry = Summary()
        smry.add_table_2cols(self, gleft=top_left, gright=top_right,
                             yname=yname, xname=xname, title=title)
        smry.add_table_params(self, yname=yname, xname=xname, alpha=alpha,
                              use_t=self.use_t)
```

There are some small inconsistencies between the implementations that I'd like to confirm are intentional.

RegressionResults - no identical to above
QuantileResults - hardcodes alpha=.05 and use_t=True in the `smry.add_table_params` call.  The `alpha` in particular I think may be incorrect.
GMMResults - hard-codes use_t=False.  This is equivalent to use_t=self.use_t since use_t is set to False at the class level; is there a compelling reason to use the hard-coded version instead of the general case version?
GenericLikelihoodModelResults - hardcodes `use_t=False`.  Not clear why this should be preferred to self.use_t.

**Comment by josef-pkt** [comment]
ignoring a keyword is a bug, ie quantile result hardcoding 0.5 is a BUG

GenericLikelihoodModelResults hardcoded use_t=False is a BUG since use_t became a fit option.
I think is is because we did not adjust it when cov_type and use_t were implemented as fit arguments.

GMM use_t in summary is not be a bug, AFAICS, because there is not option for users to set use_t=True.
However, it should still use self.use_t so that if any GMM/GMMResults class overwrites use_t, then it needs to show up in the summary column headers.

(aside: use_t in summary is only for the column headers, AFAIR, and does not affect the numbers in the params table.)
