### ISSUE TITLE
DESIGN: Speed up innovations algorithm / filter with Cython or Numba?

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#5326]
The innovation algorithm added by @bashtage in #5042 can give us a way to compute the exact log-likelihood function of an ARMA process (see https://github.com/statsmodels/statsmodels/pull/5325/files#diff-8d4eb599f6121222f9a183e3a7205f9bR794).

I'm not sure, but it seems as though this approach could be a lot faster for ARMA models since it avoids a lot of the unnecessary operations implicit in the matrix-based state space models approach. This is especially true for SARIMA models with long seasonal effects, which we have gotten several questions about.

I know @bashtage mentioned that his existing functions can be trivially sped up by numba, which I think we're planning to make an optional dependency?

I can also easily write a Cython version, but I don't know if we want to head more into the numba direction, since the code is easier for most people to read / edit / debug?

**Comment by josef-pkt** [comment]
In general I think cython is more stable then numba, i.e. once the bugs are fixed, it's just C and we don't need to worry what the current version of JIT does. 
numba is more useful for developers that don't know cython well enough, and maybe in cases where we need more flexibility.

I think with both of you, Chad and Kevin, using cython in tsa, there is no problem putting additional filters into cython.

When I get around to Poisson time series processes, then I'd rather use numba than cython because it looks less painful for me.

**Comment by bashtage** [comment]
@ChadFulton Can this be closed now?

**Comment by ChadFulton** [comment]
I guess so - where we are right now, we have a Cythonized version of the innovations algorithm that works only for specified ARMA processes, in e.g. `innovations.arma_innovations`. It can not be used with an estimated autocovariance function like `stattools.innovations_algo` can, because it takes advantage of the specific form of the autocovariance matrix for stationary ARMA processes.

I think you mentioned in your original PR for `innovations_algo` and `innovations_filter` that Numba yielded significant performance improvements, and that still seems to me like a worthwhile improvement, but could be a different issue / PR.

**Comment by bashtage** [comment]
Sounds like this stays open.

**Comment by jbrockmendel** [comment]
PERF tag?
