### ISSUE TITLE
Lots of warnings in travis from scipy sparse matrix test

### ISSUE THREAD

**Issue by thequackdaddy** [statsmodels/statsmodels#5329]
If you've been following travis recently, we're getting a lot of warnings about numpy matrix vs. ndarray... there's over 20,000 of them.

The cause is one test (I think):

https://github.com/statsmodels/statsmodels/blob/ec672ec27dacb9778d524d564e50eb45306c63c0/statsmodels/stats/tests/test_corrpsd.py#L309-L339

**Comment by josef-pkt** [comment]
I think the best would be to set the global warnings filter to warn only once for `PendingDeprecationWarning`.
numpy will be using more of it for long term "discouraged" features.

If it's only one unit test, then we could catch it locally, but we want to use more scipy sparse without having to catch numpy warnings all the time.

I haven't tried to figure out what has changed so that we get all these warnings suddenly.

**Comment by josef-pkt** [comment]
The warnings are also on appveyor and even the full log file is truncated, at least it was yesterday when I wanted to look at some test failures.

**Comment by josef-pkt** [comment]
@thequackdaddy @bashtage 
Do we have somewhere an option to set the pytest filterwarnings?

```
[pytest]
filterwarnings =
                once::PendingDeprecationWarning
```

related usage question: 
Is there a way to force pytest to show the warnings immediately instead of at the end?
`pytest -s -v path-to-module`
still shows the warning list at the end, and I don't see how I can get the information about which unit tests caused the warning.

**Comment by bashtage** [comment]
Just add a filter here:

https://github.com/statsmodels/statsmodels/blob/master/setup.cfg#L10

```
ignore:the matrix subclass:numpy.matrixlib.defmatrix:PendingDeprecationWarning
```
