### ISSUE TITLE
Statsmodels 0.10.0

### ISSUE THREAD

**Issue by francesco91910** [statsmodels/statsmodels#5330]
Hi all,

Do you know when the statsmodels package version 0.10.0 will be released as final version?

Thanks,
Francesco

**Comment by josef-pkt** [comment]
I'm not sure.
I'm about a month behind in my work for statsmodels. So I would guess now that it will be more like end of November.

**Comment by jbrockmendel** [comment]
Is this estimate still in the ballpark?

**Comment by josef-pkt** [comment]
More likely the ball will be far out of the park.

I was thinking about it last weekend. 
I still will not have any serious amount of time to work on a release. GAM is essentially finished as a mergable first version except for a few loose ends. 
But personal/family time requirements are still large. My wife and I bought a house towards the end of summer that needed 3 or 4 months of repairs and renovation. We are moving during Christmas break.
GAM was 3 times as much work as I had expected plus organizing the home repairs and move took much more time than I had expected or hoped for.

The options are to either get a rush 0.10rc1 out with just the basic work necessary for a release, or delay the release to end of January, so I have at least 3 or 4 weeks to work on it.

We should have made a bug fix 0.9.1, because new versions always take longer than expected/planned.

In terms of wishful thinking, PRs that are close:
I have GAM, plus at least two PRs from the end of summer.
Kerby also has at least two PRs that need some review and maybe a bit of refactoring for the process PR.

**Comment by jbrockmendel** [comment]
OK, well consider this the traditional/periodic offer to help.  I'd be +1 on a 9.1 even if it were expected to be short-lived.

**Comment by jbrockmendel** [comment]
ping on the offer to help with smaller, more regular/frequent releases.

**Comment by bashtage** [comment]
The release candidate is now out.  See #5845 for installation instructions.
