### ISSUE TITLE
DFM - Univariate latent factors 

### ISSUE THREAD

**Issue by bryanchew94** [statsmodels/statsmodels#5338]
I have set up a model where there are two latent factors (k_factors = 2), and the DFM models these factors jointly as a VAR(1). However, I would like to model both latent factors separately as univariate AR(1) processes. 

From what I have seen, it is possible to force this issue for the errors, but not for the latent factors. How should I go about doing this? Thank you.

**Comment by ChadFulton** [comment]
> I have set up a model where there are two latent factors (k_factors = 2), and the DFM models these factors jointly as a VAR(1). However, I would like to model both latent factors separately as univariate AR(1) processes.

Yes, unfortunately the `DynamicFactor` model only allows a VAR transition for the factors right now.

> How should I go about doing this?

There are two ways you could do this: (1) you could modify the existing dynamic factor model to accommodate a non-VAR transition, or (2) you could set up a custom state space model.

The first option maybe seems more appealing, but it has the downside that since it is a generic class that supports many possibilities, it can be slightly more difficult to see how the new code has to fit in.

The second option shouldn't be too hard, although this depends somewhat on the specific model you have in mind.

In either case, please feel free to follow up on the mailing list with your code, and we'd be happy to help if you run into any problems.

**Comment by bryanchew94** [comment]
Hi Chad,

Thanks - I was able to set up a custom state space model with help from your user guide. On a side note, is it possible to run the model with nondiagonal state covariances? I would like to allow 2 latent factors (f1 and f2) to interact via a covariance term σ(f1,2).


![image](https://user-images.githubusercontent.com/43998030/47611889-ba04b900-daa9-11e8-8a42-d24dfa7a2435.png)

How should I go about inserting this covariance term into the model? Thank you so much!

**Comment by bryanchew94** [comment]
Thanks, it's working great after making the changes you suggested. Really appreciate the help!

**Comment by ChadFulton** [comment]
Great!
