### ISSUE TITLE
OLS predict error with list of floats

### ISSUE THREAD

**Issue by bt-** [statsmodels/statsmodels#5557]
I ran into an issue using statsmodels in a project I'm working on where passing the predict method of an OLS object a dictionary of lists with a single float in the lists causes an error.  The error occurs in v0.9.0, but this approach worked in v0.8.0.

I'm not sure if this is a minor bug or my misuse and I solved the issue in my project by always passing a DataFrame.

I'm posting a link to a [notebook](https://github.com/bt-/statsmodels_pred_test) where I tested all the combinations of arguments passed to predict for v0.8.0 and v0.9.0 in case this is a bug or someone else runs into a similar issue.

I think this is related to #4552 and #3611

**Comment by josef-pkt** [comment]
Yes, it looks like #4552, but the underlying problem is that patsy doesn't convert list to ndarray based on the traceback in your notebook.
Converting to a DataFrame is most likely a detour that needs to create an extra copy of the data.

You could try a dict of ndarrays or a dict of pandas Series instead of a dict of list.

Based on the change in #3611 / #4552 this is now by design, AFAIR, i.e. let patsy handle dicts which might make other options possible.

@thequackdaddy Any opinion on this?

**Comment by thequackdaddy** [comment]
I guess looking at the usecase, my humble opinion is that this might be more of a patsy issue. 

Before, a dict like that would be converted to a pandas data frame, then sent to patsy. Now, we just send the unaltered dict. 

My usecase is really that I need some kind of object with a `__getitem__` method that can return just a 1-d array of data from a large, on-disk file. I created custom object that inherits `dict` to do this. So I can be flexible. 

My view of options...

1. We could convert only dicts to pandas data frames. I could add some kind of checking to the `predict` method to tell if its just a plain old dict or something else. Something else, we send to patsy unaltered. Dicts, we first convert to data frames then send. 
2. We could convince patsy to handle lists as the value. 
3. We just don't support dicts with list values. 

I'm happy with any of the 3 options.
