### ISSUE TITLE
matplotlib backend issue on Mac OSX

### ISSUE THREAD

**Issue by mikkokotila** [statsmodels/statsmodels#5565]
The way `/Users/mikko/miniconda3/envs/talos_37/lib/python3.7/site-packages/statsmodels/multivariate/factor.py` handles matplotlib does not work for the case when user is on Mac OSX and on env/conda env. 

Right now

```
try:
    import matplotlib.pyplot
    missing_matplotlib = False
except ImportError:
    missing_matplotlib = True

if not missing_matplotlib:
    from .plots import plot_scree, plot_loadings
```
But instead we need to have: 

```
try:
    import matplotlib.pyplot
    missing_matplotlib = False
except (RuntimeError, ImportError):
    missing_matplotlib = True

if not missing_matplotlib:
    from .plots import plot_scree, plot_loadings
```
Let me know if there is any issue with this, and I can make a PR accordingly.

**Comment by bashtage** [comment]
Why are getting a Runtime Error?  That shouldn't happen and indicate some
other problem

**Comment by mikkokotila** [comment]
It is indeed a different problem. It relates with a [known matplotlib issue](https://matplotlib.org/faq/osx_framework.html) for Mac users but yields the same situation i.e. no working matplotlib on the local machine.

**Comment by bashtage** [comment]
This seems like a matplotlib, virtualenv or conda issue. Isn't the solution is not to install matplotlib in the env, in which case the ImportError suffices.

**Comment by mikkokotila** [comment]
That's right, but for python workflow the best practice (perhaps also most common?) is to either use env or conda env. So for a package to say "don't do that so you can use our package" IMO is not reasonable.

**Comment by bashtage** [comment]
The challenge is that statsmodels is absolutely riddled with this pattern since MPL is an optional dependency. 

https://github.com/statsmodels/statsmodels/search?q=import+matplotlib&unscoped_q=import+matplotlib

It isn't reasonable to fix all of these due to a bug in a different package.  It is also problematic for statsmodels maintainer since RuntimeError could make other issues in testing. For example, support the Travis config is bad -- this happens a lot, and a RuntimeError starts being raised.  Then none of the MPL tests will be run on Travis, which means breaking changes in MPL won't be fixed until some random reports come in. 

Why won't venv/conda fix this issue?

**Comment by bashtage** [comment]
Does 

```
export MPLBACKEND=agg
```

work when you run a virtual env with Matplotlib installed?

**Comment by mikkokotila** [comment]
That's amazing, it does work. 

I understand your rationale above, thanks a lot for clarifying. 

> Why won't venv/conda fix this issue?

I'm not sure if I understand the problem properly, but I had thought that this is a matplotlib (as nothing like it happens with any other packages that I've ever used). I think it's a really great question why matplotlib is not doing anything about this. To which a very short answer may be that mac osx is not "really" supported. 

Thanks again.
