### ISSUE TITLE
Why python prompt 'AR coefficients are not stationary' and 'MA coefficients are not invertible' when I use higher order of p,q. And the value of p,q is automatically obtain.

### ISSUE THREAD

**Issue by SmileHergo** [statsmodels/statsmodels#5629]
#### Describe the bug

![image](https://user-images.githubusercontent.com/47837761/57216162-aa01ff00-7021-11e9-9338-2dad6c244c10.png)
![image](https://user-images.githubusercontent.com/47837761/57216178-b8501b00-7021-11e9-8bfe-78e929d4387c.png)
![image](https://user-images.githubusercontent.com/47837761/57216187-bdad6580-7021-11e9-9990-dee28efa56f8.png)

Because I am a rookie, so unreasonable, please correct me. Thank you very much!

**Comment by bashtage** [comment]
The model can only be fit for parameters that are consistent with covariance stationarity. The method for producing starting values does not satisfy this, and so it doesn't know what to do. You can either not use the problematic combination of p & q or you can pass some other starting values yourself.

**Comment by SmileHergo** [comment]
@ChadFulton

**Comment by SmileHergo** [comment]
@ChadFulton  please help!!!

**Comment by ChadFulton** [comment]
There is not much more to say other than what @bashtage already wrote. In particular, you can pass your own starting parameters, for example setting the "bad' values to zeros.

The only other thing I can suggest is that you install the version of Statsmodels from Github (the "master" branch) and then use the `SARIMAX` class instead of `ARIMA`. Then it will automatically replace the "bad" values with zeros.

Note that this does not mean that the estimator is likely to be any good with those starting parameters, it just won't raise an error.

**Comment by SmileHergo** [comment]
Thank you very much ! I will try this way you suggested. @ChadFulton
