### ISSUE TITLE
DOC: statsmodels.github.io repo 

### ISSUE THREAD

**Issue by thequackdaddy** [statsmodels/statsmodels#5849]
cc @bashtage 

So the tags that we use for the main repo start with a "v" (e.g., "v0.9.0", "v0.10.0rc2"). However in the stats models website, there is no "v" prefix. Do we care about keeping the doc repo with the same v prefix? 

Also, the Doctr code we have builds the release candidate docs and pushed them to stable. Is that ideal? We also made a specific 0.10.0rc2 folder. I'm not sure if we really want to archive RC docs. I'm thinking about deleting them. 

Lastly the way we have the docs done still bothers me. I'm not that good with HTML/css but it would be nice to have something simpler, with fewer pages overall and a more modern theme. I've played with that, but not gonna lie... my sense of design and style is pretty terrible. I still wear white after Labor Day.

**Comment by thequackdaddy** [comment]
I should also mention that the full docbuild is over 100 mb. I think the biggest cause of that is the same HTML header/footer is duplicated 10,000+ times and there's a good amount of waste in that.

**Comment by bashtage** [comment]
I don't mind if the v is there or not. The v is required for versioneer to get the version right. Presumably most of the files are identical across builds and so the git push should be pretty small.

**Comment by bashtage** [comment]
Are for fewer pages, it would be good if each class could be generated on a
single page instead of function per page. No idea how this is done.

**Comment by bashtage** [comment]
The alterrnative is to be selective about methods that get documented.

**Comment by thequackdaddy** [comment]
I think our issue is that we use autosummary and reference the individual classes that we want documented. I think there are some sphinx templates in docs/source/_templates/autosummary that drives this.

I think if we move away from autosummary and individually set up what methods to doc when, we can have the same information on fewer, but larger pages.

Alternatively, we could experiment with autosummary to have it document each method on the same page instead of below. Let me play with that. 

I guess my issue is that (almost?) every html page actually has a version number in it, so every page has to be updated by sphinx/doctr each push. Another idea would be make sure that the version number is its own line in the html file so its easy for git to just update those lines. 

Each individual new commit grows the statsmodels.github.io repo by a mb or so. Do 100 of those and you are talking about real space.

The repo size is close to 1 GB currently. Its fine today, but I would argue its something we should make sure doesn't get too unwieldy.

**Comment by bashtage** [comment]
Git is line-by-line so a single line modification on many pages still a smallish commit (I hope).  How but is the website repo? ```git gcgit count-objects -vH ``` From: Peter QuackenbushSent: Saturday, June 8, 2019 8:39 PMTo: statsmodels/statsmodelsCc: Kevin Sheppard; MentionSubject: Re: [statsmodels/statsmodels] DOC: statsmodels.github.io repo (#5849) I think our issue is that we use autosummary and reference the individual classes that we want documented. I think there are some sphinx templates in docs/source/_templates/autosummary that drives this.I think if we move away from autosummary and individually set up what methods to doc when, we can have the same information on fewer, but larger pages.Alternatively, we could experiment with autosummary to have it document each method on the same page instead of below. Let me play with that.I guess my issue is that (almost?) every html page actually has a version number in it, so every page has to be updated by sphinx/doctr each push. Another idea would be make sure that the version number is its own line in the html file so its easy for git to just update those lines.Each individual new commit grows the statsmodels.github.io repo by a mb or so. Do 100 of those and you are talking about real space.The repo size is close to 1 GB currently. Its fine today, but I would argue its something we should make sure doesn't get too unwieldy.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by bashtage** [comment]
Git is line-by-line so a single line modification on many pages still a smallish commit (I hope).  How but is the website repo? `git gc && git count-objects -vH`

**Comment by bashtage** [comment]
> The repo size is close to 1 GB currently. Its fine today, but I would argue its something we should make sure doesn't get too unwieldy.

I suppose there is no reason we couldn't run BFG and clear out all of the history of it except the tips of the branches that we need to keep.  This should reduce the size a good bit.

**Comment by bashtage** [comment]
I also suspect that the image files and rendered notebooks may be making it rather large. IIRC matplotlib doesn't make any guarantee that the same code produces bit identical pngs.

**Comment by bashtage** [comment]
Actual repo is only 435MiB :-)

**Comment by bashtage** [comment]
@thequackdaddy Between your numpydoc branch and changing cache_readonly to use pandas's version, I think the docs are pretty much right. See, e.g, 

http://www.statsmodels.org/devel/generated/statsmodels.regression.linear_model.OLSResults.html?highlight=olsresults#statsmodels.regression.linear_model.OLSResults

I separated out Properties from Attributes, which often come from the docstring.

**Comment by thequackdaddy** [comment]
Yes, that does look much nicer. Very nice work! 

Not sure its material, but should we keep/delete the rc2 build in the docs folder? Not sure we really need that. I suppose we should also add v0.10.1 to the dropdown options.

**Comment by bashtage** [comment]
I think rc2 should go, and 10.1 should appear. 

Still needs a redesign so that it works well on a phone or ipad.

**Comment by bashtage** [comment]
I'm going to clear out the history soon, and remove unnecessary RC directories.

**Comment by bashtage** [comment]
I followed the instructions https://gist.github.com/stephenhardy/5470814 and the repo size has halved.

**Comment by bashtage** [comment]
I cleaned the repo which reduced it by half.  I think we are OK for now with the theme.
