### ISSUE TITLE
Use SARIMAX for forecast

### ISSUE THREAD

**Issue by NN66** [statsmodels/statsmodels#6043]
I build model and save her. Then I want use this model for forecast new dataset. I test how it is work
> from statsmodels.tsa.statespace.sarimax import SARIMAX
> model = SARIMAX(history, order=(7, 1, 1), seasonal_order=(1, 1, 1, 7))

> model_fit = model.fit(disp=False)

>  modelB = SARIMAX(history[100:], order=(7, 1, 1), seasonal_order=(1, 1, 1, 7))

   

> resB = modelB.smooth(model_fit.params)

    

> y = model_fit.predict(len(history), len(history), typ='levels')

  

>   y2 = resB.predict(len(history[100:]), len(history[100:]), typ='levels')`

I expect that y == y2
because history and history [100:] have more then 7 equal data on tail
Why is it not true?

**Comment by ChadFulton** [comment]
Please post a small runnable example so that we can try to replicate the problem.

Note: `typ='levels'` is not an argument that is used by the `predict` method of SARIMAX.

**Comment by NN66** [comment]
Example

> from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_squared_error
from math import sqrt
X = [1.0, 3.0, 5.0, 8.0, 2.0, 3.0, 2.0, 1.0, 4.0, 5.0, 9.0, 2.0, 3.0, 1.0, 2.0, 3.0, 6.0, 8.0, 3.0, 3.0, 1.0, 2.0, 6.0, 10.0, 16.0, 4.0, 6.0, 4.0, 2.0, 6.0, 10.0, 16.0, 4.0, 6.0, 4.0, 3.0, 7.0, 11.0, 17.0, 5.0, 5.0, 3.0, 3.0, 7.0, 16.0, 17.0, 5.0, 5.0, 3.0, 4.0, 9.0, 18.0, 24.0, 7.0, 7.0, 6.0]
train = X[:-1]
#train model
model = SARIMAX(train, order=(7, 1, 1), seasonal_order=(1, 1, 1, 7))
model_fit = model.fit(disp=False)
#model initialization  for use for forecast new dataset
modelB = SARIMAX(train[-10:], order=(7, 1, 1), seasonal_order=(1, 1, 1, 7))
resB = modelB.smooth(model_fit.params)
#expectation y == y2
y = model_fit.predict(len(train), len(train))
y2 = resB.predict(len(train[-10:]), len(train[-10:]))
print('>predicted model_fit=%.3f, predicted modelB=%.3f, expected=%.3f' % (y, y2, X[-1]))

modelB use params model_fit and 7 values dataset. I expect that y == y2. Why is it not true?

In the real task I train model on March and use on June month. I have not May data. I try use fixed model parametrs

**Comment by ChadFulton** [comment]
> modelB use params model_fit and 7 values dataset. I expect that y == y2. Why is it not true?

There are two reasons that it's not true.

1. First, the forecast in your example depends on at least 22 observations (because you're taking seasonal differences and including 1 seasonal lag, and also taking first differences). If you include fewer observations than that (as you do in `modelB`), then your results will depend on the prior information used by the Kalman filter (where here the prior is the unconditional distribution of the state space form).

2. Your model includes moving average terms, which are unobserved. These have to be estimated by the model and that estimate generally depends on even more data in the sample than what I mentioned in part (1).

So for example, you do get the same prediction in the following case:

```python
model = SARIMAX(train, order=(7, 1, 0), seasonal_order=(1, 1, 0, 7))
model_fit = model.fit(disp=False)
modelB = SARIMAX(train[-22:], order=(7, 1, 0), seasonal_order=(1, 1, 0, 7))
resB = modelB.smooth(model_fit.params)

y = model_fit.forecast()
y2 = resB.forecast()

print(y, y2)
```

but if you use less data for `modelB` or if you include moving average terms, then you will need even longer common samples for the forecasts to match.
