### ISSUE TITLE
Hand calculated forecast does not match with model's forecast output

### ISSUE THREAD

**Issue by Nirmal-Neel** [statsmodels/statsmodels#6099]
Hi all,

I am using one Seasonal ARIMA model with (1,1,0)x(0,0,1)4 parameter. But I see the hand calculated forecast is not matching with the model's forecast result.

Following is the code snippet

```python
from statsmodels.tsa.statespace.sarimax import SARIMAX
mod = SARIMAX(data,order=(1,1,0),seasonal_order=(0,0,1, 4))
results = mod.fit()

phi = results._params_ar[0] # -0.5494064434384048
THETA = results._params_seasonal_ma[0] # 0.9993750478844912
y = results.model.endog # array([,.......,...., [16.02], [11.61]])
err = results.resid.values # array([.........,...., 1.36566471,  1.08682365, -0.46994267, -2.1512728 ])

forecast_py = y[-1] + (phi*y[-1]) - (phi*y[-2]) + (THETA*err[-4])
res=results.forecast()

print(forecast_py) # [15.39769366]
print(res.values) # [15.33289151]
```
Since in my case `trend=None`, so no constant term added to the manual calculation.

Am I missing something in the calculation? Could you help me in finding the reason please?

**Comment by ChadFulton** [comment]
This is because the estimate of the error term is not identically equal to the forecast residual, and the difference is due to the effect of the "initialization" of the Kalman filter.

(Basically, the filter iterates over each observation, and at each iteration it uses information from the previously filtered observations. Initialization is how to start the filter for the very first observation. Bayesians would call this a prior.)

When `phi` or `theta` is very close to one, it can take a large number of observations for the influence of initialization to fade completely (because the process has a lot of persistence), and in your example, theta = 0.999.

**Comment by ChadFulton** [comment]
In case it is unclear why initialization is necessary, consider the first `s` observations of the dataset. These observations do not have a residual from `s` periods ago to use in the formula that you have used in your post, and so we need to make some kind of assumption (or prior) about those first `s` error terms. That assumption is what the initialization is.

**Comment by Nirmal-Neel** [comment]
Thanks for explaining this! For some models the hand calculated forecast matches with the model's forecast. For example, in the above example if I use seasonal_order =(1, 0,1, 4), then I get the same forecast.

What changes need to be done in the formula so that I can get the same forecast?

**Comment by ChadFulton** [comment]
If your estimated parameters are not so close to one, then the two
approaches will match with less data. That is probably why some models have
better matching forecasts than other models.

There’s no simple way that I know to write down a formula that will match
the optimal forecasts produced by the Kalman filter. The best you can do is
write down the Kalman filtering equations.

**Comment by ChadFulton** [comment]
Closing since answered, but please feel free to follow up with questions.
