### ISSUE TITLE
ARMAResults are inconsistent with parametric model results

### ISSUE THREAD

**Issue by veager** [statsmodels/statsmodels#6178]
For ARMA model, the [`results.fittedvalues`](http://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARMAResults.html#statsmodels.tsa.arima_model.ARMAResults) attribute can easily get the predicted values, while the `results.params` attribute can get the model parameters. 

However, I found that the predicted values calculated based on the equation as the following were inconsistent with `results.fittedvalues`.

Taking ARMA(2,2) as an example,
`X(t) = a0 + a1 * X(t-1) + a2 * X(t-2) + e(t)- b1 *  e(t-1) - b2 * e(t-2)`
The `X(t)` are true values; `e(t)` are residuals from `results.resid`; a0, a1, a2, b1, b2 are parameters from `results.params`.

So, the predicted values can be calculated according `a0 + a1 * X(t-1) + a2 * X(t-2) - b1 *  e(t-1) - b2 * e(t-2)`, but they are  inconsistent with `results.fittedvalues`.

I wonder to know why it happened, I would be grateful if anyone helps me understand it.

**Comment by josef-pkt** [comment]
The mean is subtracted first.
ARMA is applied to the residual of series minus constant, trend, exog part

e.g. https://groups.google.com/d/msg/pystatsmodels/lMEz0VFerOk/beBFmLgsBwAJ

**Comment by bashtage** [comment]
This happens since the predicted values efficiently use the limited data available since e(-1) and e(-2) are not in your data.  This is standard in any ARMA model estimated using MLE. You can't just take 2 errors and 2 obseved values and get the next fitted since the in-sample fitted vaue at location (t) is produced using a proceedure that is "as-if" the best AR(t-1) was used.

**Comment by veager** [comment]
Hi, @josef-pkt and @bashtage, thanks for the quick replies very much! 

In this situation, how can I use the estimated ARMA model to predict when I have some new data, just like using the SVR model. For example, I want to use `X(1)~X(100)` to estimate ARMA model (same as using training data to train SVR), and use the estimated ARMA model  to predict `X(101)~X(120)` (same as using trained SVR model to predict testing data). 

It is well known that the `results.predict` can achieve multi-step prediction and predict `X(101)~X(120)`  directly. While I want to use the estimated ARMA model based on `X(1)~X(100)` and the observed `X(101)` to predict  `X(102)`.

It seems that I can only take `X(101)` and `X(1)~X(100)` together and then use `X(1)~X(101)` to re-estimate the ARMA model. It will change the parameters and the predicted values every time. 

I wonder if it has some way to achieve that?

**Comment by ChadFulton** [comment]
@veager you might find the following example useful: https://www.statsmodels.org/devel/examples/notebooks/generated/statespace_forecasting.html, In particular, the "Cross validation" section.

Note that this example requires that you have the development version of Statsmodels installed (i.e. this feature is not available in v0.10), and that you use `sm.tsa.SARIMAX` instead of `sm.tsa.ARIMA`.

**Comment by veager** [comment]
> @veager you might find the following example useful: https://www.statsmodels.org/devel/examples/notebooks/generated/statespace_forecasting.html, In particular, the "Cross validation" section.
> 
> Note that this example requires that you have the development version of Statsmodels installed (i.e. this feature is not available in v0.10), and that you use `sm.tsa.SARIMAX` instead of `sm.tsa.ARIMA`.

Thanks a lot for your helpful reply. 
What a great new feature! Looking forward to the stable version.
