### ISSUE TITLE
update Holtwinters model during prediction 

### ISSUE THREAD

**Issue by DonBeo** [statsmodels/statsmodels#6183]
Hi,

My understanding is that the HW model estimates its params with the training data.  It later uses them for prediction using an iterative procedure like: 
`x(t+1) = f(x(t))`

Now apart from `x(0)` all the other points `x(t)` are generated by the model based on the estimated params.

I would find useful to have an option to pass real observed  data during prediction. 

For example the predict example should get a `real_data` array as input:
`hw.predict(start, stop, real_data)`
and the algorithm should use the passed values for prediction: 
`x(t+1) = f(real_data(t))`

**Comment by ChadFulton** [comment]
We don't have a feature like this for the HW model. However, something like this may be added soon for linear exponential smoothing models in #6179.

Once that PR gets merged, there will be a new model class that will have the `apply`, `extend`, and `append` results methods that are described for SARIMAX models in the example notebook https://www.statsmodels.org/devel/examples/notebooks/generated/statespace_forecasting.html. See especially the section on "Cross validation".

Just to make a quick note, the situation is a little more complicated than you describe. That's because what the prediction `x(t+1)` actually depends upon is the estimated state vector `s(t)`, and `s(t)` depends on the entire history of the data, `x(0), x(1), ..., x(t)`. This means that we need different procedures depending on the relationship of `real_data` to the originally given `endog`. For example, is it just the next set of observations of `endog`, or does it represent a completely different dataset?

**Comment by ChadFulton** [comment]
Closing as answered, but please still feel free to follow up with more comments if you like.
