### ISSUE TITLE
Extremely high resid values in the initial period of SARIMAX

### ISSUE THREAD

**Issue by alexsmartens** [statsmodels/statsmodels#6212]
#### Describe the bug

The residual plot in the initial period of the SARIMAX model does not seem to be correct. For comparison I plotted the residuals produced by "the same" SARIMA models in statsmodels and R.
![residuals](https://user-images.githubusercontent.com/26261714/67584049-d407c480-f71a-11e9-84aa-197662f89462.png)

#### Code Sample, a copy-pastable example if possible

data: 
monthly-milk-production-pounds-p.csv: monthly milk production in pounds per cow from 1962 till 1975 by Rob Hyndman

```python
df = pd.read_csv("monthly-milk-production-pounds-p.csv")
df.columns = ["month", "value"]

order = (0, 1, 0 )
seasonal_order = (0, 1, 1, 12)
sarima_mod = sm.tsa.SARIMAX(df["value"], order=order, seasonal_order=seasonal_order)
sarima_res = sarima_mod.fit()

fig, ax = plt.subplots(1, 1)
ax.set_title("Residuals")
ax.plot(sarima_res.resid, label="Python", linestyle=":", alpha=.8)
```

#### Expected Output

As the residuals of the consequent periods produced by statsmodels match the ones by R, I would expect them to be similar along all the time points 

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

```
Statsmodels
===========

Installed: 0.10.1
```

</details>

**Comment by bashtage** [comment]
These are correct since they are presample values and so your seasonal order hasn't kicked in. The R ones are clearly all 0s, which aren't residuals.

**Comment by bashtage** [comment]
Plot the first few residuals against your diffferenced data.  They should be similar.

**Comment by alexsmartens** [comment]
This is what I thought, but somehow their first 12+1 values are not exactly 0:

```
R             | Python
0.333882 | 578.3
0.173716 | 31.5
0.129444 | 18.6
0.129289 | 37.2
0.146735 | 48.2
0.116019 | -6.6
0.025994 | -78.8
-0.01512 | -40.3
-0.0246   | -11.8
-0.03145 | -9.8
-0.03375 | -5.4
-0.38201 | 10.3
-2.09111 | -271.451
```

I mean, I agree that they should theoretically be zeros, just saw these results and decided to double check.

What number of the initial residuals should I ignore to properly compare models with SSE?
Is it **S + 1** where S is number of periods?

**Comment by alexsmartens** [comment]
Here are the residuals plotted against the nonseasonal differences data:
![residuals2](https://user-images.githubusercontent.com/26261714/67593893-294ed080-f731-11e9-8a5d-dcb099abe267.png)

@bashtage, you are right the values are similar. However the points **0** and **12** have some unexpected spikes. What do you think?

**Comment by bashtage** [comment]
I assume this is due to the seasonal component of the model. You shouldn't
trust these. They are part of the initialization of the KF and are affected
by the prior variance.

**Comment by ChadFulton** [comment]
> You shouldn't trust these. They are part of the initialization of the KF and are affected
by the prior variance.

I think this comment by @bashtage is the main point. Probably we should report them as `NaN` instead, because for the first 13 observations (in this case) there is a diffuse component to the forecast error (i.e. infinite variance).

-------

> What number of the initial residuals would you suggest to ignore to properly compare models with SSE?
Is it S + 1 where S is the number of periods?

You can do one of two things.

1. If you are using version 0.10, you can use the value of `sarima_mod.loglikelihood_burn`, which is based on the number of diffuse states. In this case, `sarima_mod.loglikelihood_burn = 13`, which is the number of periods you should ignore.

2. If you want to upgrade to the development version, then you add the argument `use_exact_diffuse=True` to the SARIMAX constructor, and then you can use the value of `sarima_res.nobs_diffuse` to get the exact number of periods to ignore. In this case, we also have `sarima_res.nobs_diffuse = 13`.

-------

Here's what's going on in Statsmodels:

Basically, because an SARIMA model with integration is non-stationary, there's no "correct" starting level for the state to initialize the Kalman filter at (i.e. prior to seeing any of the data). There are several approaches to dealing with this problem, and in Statsmodels we use diffuse initialization, so that the state vector is N(0, kappa) with kappa going to infinity.

The key, though, is that the initial state vector is centered at zero. So ignoring the variance for a moment, the point one-step-ahead forecast for the first observation will be 0, and the forecast error will be equal to the first observation. That's the big spike you see in the first residual.

Because of the seasonal differencing, the Kalman filter can't "figure out" the level until it has processed a full season, and then here it actually needs one more datapoint than that because of the non-seasonal differencing.

-------

I took a look at what Stata returns (Stata also uses diffuse initialization), and its residuals are identical to ours, except that it returns missing values for the first 13 observations.

For R, I guess they are using de Jong's augmented Kalman filter for the diffuse initialization (although I found no reference to it, the `Delta` argument to `stats::KalmanLike` makes me think it's likely, although confusingly they also allow setting a value for kappa while de Jong sends it to infinity), in which case they may be reporting what Durbin and Koopman refer to as v_{\delta, t} in section 5.7.2.

Ultimately, I think there is no evidence that R is doing something better here, and it is possible that they are doing something worse. Although again, we should possibly be reporting `NaN`s for these periods to avoid confusion.

**Comment by alexsmartens** [comment]
@ChadFulton, thanks for your exhaustive answer.
The idea is clear, I'm closing the issue
