### ISSUE TITLE
Abrupt behaviour of get_prediction with different indices

### ISSUE THREAD

**Issue by alexsmartens** [statsmodels/statsmodels#6302]
#### Describe the bug

Prediction methods produce different outcomes on series with the same values but different indices. To illustrate what I mean I will provide a few examples of the same data with different indices

#### Code Sample, a copy-pastable example if possible

```python
endog_train = pd.Series([1, 0, 3, 6, 5, 4, 7, 6, 9, 12], index=np.arange(0, 10))
endog_test = pd.Series([11, 12, 11, 14, 15, 18, 17], index=np.arange(10, 17))

mod = sm.tsa.SARIMAX(endog_train, order=(1, 0, 0), trend='c')
res = mod.fit(disp=False)

res = res.append(endog_test, refit=False)
t_delta = endog_train.index[1] - endog_train.index[0]
pred_res_all = res.get_prediction(start=endog_train.index[-1], end=endog_test.index[-1] + t_delta, full_results=True)
pred_mean = pred_res_all.predicted_mean

fig, ax = plt.subplots()
plt.plot(endog_train, alpha=.2, label="Train")
plt.plot(endog_test, alpha=.2, label="Test")
plt.plot(pred_mean, alpha=.4, label="Prediction", color="blue")

plt.title("Start idx = {}".format(endog_train.index[0]))
plt.legend()
```

![Figure_0](https://user-images.githubusercontent.com/26261714/69978500-9442b280-14fa-11ea-9107-f68252909230.png)

Change indices as follows:
```
endog_train = pd.Series([1, 0, 3, 6, 5, 4, 7, 6, 9, 12], index=np.arange(1, 11))
endog_test = pd.Series([11, 12, 11, 14, 15, 18, 17], index=np.arange(11, 18))
```
![Figure_1](https://user-images.githubusercontent.com/26261714/69978762-00bdb180-14fb-11ea-9fb7-a5b1e9186eb8.png)
Change indices as follows:
```
endog_train = pd.Series([1, 0, 3, 6, 5, 4, 7, 6, 9, 12], index=np.arange(2, 12))
endog_test = pd.Series([11, 12, 11, 14, 15, 18, 17], index=np.arange(12, 19))
```
![Figure_2](https://user-images.githubusercontent.com/26261714/69978813-1632db80-14fb-11ea-83db-edfec55547f0.png)
Change indices as follows:
```
base = dt.datetime.today()
dates_train = [base + dt.timedelta(seconds=x) for x in range(10)]
dates_test = [dates_train[-1] + dt.timedelta(seconds=1) + dt.timedelta(seconds=x) for x in range(7)]
endog_train = pd.Series([1, 0, 3, 6, 5, 4, 7, 6, 9, 12], index=dates_train)
endog_test = pd.Series([11, 12, 11, 14, 15, 18, 17], index=dates_test)
```
![Figure_date](https://user-images.githubusercontent.com/26261714/69978863-29de4200-14fb-11ea-8c28-9448b5050325.png)

#### Expected Output

I would expect the figures in these examples to be the same

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

`0.11.0.dev0+628.g17f7c3481`

**Comment by ChadFulton** [comment]
Your first and last setups each use supported indexes, and they give the same answer, but we don't support the indexes in your second and third setups. We issue a warning if the index is not supported saying that it will not be used, so the only bug there would be if you aren't getting that warning on model instantiation?

-----------

**Details**

The unsupported indexes are `Int64Index`es, and we only support one very special case of `Int64Index`es: when they are of the form `0, 1, 2, ..., n-1, n`. This is because the general case of `Int64Index` could have any pattern - e.g. `pd.Int64Index([0, 3, -1, 6])` is a possibility - and so there is no universal way to expand these beyond the end of the sample. We could potentially add support for the cases you give here (since they are monotonic increasing / full `Int64Index`es), and I'd be happy to review a PR to do that, but it's not a high priority for me to implement.

Instead, our basic index that is already fully supported is the `RangeIndex`. For this index type, it is straightforward to extend it beyond the end of the sample. One thing to note is that because this is the non-date index concept that we really are interested in supporting, we interpret integer arguments for `start` and `end` as integer *locations* in the index, not index *values*. So to start at the beginning of the sample, you would use `start=0` and not `start=endog.index[0]`.

We have a special case to allow passing date arguments, if the index is a `DatetimeIndex` or `PeriodIndex`. In this special case, strings or `datetime` objects are interpreted as index values.

**Comment by alexsmartens** [comment]
> Your first and last setups each use supported indexes, and they give the same answer, but we don't support the indexes in your second and third setups. We issue a warning if the index is not supported saying that it will not be used, so the only bug there would be if you aren't getting that warning on model instantiation?

The warnings are there. I did not pay proper attention to them.
I got the idea now, thanks

**Comment by bashtage** [comment]
Would probably be better to raise rather than warn.  Warnings, while feeling nice, are pretty easy to miss depending on how code is run, and increase the chance of _unexpected_ (and undetected) results.

**Comment by alexsmartens** [comment]
> Would probably be better to raise rather than warn. Warnings, while feeling nice, are pretty easy to miss depending on how code is run, and increase the chance of unexpected (and undetected) results.

Agree

**Comment by ChadFulton** [comment]
That would be pretty easy to implement - we can raise an exception in `get_prediction` if there is no supported index and `out_of_sample` is greater than zero. The deprecation strategy is the only tricky part.
