### ISSUE TITLE
Time difference in fitting of VAR and VARMA model

### ISSUE THREAD

**Issue by enthu-sh** [statsmodels/statsmodels#6519]
I am trying VARMA model on a data of about 80000 samples with 10 features  with p=50 and q=0 but it is taking too much time to build the model. This was running even after an hour with maxiter=1. The code I am using is:

     from statsmodels.tsa.statespace.varmax import VARMAX
     modelVARMA = VARMAX(data, order=(50,0))
     resultsVARMA=modelVARMA.fit(maxiter=1)

I also tested VAR model with p=50 and it gave the model quickly. 

I read it at link https://github.com/statsmodels/statsmodels/issues/3825 that it is because of the difference in the fitting of models in VARMA and VAR. 

But VARMA is way too slow. I could not find any parameter settings that can be adjusted to get fast results from VARMA.

**Comment by ChadFulton** [comment]
That's correct - `VARMAX` will be slower at fitting parameters, and it will be much slower for a model with `nobs` or `order` (i.e. `p`) large. With 10 features, I would assume that `VARMAX` will be quite slow with even `p=5`.

This is because `VARMAX` uses numerical methods to maximize the likelihood function, and with `n` features and `p` lags, there will be `(n**2 * p) + (n * (n + 1) / 2)` parameters. `VAR` uses ordinary least squares, which is much faster.

**Comment by bashtage** [comment]
Sounds like this question has been answered as well as can be done.
