### ISSUE TITLE
Unexpected results for OLS

### ISSUE THREAD

**Issue by karasjoh000** [statsmodels/statsmodels#6527]
I created a notebook which you can find here: https://colab.research.google.com/drive/1isvaFC0_KtQPD47jI8HWkkOR4KLUKM_v#scrollTo=08_6NaLb0-RO

log Money demand was regressed on log GDP and log interest rate. The model shows there is a positive relationship between the interest rate and money demanded however this is not the case in economic theory. Is this an issue with the OLS regression function? 
TB3MS - interest rate
RGDP - gdp

Here is the regression summary: 

```shell
                           OLS Regression Results                            
==============================================================================
Dep. Variable:                     M1   R-squared:                       0.743
Model:                            OLS   Adj. R-squared:                  0.741
Method:                 Least Squares   F-statistic:                     336.7
Date:                Wed, 19 Feb 2020   Prob (F-statistic):           1.86e-69
Time:                        05:12:28   Log-Likelihood:                 88.396
No. Observations:                 236   AIC:                            -170.8
Df Residuals:                     233   BIC:                            -160.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.1906      0.205     15.584      0.000       2.787       3.594
TB3MS          0.0071      0.009      0.815      0.416      -0.010       0.024
RGDP           0.4999      0.023     21.593      0.000       0.454       0.545
==============================================================================
Omnibus:                       83.986   Durbin-Watson:                   0.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               13.169
Skew:                          -0.097   Prob(JB):                      0.00138
Kurtosis:                       1.859   Cond. No.                         165.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
```

**Comment by josef-pkt** [comment]
It's not a question for statsmodels.
OLS is fine, the question is how to specify the model and what the theories (plural) say, especially over different time horizons.

AFAIR, there is a large literature on money demand, and several theories about it.

The main point here, If you do the regression in (log) levels, then OLS fits the long term trend. Long term trends may differ from short term behavior, e.g. with technological progress in finance industry and changes in transaction cost..

In your regression, TB3MS is not statistically significant, the confidence interval is pretty wide and has 0 inside and not even close to the edge of the confidence interval.

(Aside
This might be a good excercise for `dfbeta`, i.e. drop some observations and see how much the parameter estimate changes. http://www.statsmodels.org/stable/generated/statsmodels.stats.outliers_influence.OLSInfluence.html 
)

**Comment by karasjoh000** [comment]
Does stata automatically drop observations that are "outliers"? Other classmates that used stata got negative relationship results.

**Comment by josef-pkt** [comment]
No, Stata doesn't drop observations because they might be outliers.

Stata drops observations in some cases in Logit (IIRC) and drops variables if there is perfect collinearity. None of those reasons should apply in this case.

For regular cases like this statsmodels, Stata and R agree to a high precision. 
You need to check that the data used in the regression is really the same, mainly that the preprocessing of the data is the same.
You can also verify that df_resid and other statistics agree between Stata and statsmodels. They should.

(There are a few of the extra results statistics where the definitions do not agree across all packages, maybe aic in the OLS case.)

**Comment by karasjoh000** [comment]
So when the graph is plotted against fitted values it looks like: 

```python
fig, ax = plt.subplots(figsize=(20,10))
ax.plot(q_X.RGDP, q_lnM1, 'o', label="data")
ax.plot(q_X.RGDP, q_M1_OLS_results.fittedvalues, 'o', label="fit")
#ax.plot(q_X.RGDP, q_M1_OLS_results.fittedvalues, 'r-', label="data")
#ax.plot(q_X.TB3MS, q_lnM1, 'o', label="data")
ax.legend(loc='best')
ax.set_title('Quarter M1')
ax.set_xlabel('ln(RGDP)')
ax.set_ylabel('ln(M1)')
fig.savefig("qM1.pdf")
```
[qM1.pdf](https://github.com/statsmodels/statsmodels/files/4228301/qM1.pdf)

The fitted values do not look like a straight line at the end. However, should it be a straight line since this is a linear model?

**Comment by josef-pkt** [comment]
fittedvalues depends on all regressors. Other regressors will shift the fittedvalues points in the plot, and the fittedvalues points will not be on a straight line in general.
If it is almost linear as in this case, it means that other regressors don't have much influence on prediction

y_hat = a + b1 x1 + b2 x2

b1 x1 is linear in x1, but y_hat bounces around for a given x1 because of x2

in graphics.regressionplots we have some plots like CCPR that are linear in x1. 
CCPR is component versus component plus residual, which ignores the effect of other x
