### ISSUE TITLE
How can I use exog for training without using it in forcasting ? 

### ISSUE THREAD

**Issue by rdeporre** [statsmodels/statsmodels#6571]
Hi
I try to forecast stock values with sarimax
I use exog vars in my training, as exchanged volumes.
I'd like to forecast because i don't know futur values of the stock of course, but i don't know futur values of the volume, so my exog vars, too.
so how can i get a forecast of stock values without providing exog volume beacause noone knows it ?
Actualy when i try to forecast for an horizon of 5 values, for example, i get an error telling me to provide 5 values of exog vars, but i dont know them. 
Can you help me ?

**Comment by ChadFulton** [comment]
Yes, SARIMAX is only modeling the `endog` variable, and as a result you have to independently provide forecasted values of the `exog` variable to forecast the `endog` variable. This is simply what happens with a univariate model. Typically, people do something like:

- Set the `exog` variables equal to their mean, so that the interpretation of the forecasts is conditional on the "average" behavior of the `exog` variables
- Forecast the `exog` variables using a simple model, like an AR(1)

You could alternativel also use a multivariate approach, where all the variables are modeled jointly, like a VAR model.

**Comment by rdeporre** [comment]
It seems i made a mistake with concepts of uni/multivariate and endo/exog
vars.
I didn't know VAR it seems to be the perfect method for my problem.
Thanks a lot Chad !
