### ISSUE TITLE
Exogenous interaction with AR and MA components

### ISSUE THREAD

**Issue by fredshone** [statsmodels/statsmodels#6623]
I would like to use an uni-variate auto-regressive model which has interactions between some exogenous variables and the auto-regressive components.

for example:
`y(t) = c + a y_{t-1} + b e_{t-1} + c x_t + d x_t  y_{t-1} + e x_t e_{t-1} + f e_t`

If this turns out to be a reasonable idea then implementation would be via AR(I)MA model. Adding optional exog variables for interactions with the AR and MA processes. However, as i suspect its not reasonable then perhaps some guidance on making use of existing API to that end.

I have been using standard OLS with lags and interactions for AR. But inclusion of MA is beyond me.

Happy/relieved to be told this is ridiculous - I have been unable to find literature - which is alarming. It seems interactions with lags of the same variable are going to be highly correlated with each other, which i think is causing problems with my interacting AR experiments.

**Comment by ChadFulton** [comment]
I guess this is like a time-varying coefficients ARIMA model, where you have parameterized the time-varying coefficients with a particular functional form, e.g. the coefficient on y_{t-1} is `a+ d x_t`.

A brief search turned up a couple of related models (i.e. TVP ARIMA models), although not with your particular functional form:

- https://www.ism.ac.jp/editsec/aism/pdf/052_1_0108.pdf
- https://www.jstor.org/stable/1391375?seq=1

At least from a technical perspective, you could put this into state space form and estimate the parameters. I have no idea how this type of model would perform. You would run into some issues, including (there may be more, this is just from a quick look):

- The model is not identified  since you need to estimate `b`, `e`, `f`, and the variance of the error process `Var(e_{t-1})`. You would need to normalize one of these to 1.
- Depending on x_t, the model would likely drift between explosive and stationary regimes. Maybe that's okay for your purposes. Often TVP-VAR models impose some sort of stationarity, but I don't know how feasible that is here.

**Comment by bashtage** [comment]
This appears to have been answered as well as possible.
