### ISSUE TITLE
Clustered one-sample t-test ~ constant WLS with robust covariance

### ISSUE THREAD

**Issue by oulenz** [statsmodels/statsmodels#6666]
(Note that I am not a statistician.)

I am looking for an implementation of a clustered one-sample t-test (actually, a paired t-test), but couldn't find one. I would like to test the mean of the cluster means against 0, without discarding all the  intra-cluster information. I have ~45 clusters and a variable number of instances per cluster (with a median of 3).

I found out that the p-values of linear regression are determined through a t-test, and that statsmodels offers cluster-robust p-values, so I could in effect get what I want by fitting a linear model on a single constant variable. I have the following questions:

* Do you see anything wrong with this approach? 
* Since I want to test the mean of the cluster means, I should use WLR with weights 1/m^2 where m is the cluster size, correct? Or should that be simply 1/m?
* What literature is the statsmodels implementation of the cluster-correction of the t-test based on?
* If this approach really amounts to a clustered one-sample t-test, might I suggest exposing it in the api as a dedicated function?

**Comment by josef-pkt** [comment]
paired t-test only works for cluster size = 2. But then it is equivalent to a t-test on the difference `y1 - y2`, so we can just use the one-sample t-test or the paired ttest in scipy.stats.

> Do you see anything wrong with this approach?

Nothing wrong, that's an intended use case.
Another option is to use GEE, which has a slightly different cluster robust covariance including a bias reduced version

> Since I want to test the mean of the cluster means, I should use WLR with weights 1/m^2 where m is the cluster size, correct? Or should that be simply 1/m?

If you use the original observations, i.e. all observations in all clusters, then there is no weighting, just use OLS. 
Weights would come in when we use cluster means in the regression.
(The latter is essentially what I'm doing for meta-analysis PR #6632. But I haven't started with cluster robust meta-analysis yet)

> What literature is the statsmodels implementation of the cluster-correction of the t-test based on?

It's pretty standard except that some stats packages differ in small sample corrections and degrees of freedom. I mostly followed Stata in this. The main references for cluster robust were articles by Cameron and Miller.
Here is an overview article
http://cameron.econ.ucdavis.edu/research/Cameron_Miller_JHR_2015_February.pdf

> If this approach really amounts to a clustered one-sample t-test, might I suggest exposing it in the api as a dedicated function?

It's not likely that we add a specific function for this, because it can simply be done by OLS, or GEE. The same would be the case of other robust sandwich cov_params, e.g. serial correlation.

However, I found some articles for cluster robust meta-analysis that use explicit formulas, and I have been working on several hypothesis tests, confidence intervals and similar that have a very close analogue or an equivalent model in OLS or GLM. In some cases, standalone specific functions have better small sample corrections that are not available in the general case using a model.
I'm not sure yet how much duplication between standalone tests and model based test would be the best choice.

(aside: Welch t-test, i.e. unequal variance is identical to using OLS with cov_type=HC2)

**Comment by oulenz** [comment]
Thank you for your quick reply!

> paired t-test only works for cluster size = 2. But then it is equivalent to a t-test on the difference `y1 - y2`, so we can just use the one-sample t-test or the paired ttest in scipy.stats.

I don't follow why you would say that cluster size has to be 2. I have clusters of pairs of observations. But as you say, a paired t-test is just a one-sample t-test on the difference, so my question is about a clustered one-sample t-test.

> Another option is to use GEE, which has a slightly different cluster robust covariance including a bias reduced version

Thanks for pointing that out, I will try it!

> 
> > Since I want to test the mean of the cluster means, I should use WLR with weights 1/m^2 where m is the cluster size, correct? Or should that be simply 1/m?
> 
> If you use the original observations, i.e. all observations in all clusters, then there is no weighting, just use OLS.
> Weights would come in when we use cluster means in the regression.
> (The latter is essentially what I'm doing for meta-analysis PR #6632. But I haven't started with cluster robust meta-analysis yet)

I would like to weigh the clusters equally, so clusters with more observations should not carry more weight than clusters with just two observations. For that I would have to use WLS, no? And the weights should be 1/m^2, where m is the cluster size?

> It's pretty standard except that some stats packages differ in small sample corrections and degrees of freedom. I mostly followed Stata in this. The main references for cluster robust were articles by Cameron and Miller.
> Here is an overview article
> http://cameron.econ.ucdavis.edu/research/Cameron_Miller_JHR_2015_February.pdf

Thanks!

> > If this approach really amounts to a clustered one-sample t-test, might I suggest exposing it in the api as a dedicated function?
> 
> It's not likely that we add a specific function for this, because it can simply be done by OLS, or GEE. The same would be the case of other robust sandwich cov_params, e.g. serial correlation.

Ok, but for a non-statistician like me, it took quite a bit of searching before i realised that I could get a clustered t-test this way. Also, it feels very backward: OLS uses a t-test, I don't need the linear regression so I run constant regression just to get at the t-test. Seems more elegant to expose it directly...

**Comment by josef-pkt** [comment]
> I don't follow why you would say that cluster size has to be 2. I have clusters of pairs of observations.

I misunderstood, I thought clusters are the generalization of the pairs, not that you have clusters of paired observations.

> I would like to weigh the clusters equally, so clusters with more observations should not carry more weight than clusters with just two observations. For that I would have to use WLS, no? And the weights should be 1/m^2, where m is the cluster size?

Yes, that compensates for the cluster size.
They are not really variance weights in that case. However, if you use a robust cov_type, then inference for WLS should still be correct.
(Using weights scales the observations, the scaled residual variance would not be constant anymore, if it is assumed that it is initially constant. AFAIR, cluster robust includes heteroscedasticity robust cov_params)

**Comment by oulenz** [comment]
Ok, thanks again for your help, I'm closing this now!

**Comment by RocaVincent** [comment]
Hello @oulenz , can you give more details about the way you performed a one-sample test on clustered data ? I understood you used a linear regression for this but what is the independent/dependent variables ? Because we only have one variable here (and the cluster information).
