### ISSUE TITLE
[Question] Updating VAR model with new data

### ISSUE THREAD

**Issue by cryptohyper** [statsmodels/statsmodels#6695]
Is it possible to update VAR model with new incoming data after training? Or do I have to use VARMAX if I want to forecast multivariate time series with possibility to update?

**Comment by josef-pkt** [comment]
VAR does not allow updating.

Updating prediction without re-estimation should work, but AFAIR is not separately tested and is mainly for internal use. It's easier in VAR than other models because there is no MA term.

The predict function for VAR just needs the last nlags observations, plus trend and exog. AFAIR, there is a standalone function that can be used for prediction/forecasting with new observations.

The statespace models have more updating built in, while VAR is essentially just a big OLS.

**Comment by cryptohyper** [comment]
Thanks for clarification!
