### ISSUE TITLE
 Is the DynamicFactor Model built to handle large panels of times series as input?

### ISSUE THREAD

**Issue by destambouli** [statsmodels/statsmodels#6864]
Apologies in advance if this formatting does not follow a template, this is my first time posting here please let me know if any edits are needed.

I am working with the [DynamicFactor ](https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.dynamic_factor.DynamicFactor.html?highlight=dynamicfactor) model 

I noticed that when dealing with large panels +100 times series the estimation (.fit) takes very long time to run +2h or will raise an exception for non-positive definite forecast error covariance matrix.
Which raises the following questions :      

> -  Does the implementation of the dynamic factor model allows the work on large panels? With profiling the Kalman filtering is the step that takes too long to complete
> 
> -  In the same context of high dimensional panels, what are the reasons that lead to non-positive definite error forecast covariance matrices? Is it numerical stability ? This error causes the Cholesky inversion to raise a Linalg exception and changing Cholesky to LU causes memory errors (as well as working with non-valid covariance matrices).
> 
> - Is there a routine implemented to correct the non-positive definite covariance errors?

**Comment by ChadFulton** [comment]
The current `DynamicFactor` class uses quasi-Newton methods to numerically maximize the likelihood function. When there are hundreds of observed time series, there can be thousands of parameters. In this case, quasi-Newton methods will take a long time, and often don't produce good results anyway.

The solution for these models is to use the EM algorithm to maximize the likelihood function, which the current model does not support. However, I will soon be adding a new dynamic factor model that will support the EM algorithm, and will allow estimation with hundreds of variables.

The non-positive definite forecast error covariance matrix error is probably due to the optimizer getting into a bizarre part of the parameter space, given that it has so many parameters that it's trying to estimate.  However, that error should no longer appear due to an improvement from #6797.

**Comment by ChadFulton** [comment]
Closing since no action from us, but feel free to continue to follow up with questions, etc.
