### ISSUE TITLE
GLM is Broken in Python 3.8

### ISSUE THREAD

**Issue by TobyRoseman** [statsmodels/statsmodels#6956]
#### Describe the bug

Fitting a GLM works in Python 3.7 but does not work in Python 3.8.

#### Code Sample
The following works in Python 3.7 but does not work in Python 3.8:
```python
import numpy as np
import statsmodels.api as sm

np.random.seed(8)
n, d = 100, 10
x = np.random.rand(n,d)
y = np.random.randint(2, size=n)

sm_model = sm.GLM(y, x, family=sm.families.Binomial())
sm_model = sm_model.fit()
print(sm_model.llf)
```

In Python 3.8, the `fit` call produces lots of error messages that look like this:
```
python(97726,0x116394dc0) malloc: can't allocate region
:*** mach_vm_map(size=18446744071921549312, flags: 100) failed (error code=3)
python(97726,0x116394dc0) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
```

In Python 3.8 `sm_model.llf` is `nan`. In Python 3.7 it is a number. 

Removing the ` family=sm.families.Binomial()` from `sm.GLM(...)` (i.e. using Gaussian) still produces malloc errors, but does seem to produce the right model.

#### Expected Output

No malloc error in Python 3.8.

Also gives the correct answer, when using Binomial Family, in Python 3.8 

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

INSTALLED VERSIONS
------------------
Python: 3.8.5.final.0
OS: Darwin 19.5.0 Darwin Kernel Version 19.5.0: Sun Apr 19 22:51:38 PDT 2020; root:xnu-6153.120.31~14/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

Statsmodels
===========

Installed: 0.10.2 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.21 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/Cython)
numpy: 1.16.4 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/numpy)
scipy: 1.5.1 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/scipy)
pandas: 1.0.5 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/pandas)
    dateutil: 2.8.1 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/dateutil)
patsy: 0.5.1 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: Not installed
cvxopt: Not installed
joblib: 0.16.0 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/joblib)

Developer Tools
================

IPython: 7.17.0 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/IPython)
    jinja2: Not installed
sphinx: Not installed
    pygments: 2.6.1 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/pygments)
pytest: 6.0.1 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/pytest)
virtualenv: 20.0.30 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/virtualenv)

</details>

**Comment by bashtage** [comment]
What happens if you use 0.11.1?  That is the latest release.  AFAIK Python 3.8 wasn’t yet out when 0.10 was released.  From: Toby RosemanSent: Thursday, August 6, 2020 11:05 PMTo: statsmodels/statsmodelsCc: SubscribedSubject: [statsmodels/statsmodels] GLM is Broken in Python 3.8 (#6956) Describe the bugFitting a GLM works in Python 3.7 but does not work in Python 3.8.Code SampleThe following works in Python 3.7 but does not work in Python 3.8:import numpy as npimport statsmodels.api as sm np.random.seed(8)n, d = 100, 10x = np.random.rand(n,d)y = np.random.randint(2, size=n) sm_model = sm.GLM(y, x, family=sm.families.Binomial())sm_model = sm_model.fit()print(sm_model.llf)In Python 3.8, the fit call produces lots of error messages that look like this:python(97726,0x116394dc0) malloc: can't allocate region:*** mach_vm_map(size=18446744071921549312, flags: 100) failed (error code=3)python(97726,0x116394dc0) malloc: *** set a breakpoint in malloc_error_break to debuginit_dgelsd failed initIn Python 3.8 sm_model.llf is nan. In Python 3.7 it is a number.Removing the family=sm.families.Binomial() from sm.GLM(...) (i.e. using Gaussian) still produces malloc errors, but does seem to produce the right model.Expected OutputNo malloc error in Python 3.8.Also gives the correct answer, when using Binomial Family, in Python 3.8Output of import statsmodels.api as sm; sm.show_versions()/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.import pandas.util.testing as tmINSTALLED VERSIONSPython: 3.8.5.final.0OS: Darwin 19.5.0 Darwin Kernel Version 19.5.0: Sun Apr 19 22:51:38 PDT 2020; root:xnu-6153.120.31~14/RELEASE_X86_64 x86_64byteorder: littleLC_ALL: NoneLANG: en_US.UTF-8StatsmodelsInstalled: 0.10.2 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/statsmodels)Required Dependenciescython: 0.29.21 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/Cython)numpy: 1.16.4 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/numpy)scipy: 1.5.1 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/scipy)pandas: 1.0.5 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/pandas)dateutil: 2.8.1 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/dateutil)patsy: 0.5.1 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/patsy)Optional Dependenciesmatplotlib: Not installedcvxopt: Not installedjoblib: 0.16.0 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/joblib)Developer ToolsIPython: 7.17.0 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/IPython)jinja2: Not installedsphinx: Not installedpygments: 2.6.1 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/pygments)pytest: 6.0.1 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/pytest)virtualenv: 20.0.30 (/Users/tobyroseman/Documents/turicreate-py38/deps/env/lib/python3.8/site-packages/virtualenv)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by TobyRoseman** [comment]
> What happens if you use 0.11.1?  That is the latest release.  AFAIK Python 3.8 wasn’t yet out when 0.10 was released.

The behavior is the same with 0.11.1. I've tried all three versions which support Python 3.8 (0.11.1, 0.11.0 and 0.10.2) they all have this issue.

**Comment by josef-pkt** [comment]
I think this is unrelated to statsmodels.

It looks like a problem with lapack, so check whether numpy and scipy work correctly in your installation.
GLM itself doesn't have any cython or c code directly.

**Comment by bashtage** [comment]
Where are you getting NumPy and statsmodels from?  If you are pip installing, could you try using Anaconda?

**Comment by bashtage** [comment]
I would also strongly recommend trying a much newer NumPy. 1.16 is pretty old and if you are using pip, OpenBLAS has gone through quite a few changes in this period.

**Comment by bashtage** [comment]
Almost certainly this issue https://github.com/Homebrew/homebrew-core/issues/31404.  FIx is to use a recent NumPy and SciPy.

Going to close since this upstream of statsmodels.

**Comment by TobyRoseman** [comment]
I am using Anaconda not Homebrew.

I just tried installing StatsModels in a fresh Python 3.8 virtual environment. The code works there. That was using NumPy 1.19.1.

However when I manually install NumPy 1.16 in that same virtual environment, I get the same incorrect behavior as before. It seems clear to me StatsModel is broken on macOS in Python 3.8 with NumPy 1.16. 

I think this issue should be reopened. I think either the root issue should be solved or [the NumPy dependency](https://github.com/statsmodels/statsmodels/blob/11b8c013b58658de091e07640b09ee120ad81ea3/setup.py#L42) should be updated. 

I also wouldn't say NumPy 1.16 is particularly old. It was released in January of 2019. So about a year and a half ago.

**Comment by bashtage** [comment]
No, numpy is broken in version 1.16 on OSX. The error you are seeing is in
code provided by NumPy. The real culprit is Apple though who have not
updated their accelerate framework in a long time. This is why OSX was
moved on to OpenBLAS.

**Comment by josef-pkt** [comment]
> I also wouldn't say NumPy 1.16 is particularly old. It was released in January of 2019. So about a year and a half ago.

But that's older than py 3.8, there is no guarantee that an old version works on a new python 3.x version, and in general will not work because of binary changes (C-API).

Python 3.8.0 Oct. 14, 2019
