### ISSUE TITLE
Default branch name, master.

### ISSUE THREAD

**Issue by dvklopfenstein** [statsmodels/statsmodels#6996]
#### Describe the bug

The default branch name of "master" is racist and embarrassing.

#### Expected Branch name

Please consider changing the name of the default branch from "master" to "main" or something similar.

#### Quick easy fix

It is super easy to change the default branch from "master":

  * https://github.com/StevenMMortimer/master-to-main
  * https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

Please consider this request. How am I to explain that I am dependent on a repo that prominently features "master" at the top of its home page as the default GitHub branch?

I am in Philly, where there a lot of black people. What do I say to them about keeping "master"?

Thank you for considering this request.

**Comment by ChadFulton** [comment]
I agree that this is a worthwhile idea. The main issue is that we have a relatively small base of contributors, all of whom are volunteers, and it can be tough to be "first movers". 

We will likely need to wait for Github to provide the "seamless support" that it is planning for later this year, see https://github.com/github/renaming for details about what that support will provide. In fact, they write:

> If you haven’t moved yet, we recommend not moving right now, and waiting until later this year. We’re investing in tools to make the renaming the default branch of an existing repository a seamless experience for both maintainers and contributors.

For the same reason, it is often better to let one of the larger pydata packages with a lot of contributors (like Pandas, etc.) take these steps first, so that we can better understand the process. Some discussions appear to be ongoing at https://github.com/scikit-learn/scikit-learn/issues/17595, https://github.com/dask/community/issues/68, and https://github.com/bokeh/bokeh/issues/10224.

**Comment by bashtage** [comment]
I think we will also wait until the numerical python community standardizes on a default branch name. It may be `devel` or `default` or something else.  You should consider joining the NumPy mailing list and making the case there. That is more likely to have a wider impact.

**Comment by bashtage** [comment]
One more point, without support from GitHub this will invalidate all of the 145 PRs that are open.

**Comment by dvklopfenstein** [comment]
@github, What about this: https://github.com/statsmodels/statsmodels/issues/6996#issuecomment-680703939

**Comment by josef-pkt** [comment]
What about having an MA or MBA degree?
