### ISSUE TITLE
Kalman Filter initial values 

### ISSUE THREAD

**Issue by zeina-abuaisheh** [statsmodels/statsmodels#7037]
Hello,

The basic kalman filter as we all know is as follows:

```
    # Prediction Part
    x =np.dot(F,x)
    P = np.dot(np.dot(F,P),F.T) + Q

    # Update Part
    S=(np.dot(np.dot(H,P),H.T) + R)
    S2 = inv(S)
    K = np.dot(P,H.T)*S2
    x = x +K*((z[:,k]- np.dot(H,x)))
    P = np.dot((I - K*H),P)
```

Taking into account the Local Linear Trends model: https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_local_linear_trend.html
What are the values of Q, R and the initial value of P in the kalman filter of statsmodels?

Thanks

**Comment by ChadFulton** [comment]
For the local linear trend model,

- What you've denoted by Q is the same matrix as Q_t in that notebook, so it is a diagonal matrix with entries sigma_xi^2 and sigma_zeta^2.
- What you've denoted by R in your post is referred to as H_t in the notebook, and it is a 1x1 matrix with entry sigma_epsilon^2

To initialize the Kalman filter in Statsmodels:

- For the local linear trend model in that notebook, we used an approximate diffuse initialization for the state vector, so that P = kappa * I, where I is the identity matrix and kappa = 1x10^6.
- Since that notebook was written, we have also introduced exact diffuse initialization, which uses an approach that sends kappa to infinity.
- It is also possible to initialize models with known values or with the unconditional distribution, for stationary processes

**Comment by zeina-abuaisheh** [comment]
Thanks a lot for your detailed answer.

When we fit the model using MLE, we get the values of the parameters to construct the matrices Q and H
for instance in the above link I shared with you it says in the model's summary:
sigma2.measurement, coef =  0.0010

Does the coefficient 0.0010 represents sigma_epsilon^2? so I don't need to square it, right?

**Comment by ChadFulton** [comment]
Yes, that's correct. The estimated parameter is the variance, so if that's what you're looking for, then you do not need to square it.

**Comment by zeina-abuaisheh** [comment]
Thanks a lot for your confirmation.
I wrote a basic kalman filter which uses the outputs of mod.fit of the Local Linear Trends model (i.e, 'sigma2.measurement', 'sigma2.level' and 'sigma2.trend') to build the matrices Q and H, and I initialized P to kappa * I, but I don't get the very same results as get_prediction and get_forecast of statsmodels

here are the main parts of the code:
```
# Get parameters estimation results
params = res.params

observation_error = params[0]
state_error_position = params[1]
state_error_velocity = params[2]

F = np.array([[1, 1],[ 0, 1]]) # State matrix
H = np.array([[1, 0]]) # Measurements matrix 
Q = np.array([
    [state_error_position, 0],
    [0, state_error_velocity]
])


R = np.array([[observation_error]])

# #% Loop through and perform the Kalman filter equations recursively
I = np.identity(2)
P = 10**(-6) * I

x_list = []
x_kalman = np.array([[measurements[0]],[0]])

for k in range(len(vehicle_dist_to_closest_path)):
    # Predict
    x_kalman = np.dot(F, x_kalman)
    P = np.dot(np.dot(F, P), F.T) + Q
    # Update
    S = (np.dot(np.dot(H, P), H.T) + R)
    S_inverse = inv(S)
    K = np.dot(P,H.T) * S_inverse
    x_kalman = x_kalman + K * ((measurements[k] - np.dot(H, x_kalman)))
    P = np.dot((I - np.dot(K, H)),  P)
    x_list.append(x_kalman)

```
In the forecast case, I set "K" to zero.
Do you know why I don't get the same outputs as get_prediction and get_forecast of statsmodels?

Thanks a lot

**Comment by ChadFulton** [comment]
There are three differences between your code and what Statsmodels is doing:

1. You have `P = 10**(-6) * I`, but the approximate diffuse initialization is `P = 10**6 * I`
2. We initialize in terms of the predicted state and predicted state covariance, so you need to skip the prediction step when k == 0
3. The diffuse initialization sets the initial predicted state equal to [0, 0], meaning that it is not initialized with the first observation (`measurements[0]`).

**Comment by zeina-abuaisheh** [comment]
Thanks a lot for your answers, they are super helpful.
Can you please clarify this, as I am not sure if I understood you well:

`We initialize in terms of the predicted state and predicted state covariance, so you need to skip the prediction step when k == 0`

**Comment by ChadFulton** [comment]
Your notation makes it hard to express this, since you use x_kalman and P for both the predicted distribution values (x_{t|t-1} and P_{t|t-1}) and the filtered distribution values (x{t|t}, P_{t|t}).

The prediction step takes as arguments the previous filtered values, which means that you have implicitly initialized the model with P_{0|0}, x_{0|0}. Instead, Statsmodels initializes with P_{1|0} and x_{1|0}.

This makes no real difference, since in the notation that Statsmodels uses, x_{1|0} = T x_{0|0} (where T is the transition matrix), and you are free to initialize either way (in the same way that you could choose to place a prior on a variance rather than on a standard deviation). However, if you want to match Statsmodels' output exactly, then you need to use the same initialization.

**Comment by zeina-abuaisheh** [comment]
Thanks so much, it's super clear now. You can close the issue, thanks again for your continuous help

**Comment by ChadFulton** [comment]
No problem, glad to help.
