### ISSUE TITLE
Avoid np.linalg.inv call in regression.rolling.RollingWLS.fit if output is not used

### ISSUE THREAD

**Issue by mm842** [statsmodels/statsmodels#7140]
#### Problem description

In the documentation of `statsmodels.regression.rolling.RollingWLS.fit` the parameter `method` is described as 

> method{‘inv’, ‘lstsq’, ‘pinv’}
> Method to use when computing the the model parameters.
> ‘inv’ - use moving windows inner-products and matrix inversion. This method is the fastest, but may be less accurate than the other methods.
> ‘lstsq’ - Use numpy.linalg.lstsq
> ‘pinv’ - Use numpy.linalg.pinv. This method matches the default estimator in non-moving regression estimators.

An obvious reason that 'inv' is fastest in the current implementation to be that `np.linalg.inv` is called also for 'lstsq' and 'pinv':
![image](https://user-images.githubusercontent.com/8350047/97979299-31732e80-1dcf-11eb-8e4c-11e257af684a.png)

(ll. 222 in https://github.com/statsmodels/statsmodels/blob/master/statsmodels/regression/rolling.py)

If `params_only==True` then `wxpwxi` seems to be never used but has impact on performance. 

#### Proposed solution
Doing in the try-except block quoted above something like   
```python
    if method == "inv" or not params_only:
        wxspwxi = np.linalg.inv(wxpwx)
    [...]
```
should speed up the the method for `method=='lstsq'` and `method=='pinv'`.

**Comment by bashtage** [comment]
`inv` is faster since wxpwx is updates using a rank 1 update, and only depends on the number of variables in the model.  The other two methods depend on both the number of variables in the model and the rolling window size, and so have an extra term in their computational complexity.  

If you want to submit a PR, it should be fine to skip this inversion when not necessary. I suspect that it will have a small performance impact.

**Comment by mm842** [comment]
Thanks for the details. I submitted a PR and provided a short example comparing the performance on my machine for this one example.
