### ISSUE TITLE
SARIMAX Help

### ISSUE THREAD

**Issue by riddh9904** [statsmodels/statsmodels#7185]
#### Is your feature request related to a problem? Please describe
I am working on a time series problem to predict the sales. On predicting the sales using SARIMA the results are coming fine but when I am including the exog, the results are going for a toss. Though the curve followed is fine but the intercept is not good. Its like the actuals for 2019 are 6,7,8...I am getting 2,3,4 i.e. actuals-2 but for 2020 if actuals are 6,7,8 then I am getting 10,11,12 i.e. actuals plus 3. The time series is monthly.

#### Describe the solution you'd like
How can I transform the exog so as to get a better fit. Or what else can be done.

#### Describe alternatives you have considered
I have tried tuning the state space parameters like enforce_stationarity , using these the 2019 fit is getting better but still no impact on 2020 results.

**Comment by riddh9904** [comment]
@ChadFulton Please help.

**Comment by riddh9904** [comment]
Images attached here
https://stats.stackexchange.com/questions/498260/i-am-modelling-a-time-series-the-results-are-coming-fine-without-exogenous-vari

**Comment by ChadFulton** [comment]
It's hard to know how to help without an example that can be replicated. My guess would be that you're not providing the correct `exog`, but of course I can't be sure. My suggestion is to double-check that you are only providing the exog for the training period when you call `forecast`.

**Comment by ChadFulton** [comment]
Correction to my last message: you should only be providing the exog for the **test** period when you call forecast (i.e. no exog at all for the training period)

**Comment by bashtage** [comment]
Seems to work as expected using a basic sanity check that constructs the exog two ways. 

```
import statsmodels.api as sm
import statsmodels.tsa.api as tsa

a = tsa.ArmaProcess.from_coeffs([.9],[.5])
x = a.generate_sample(10000)
y = 10 + 2 * x
b = tsa.ArmaProcess.from_coeffs([1.6,-0.8])
e  = b.generate_sample(10000)
y += e
z = sm.add_constant(x)

res = tsa.SARIMAX(y[:9990], x[:9990], trend="c", order=(2,0,0)).fit()
res2 = tsa.SARIMAX(y[:9990], z[:9990], trend="n", order=(2,0,0)).fit()

f1 = res.forecast(10,exog=x[9990:][:,None])
f2 = res2.forecast(10,exog=z[9990:][:,None])
print(f1 - f2)
```

```
[-5.28398954e-06 -1.20670298e-05 -1.96670200e-05 -2.85355597e-05
 -3.76595737e-05 -4.63705667e-05 -5.47324478e-05 -6.16013892e-05
 -6.64342742e-05 -6.75857078e-05]
```

```
print(f1)
```

```
[-0.24593243 -0.84579778 -0.4399325   2.52060865  5.30045807  6.25528193
  6.48855452  5.53609999  4.91728029  3.37928576]
```

**Comment by bashtage** [comment]
Parameters are exactly as expected
```
In [56]: res.params
Out[56]: array([ 2.06297827,  1.98859026,  1.60957678, -0.81649077,  1.01239655])

In [57]: res2.params
Out[57]: array([ 9.97026842,  1.98859114,  1.60957909, -0.81649109,  1.01241283])
```

**Comment by riddh9904** [comment]
@ChadFulton I have double check I am passing the correct exogs. I have attached the jupyter notebook and data below
[Notebook.zip](https://github.com/statsmodels/statsmodels/files/5611840/Notebook.zip)

Please help

**Comment by ChadFulton** [comment]
This looks to me like a case of overfitting, which often results in poor out-of-sample forecasts. You have a sample size of 60, but you effectively have a sample size of 47 due to the seasonal and non-seasonal differences that you're taking.  Meanwhile, you are trying to estimate 26 parameters.

For example, I get better out-of-sample results using only columns `['c', 'f', 'h', 'n', 'u']`.

**Comment by riddh9904** [comment]
@ChadFulton Yes I am also getting better fit using these variables but the business requirement is to include all the variables. Is there any other way estimate this. 
I tried to do parameter tunning like 
model=SARIMAX(endog=y,exog=X_df,
              order=(3,1,0),seasonal_order=(0,1,0,12),freq='M',mle_regression=False,enforce_stationarity=False
              ,enforce_invertibility=True,trend='ct')
using this 2019 results are fine but 2020 fir is still not good.

Also how did you get a sample size of 47 due to the seasonal and non-seasonal differences. 
I am new to time series modelling so don't have much idea.
Also please suggest some way to model this.

**Comment by ChadFulton** [comment]
> Yes I am also getting better fit using these variables but the business requirement is to include all the variables.

> Also please suggest some way to model this.

There are no options in `SARIMAX` that will help here. If you absolutely must include all the variables (although this seems like a strange requirement), you could look into models that include regularization, like Lasso (see e.g. `fit_regularized` method to the `OLS` or `GLM` models).

> Also how did you get a sample size of 47 due to the seasonal and non-seasonal differences.

First, think about the seasonal difference part, where you specified 1 seasonal difference, with a period of 12 months. This means that you are modeling the change from the previous year, but for the first 12 observations, you don't have the value from the previous year, so your effective sample size starts after the 12th observation.

Second, you also have 1 non-seasonal difference. Given the above, this means that you're modeling the change in the change from the previous year. Since the first value won't have a previous value, your effective sample size is reduced by 1 more.

**Comment by riddh9904** [comment]
@ChadFulton Thanks a lot.
