### ISSUE TITLE
AttributeError: 'Holt' object has no attribute 'fitted_values'

### ISSUE THREAD

**Issue by hanshupe** [statsmodels/statsmodels#7431]
I am new user of statsmodels. I tried to reproduce the examples from:
 https://www.statsmodels.org/dev/examples/notebooks/generated/exponential_smoothing.html

Unfortunately it looks like Holt has no fitted_values attribute as in the example. How can I retrieve those values? I am using version 0.12.2.

**Comment by bashtage** [comment]
You need to call `fit` to get a results instance. `Holt` is a model class.

**Comment by hanshupe** [comment]
I did, I was copying the examples from the link above

**Comment by bashtage** [comment]
You have made a mistake somewhere in your copy and paste.  You can directly download the notebook from the repo and run it. I just did and all cells run correctly without error or warning.

**Comment by hanshupe** [comment]
In the documentation of Holt I can't find a fitted_values parameter either: https://www.statsmodels.org/dev/generated/statsmodels.tsa.holtwinters.Holt.html#statsmodels.tsa.holtwinters.Holt

**Comment by bashtage** [comment]
That is because you have to call `fit`, which returns a `HoltWintersResults`. Fitting virtually every model in statsmodels requires 2 steps.

1. Defining the model which is immutable
2. Calling fit which returns a Model`Results` class.  Fit provides all options that are allowed to change between calls.

https://www.statsmodels.org/dev/generated/statsmodels.tsa.holtwinters.HoltWintersResults.html#statsmodels.tsa.holtwinters.HoltWintersResults

**Comment by bashtage** [comment]
It is also `fittedvalues`, not `fitted_values`.
