### ISSUE TITLE
VARMX Simulation Using Fitted Residuals

### ISSUE THREAD

**Issue by armarion** [statsmodels/statsmodels#7477]
I am trying to do some bootstrap simulations of a VARMAX model by resampling the fitted model residuals in my model simulation. The first thing I wanted to test is to make sure that if I simulate a model from the initial state of the original endogenous data, and used the fitted residuals that the model would generate exactly the same path of endogenous variables. In other words, if I simulate using anchor='start' and pass in the model residuals, I should recover the endogenous variable vector. This is  just a simple round trip test to make sure I have the plumbing working. 

Unfortunately this isn't working, and I'm not sure why. When I try to do this, the model simulates a different path each time and it doesn't even line up to the initial value in my endogenous variable. Any help how to do this?

```

import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

# load sample data
dta = sm.datasets.webuse('lutkepohl2', 'https://www.stata-press.com/data/r12/')
dta.index = dta.qtr
dta.index.freq = dta.index.inferred_freq
endog = dta.loc['1960-04-01':'1978-10-01', ['dln_inv', 'dln_inc']]

#fit VARMAX model and simulate using fitted residuals and start anchor
mod = sm.tsa.VARMAX(endog, order=(2,0), trend='n')
res = mod.fit(maxiter=1000, disp=False)
sim = mod.simulate(params = res.params, nsimulations = len(endog), repetitions = 1, state_shocks = res.resid, measurement_shocks=None, anchor = 'start')

#compare simulated values to original values
print(sim)
print(endog)

```

**Comment by ChadFulton** [comment]
This is a good question, and it's a good opportunity to add to the record.

There are two reasons why the simulations aren't matching up:

1. The timing of the state space model formulation (which follows Durbin and Koopman, 2012) is such that the time `t` innovation generates the time `t+1` state. For a VAR model in state space form, this means that the timing convention is `y(t+1) = T y(t) + e(t)`, which is different from the usual VAR timing convention `y(t+1) = T y(t) + e(t + 1)`, and this means you need to shift the residuals to get them to line up (see code below).
2. The first simulation will be entirely generated by the initial state, which be default is drawn from the distribution specified by the "initialization" of the model.  This is why you are still seeing randomness in your simulations, because the initial state is still being randomly drawn (in the stationary VAR case, the initial distribution is the unconditional distribution).  You can specify a specific initial state using the `initial_state` argument. Specifying the correct initial state to replicate a particular simulation can be complicated, but in this case it is equal to the first value of the `filtered_state` result object.

Putting these two things together, the following code works for me:

```python
#fit VARMAX model and simulate using fitted residuals and start anchor
mod = sm.tsa.VARMAX(endog, order=(2,0), trend='n')
res = mod.fit(maxiter=1000, disp=False)

state_shocks = np.c_[res.resid.iloc[1:].T,
                     [0, 0]].T
initial_state = res.filtered_state[..., 0]

sim = mod.simulate(params=res.params, nsimulations=len(endog),
                   repetitions=1, state_shocks=state_shocks, measurement_shocks=None,
                   anchor='start',
                   initial_state=initial_state)

# #compare simulated values to original values
sim.columns = sim.columns.droplevel(1)
print('Data:')
print(endog.head(), end='\n\n')
print('Simulated:')
print(sim.head(), end='\n\n')
print('Maximum absolute difference:')
print(np.max(np.abs(sim - endog)))
```

yields:

```
Data:
             dln_inv   dln_inc
qtr                           
1960-04-01 -0.005571  0.030570
1960-07-01  0.032970  0.042111
1960-10-01  0.037139  0.016360
1961-01-01  0.094363  0.031939
1961-04-01 -0.043591  0.021381

Simulated:
             dln_inv   dln_inc
qtr                           
1960-04-01 -0.005571  0.030570
1960-07-01  0.032970  0.042111
1960-10-01  0.037139  0.016360
1961-01-01  0.094363  0.031939
1961-04-01 -0.043591  0.021381

Maximum absolute difference:
dln_inv    2.775558e-17
dln_inc    6.938894e-18
dtype: float64
```

**Comment by ChadFulton** [comment]
I'm closing this question as answered, but feel free to follow up if you like.

**Comment by armarion** [comment]
Perfect solution, thank you! Maybe would be nice to have a feature to bootstrap the simulation naturally using the residuals, similar to how the R package rmgarch does. In the meantime I can just reshuffle the residuals for each path
