### ISSUE TITLE
Using fourier decomposition for SARIMAX exog

### ISSUE THREAD

**Issue by zollen** [statsmodels/statsmodels#7498]
I am thinking of using fourier decomposition for a time series data, the resulting base frequencies would be used for the exog of the SARIMAX, do you think it would help improve the overall mean errors?

If the above approach is feasible, is it possible to built-in this features as part of internal auto-optimization of SARIMAX?

**Comment by bashtage** [comment]
Standdard FFTs are noncausal in the sense that the transformed observation at location `i` uses information from values `0,1,2,...,i-1,I,i+1, i+2,...`.  This makes it a bad idea to use in most time series models since it is using information from the future. This would not be a reasonable candidate for inclusion, although you might find it reasonable to use as an exogenous predictor.  There are probably similar transformations that are causal, which might be useful.  However, these are also too specialized for inclusion as a standard argument, and can always be included as an `X` variable.
