### ISSUE TITLE
Adding more kernels in KDE

### ISSUE THREAD

**Issue by Simardeep27** [statsmodels/statsmodels#7663]
Statsmodels consists of various different kernels but few additions such as exponential kernel and quartic kernel could be a good addition to the group of kernels. 

The additions would be similar as other kernels, classes would be created in <code>statsmodels/sandbox/nonparametric/kernels.py</code>, which would be then called in the list of kernels in <code>statsmodel/nonparametric/kde.py</code>.

**Comment by josef-pkt** [comment]
Do you have any code for those?

I added asymmetric kernels,  beta kernel (kernels for unit interval) and kernels for positive valued random variables, but they don't use an interface that is compatible with the older kernel functions in nonparametric, at least not with those used for MultivariateKDE.

Asymmetric kernels don't have the property that they depend on distance between points, which is assumed by KDEUnivariate.

Is exponential kernel an asymmetric kernel?

**Comment by Simardeep27** [comment]
I think you are correct here, exponential kernel is an asymmetric kernel and could be added in <code>kernels_asymmetric.py</code>. Looking into the implementation of asymmetric kernels, wouldn't it be better to have a single class of these kernels instead of separate functions?

Re code, should I make a PR for quartic kernel?

**Comment by josef-pkt** [comment]
> Looking into the implementation of asymmetric kernels, wouldn't it be better to have a single class of these kernels instead of separate functions?

Not until we have a better idea of how they fit in and will be reused.
I wrote them mainly to work out the math and see how well they do.
My current use of them is to support and compare with parametric multivariate distributions in the context of copulas, e.g. nonparametric Beta and Bernstein copulas/distributions.
`MultivariateKDE` could use them and uses separate functions for cdf and pdf. But I didn't like the signature of those function and used a different argument list. Tying them into MultivariateKDE would automatically (?) give us optimal bandwidth selection.

Exponential kernel might be a special case of an existing asymmetric kernel. But I don't remember those details.

> Re code, should I make a PR for quartic kernel?

Yes, that sounds useful. But I haven't looked at that part in a long time.

aside: 
I also wrote asymmetric kernel `rvs` functions for generating random samples, but the only one for which I found references is Beta kernel. I use that one in copulas. I didn't add the rvs functions to statsmodels yet because I don't have references, and I wrote them "by analogy".

**Comment by Simardeep27** [comment]
Re asymmetric kernels, that makes sense, will look into this.

Re quartic, Actually I found quartic kernel (biweight) already implemented in <code>sandbox/nonparametric/kernels.py</code>. Also found that **Tricube** kernel was missing, so will create a PR for that

**Comment by Simardeep27** [comment]
Hey @josef-pkt , I've added Tricube Kernel in my forked repository, with the test class,
Here is the working example: https://colab.research.google.com/drive/1Lx8pq4jOJUORld_iThjVHIhG-Bdoe_2r?usp=sharing

If you feel that it works perfectly fine and need no changes, I'll make a PR

**Comment by josef-pkt** [comment]
@Simardeep27 open a PR. That makes it easier to see what changes you made and what code you added.

**Comment by Simardeep27** [comment]
Sure will do, Just a query regarding test cases in <code>test_bandwidth.py</code>, how do you decide upon the <code>self.const</code> value?

**Comment by josef-pkt** [comment]
looks like they came from a reference, likely Hansen's notes, link in #1243, PR #1271
However, they are only available for some kernels, not for tricube

we might just add the current results as a regression test number, and check that kde at rule of thumb bandwidth is about as smooth as similar kernels for the normal case

**Comment by josef-pkt** [comment]
I just remembered in the context of bandwidth choice.

The articles for the asymmetric kernels have expressions for integrated mean squared error and optimal bandwidth formulas for given reference distributions, some use gamma as reference distribution for kernels in R+ (nonegative observations).
When we add those, then we need to convert the asymmetric kernels to a class, so we can add additional methods.

I didn't want to spend the time on that because asymmetric kernels was mostly a detour for me while working on copulas.

**Comment by Simardeep27** [comment]
> looks like they came from a reference, likely Hansen's notes, link in #1243, PR #1271
> However, they are only available for some kernels, not for tricube
Oh okay, thanks for the references




> The articles for the asymmetric kernels have expressions for integrated mean squared error and optimal bandwidth formulas for given reference distributions, some use gamma as reference distribution for kernels in R+ (nonegative observations).
> When we add those, then we need to convert the asymmetric kernels to a class, so we can add additional methods.

So, if I understood correctly, we require classes for asymmetric kernel when we would use these kernels as reference distributions.

**Comment by Simardeep27** [comment]
I had a doubt regarding the test cases, how did you obtain the values of <code>results_kernel_regression.csv</code>, I saw that it is being used for testing the Kernels.

**Comment by josef-pkt** [comment]
test_kernel_regression.py mentions code to replicate in R using package `np`.
So I guess it's from there, but I didn't look at the details or history for that.

> So, if I understood correctly, we require classes for asymmetric kernel when we would use these kernels as reference distributions.

We need classes if we support some rules of thumb or plug-in bandwidth choice for the asymmetric kernel. 
The symmetric kernels use the normal distribution as reference. But kernels in R+ cannot use a normal reference.
(Rules of thumb for kernel bandwidth are optimal for the reference distribution for which they are calculated, but might not be good for other distributions._

**Comment by Simardeep27** [comment]
> test_kernel_regression.py mentions code to replicate in R using package `np`.
> So I guess it's from there, but I didn't look at the details or history for that.
> 
> > So, if I understood correctly, we require classes for asymmetric kernel when we would use these kernels as reference distributions.

Should I update it?

> We need classes if we support some rules of thumb or plug-in bandwidth choice for the asymmetric kernel.
> The symmetric kernels use the normal distribution as reference. But kernels in R+ cannot use a normal reference.
> (Rules of thumb for kernel bandwidth are optimal for the reference distribution for which they are calculated, but might not be good for other distributions._

Oh got it, thanks for the explanation.
