### ISSUE TITLE
BUG: spikes in lowess

### ISSUE THREAD

**Issue by cascalesclement** [statsmodels/statsmodels#7700]
It seems that the regression is making huge mistakes with some points and i do not understand why. A few points become peaks. I do not know if it is a bug but whatever the case, i report it. Here is a piece of code that shows the problem.

####### -*- coding: utf-8 -*-

import matplotlib.pyplot as plt
import numpy as np
import statsmodels.api as sm

y=[29.60046, 29.70066, 29.99869, 30.18495,
 30.52497, 30.88539, 31.06073, 31.16298, 31.3087, 31.34476, 31.4047, 31.27913,
 31.29533, 31.14104, 31.033, 30.95522, 30.7452, 30.6161, 30.48558, 30.20304,
 29.94876, 29.49816, 28.99673, 28.47641, 27.75036, 26.98692, 26.22662, 25.29733,
 24.45699, 23.47883, 22.421, 21.46149, 20.50521, 19.55747, 18.71905, 17.97059,
 17.4616, 17.15413, 17.02539, 17.23645, 17.69518, 18.47265, 19.49916, 20.87392,
 22.47629, 24.34076, 26.46264, 28.66842, 31.13522, 33.57669, 35.95129, 38.50984,
 40.9788, 43.45954, 45.54811, 47.72132, 49.50215, 51.28018, 52.67683, 53.87601,
 54.98996, 55.89579, 56.45095, 56.88656, 57.15155, 57.16919, 57.04115, 56.87761,
 56.42096, 55.93649, 55.2568, 54.47306, 53.79956, 52.8701, 51.84985, 50.93586,
 49.95632, 48.73087, 47.77627, 46.75819, 45.54977, 44.36957, 43.32188, 42.29313,
 41.24385, 40.14291, 39.15614, 38.17805, 37.27126, 36.13561, 35.32942, 34.35569,
 33.69126, 32.67565, 31.91131, 31.0636, 30.32011, 29.60982, 28.88217, 28.10989,
 27.56996, 27.03619, 26.36284, 25.82758, 25.27555, 24.80477, 24.25029, 23.74979,
 23.31028, 22.95834, 22.56406, 22.13128, 21.81209, 21.42739, 21.12386, 20.8205,
 20.52693, 20.26264, 19.94682, 19.74871, 19.47004, 19.28826, 19.09282, 18.8813,
 18.69543, 18.51512, 18.37025, 18.21213, 18.09597, 18.00692, 17.84771, 17.7365,
 17.70439, 17.54311, 17.50521, 17.42641, 17.32607, 17.29374, 17.17156, 17.14076,
 17.18559, 17.12909, 17.11519, 17.06809, 17.05098, 17.06691, 17.02511, 17.01555,
 17.07787, 17.05032, 17.05407, 17.06751, 17.12841, 17.12312, 17.16593, 17.21924,
 17.19979, 17.25681, 17.31144, 17.36246, 17.43259, 17.43767, 17.5086, 17.58345, 
 17.62989, 17.70608, 17.70383, 17.81441, 17.82661, 17.8836, 18.00816, 18.05311,
 18.16044, 18.19468, 18.24426, 18.32978, 18.41256, 18.47817, 18.57559, 18.6523,
 18.71417, 18.79602, 18.89392, 18.96791, 19.0598, 19.17692, 19.25897, 19.33334,
 19.45276, 19.56273, 19.63092, 19.71592, 19.83377, 19.91831, 19.97547, 20.07111,
 20.15791, 20.23325, 20.38081, 20.49393, 20.54687, 20.62749, 20.70332, 20.81285,
 20.87916, 21.01356, 21.07556, 21.19642, 21.26882, 21.35373, 21.45083, 21.55625, 
 21.66463, 21.75115, 21.8033, 21.9497, 22.06961, 22.1253, 22.20523, 22.32333,
 22.41526, 22.50364, 22.62715, 22.70702, 22.80392, 22.89037, 23.02072, 23.12152,
 23.18633, 23.29179, 23.39558, 23.4171, 23.56042, 23.59962, 23.76348, 23.7985, 
 23.93591, 23.97028, 24.04745, 24.12475]
axe=np.linspace(21*60,25*60-1,25*60-21*60)/60
lowess = sm.nonparametric.lowess
z=lowess(y, axe, frac=11/len(axe),it=1)
Y=[]
for i in z:
Y.append(i[1])
fig, ax = plt.subplots(figsize=(14,8))
ax.plot(axe,y,linewidth=3,color='red')
ax.plot(axe,Y,linewidth=3,color='green')
######## plt.xlim(21.5,22)
plt.xlabel("x")
plt.ylabel("y")
plt.show()

![lowess_problem](https://user-images.githubusercontent.com/44851540/132503900-8f6c26ff-30da-4a6f-be1c-d5a1dd1d5ca5.png)

**Comment by josef-pkt** [comment]
the example doesn't work

```
ValueError: exog and endog must have same length

len(y), axe.shape
(240, (400,))
```

**Comment by josef-pkt** [comment]
After truncating `axe = axe[:len(y)]` , I get the same/similar results.

Strangely, the spikes only show up when `it=1`. Using 0, 2 or 3 iteration has a good match to the function without spikes.

With it = 3, there is one tiny spike and match at peak is weaker than with 0 or 2 iterations.

**Comment by josef-pkt** [comment]
**changing frac**

Doubling frac `2 * 11/len(axe)`, has nonsmooth parts, several extra fluctuations or medium size spikes with it=1. With it=0, the fit is smooth but oversmooths.

Reducing frac by half `frac=0.5 * 11/len(axe)`, fit is very good for all it from 0 to 3.

**adding noise**

Adding small noise still leaves a spike at it=1, e.g.

```
y = y + 0.05 * np.random.randn(len(y))
z=lowess(y, axe, frac=1 * 11/len(axe),it=1)
```

with larger noise, `y = y + 0.1 * np.random.randn(len(y))`, the fit with it=1 is smooth except for one small bump/spike at trough.

**Comment by josef-pkt** [comment]
another:

**changing scale of x**

reducing scale leaves only 2 tiny spikes or local fluctuations with it=10 
```
axe=np.linspace(2160,2560-1,2560-2160)/600  # instead of /6-
axe = axe[:len(y)]
```

demeaning x (without rescaling) has no (visible) effect (which sounds correct)

Making scale smaller by another factor 10, `axe=np.linspace(2160,2560-1,2560-2160)/6000` 
Then fit has spikes again at it=1, but also one large spike at it=3, but none at it= 0 or 2.

**Comment by josef-pkt** [comment]
I'm not sure this is a bug or a "feature".

lowess, outlier robust estimators of this kind are sensitive to corner cases, and might end up in local minima.
This might be the case here, because the behavior is not robust to changing the setting.

I don't know if we can prevent this. It should not be difficult to identify cases with huge outlying predictions or spikes like this.

**Comment by tgbrooks** [comment]
I've looked into this and found that the problem is that we get a stretch of 0 weights and followed single nearly-zero weight (< 1e-13). The zero weights come, I believe, from having a very close fit along most of the curve and therefore the few places where it doesn't fit well get large `std_resid` (which gives weights = 0). Presumably the nearly-zero weight is similar but right on the borderline. (Shockingly this happens in two places in the example and seems to require having a residual that is between 0.9999995 and 1.0 of the threshold to get that small but non-zero weight. I might be missing something since that seems unlikely to happen by chance.)

On [this line](https://github.com/statsmodels/statsmodels/blob/77bb1d276c7d11bc8657497b4307aa7575c3e65c/statsmodels/nonparametric/_smoothers_lowess.pyx#L342) we see that there is a check for number of non-zero weights. If there are 1 or 0 non-zero weights, the `reg_ok` is set to `False` and the value is not fit (either filled with NaNs or the original values). We hit that with the stretches of 0s but not with the nearly-zero epsilon value. Therefore I think the resolution is to replace that check with a check for nearly-zero using np.isclose(). Using the following looks good but I'll need to test it more:

``` python
    num_nonzero_weights = np.sum(np.isclose(weights[left_end:right_end], 0) == False)

    if num_nonzero_weights < 2:
        # Need at least 2 non-zero weights to get an okay regression fit
        # see 1960
        reg_ok = False
```

**Comment by bashtage** [comment]
That sounds like a good solution; should this be a user tunable parameter?  Checking for exact 0 is often a bad idea. Should there be a tolerance around a check?

**Comment by josef-pkt** [comment]
@tgbrooks Thanks for digging into this

np.isclose has default `atol=1e-08`
Isn't this too large as threshold?

We are close to releasing 0.13. 
Adding the isclose check sounds safe enough to change the code for this release. However, I'm not really familiar with those parts.

**Comment by tgbrooks** [comment]
I agree that it's not necessarily a good choice for a threshold. There's really two cases here that could be a problem:

1. We have no weights that are far from non-zero. Use an absolute threshold, though I'm not sure what (probably smaller than 1e-8).

2. We have one non-epsilon weight plus some number of 'epsilon' weights. Then maybe the threshold should be based off the non-zero weight with a relative threshold.

(If we have two non-epsilons then we're already OK.)

Maybe something like:

```
max_weight = np.max(weights[left_end:right_end])
epsilon = max(max_weight*1e-5, 1e-12) # not sure what the constants should be though
num_nonzero_weights = np.sum( np.isclose(weight[left_end:right_end], 0, atol=epsilon) == False )
```

**Comment by josef-pkt** [comment]
also given that this is in cython wouldn't it be simpler to replace the 0 by something larger than 0 (instead of going through np.isclose) in
`if sum_weights <= 0.0 or (np.sum(weights[left_end:right_end] != 0) == 1):`

e.g.
`if sum_weights <= 1e-12 or (np.sum(weights[left_end:right_end] < 1e-13) < 2):`
or just the second part

Using relative weights sounds fine, but I guess it could be smaller than 1e-5.
I don't see code that directly normalizes weights like weights / sum_weights. 

Looking a bit further:
After line 423, it might be better to put also a positive minimum on `weighted_sqdev_x`
That would directly prevent the zero division.

**Comment by josef-pkt** [comment]
putting a strictly positive minimum on `weighted_sqdev_x`  might solve #2449  (avoiding 0/0 )

**Comment by tgbrooks** [comment]
Normalizing the weights to sum to 1 is done on line [348](https://github.com/statsmodels/statsmodels/blob/77bb1d276c7d11bc8657497b4307aa7575c3e65c/statsmodels/nonparametric/_smoothers_lowess.pyx#L348).

Weights are near zero either due to residuals being large or due to being near the edge of the considered x-values. Since anything beyond these thresholds gets a weight of exactly 0, I think it's okay to also treat ones very close to a threshold as zero. In that sense I think a relatively high tolerance value is fine.  (There's even some old commented-out code that does this for the first case in `calculate_residual_weights`.)

Since weights are capped at 1, I guess there's not actually much reason to use a relative tolerance threshold. For the absolute tolerance, since I think it's fine for it to be relatively large, I'd propose just using the same 1e-8 that `np.isclose` uses, for lack of a clear alternative.

On user tunability: that doesn't sound too important to me. The magic 6-times-the-median threshold on residuals would be the more natural thing to tweak for the residual weights instead. For weighting by x value, tweaking `frac` is probably more important and natural.

I also think that forcing `weighted_sqdev_x` to be positive would be a good idea. That nicely reduces it to a weighted average in the case of all the `x` values being identical. While this would also remove the outlier points in this issue as well, I think we'd still want to fix the check for 0 weights (regression off a single point isn't right even if it won't blow up anymore). I don't know what the minimum for `weighted_sqdev_x` should be, but making it larger can only move the fit value closer to the weighted mean of the y values, which should be reasonable. So I think the choice for this is flexible and fine to also make relatively large.

**Comment by josef-pkt** [comment]
Can you make a PR that can still go into 0.13?
with the two changes weights close to zero and lower bound on weighted_sqdev_x

If we make the change just before the release, then a lower threshold (like 1e-12) would be safer because it will only have an effect in extreme cases.

I'm not sure that 1e-8 doesn't have visible consequences that we might want to look at before increasing the threshold in a release.
e.g. cases where weights of all observations in neighborhood are very small.

**Comment by tgbrooks** [comment]
Sounds good. Should we leave the `weighted_sqdev_x` change to a separate PR?

**Comment by josef-pkt** [comment]
both changes for this can be in one PR
If we agree on the changes, then it's easier to do it in one and won't cause a delay

**Comment by tgbrooks** [comment]
Okay great. I'll use 1e-12 for both changes. Is there are recommendation for where to put this 'magic constant'? I am just putting it inline at the moment e.g. `weights[left_end:right_end] < 1e-12` but not sure if there is anywhere better.

**Comment by josef-pkt** [comment]
inline is fine.

For my practice, I don't like having to look somewhere for what the tol is, unless it's a floating point eps definition, or we use  the same constant in many different places.
