### ISSUE TITLE
proportion_chisquare_*pairs* functions mistaken docstring

### ISSUE THREAD

**Issue by Daedalos** [statsmodels/statsmodels#7776]
https://github.com/statsmodels/statsmodels/blob/f67fc16d581767c030b6f191cf650c3a69d9ed5d/statsmodels/stats/proportion.py#L982
https://github.com/statsmodels/statsmodels/blob/f67fc16d581767c030b6f191cf650c3a69d9ed5d/statsmodels/stats/proportion.py#L1024

I may be mistaken, but I think these docs are wrong.  Idon't think this parameter is actually used in either of these chisquare "all" functions.  It looks like maybe it was intended to be a control, which should only apply to the second function, but _proportions_chisquare_pairscontrol_ specifies that the control is assumed to be the first element of the count and nobs arrays.

Never done a pull request so i'm not actually sure the process to suggest the correction

**Comment by josef-pkt** [comment]
Thanks for reporting.

I guess it's a copy paste error

For this you could try the `edit` icon when viewing the file in `main`. AFAIK, it will automatically create a pull request.
(I never tried it myself)
https://github.com/statsmodels/statsmodels/edit/main/statsmodels/stats/proportion.py

But it's also useful to learn how to do a full pull request on github, because by now most "action" for opensource, and for personal version control, is on github.

**Comment by josef-pkt** [comment]
I think you can edit this in your repo ( I never tried this either)
hit edit link in
https://github.com/Daedalos/statsmodels/blob/patch-1/statsmodels/stats/proportion.py

and add this before multitest_method line 1021

```
value : None
    ``value`` option is currently not implemented.
```
