### ISSUE TITLE
Change value of result

### ISSUE THREAD

**Issue by christian-hobelsberger** [statsmodels/statsmodels#7910]
Hi,

Is it possible to change the (seasonal-)value of a statsmodels.tsa.forecasting.stl.STLForecastResults object?
If not, is the saisonality even factored in when using .forecast() or could i add additional seasonal component after?

Thanks,
Chris

**Comment by bashtage** [comment]
Can you provide code to explain what you are trying to do?  I don't fully follow.

**Comment by christian-hobelsberger** [comment]
Hi! I basicly am trying to add seasionality to an statsmodels.tsa.forecasting.stl.STLForecastResults object. So after fitting:
`dec_df.fit()
dec_df.result.seasonal += value`
how can i edit the values of a statsmodels.tsa.forecasting.stl.STLForecastResults object?

**Comment by bashtage** [comment]
You could probably alter `res._result._seasonal`, but this isn't supported.  What are you trying to accomplish?  Can you not just apply the alteration after the fact?

**Comment by christian-hobelsberger** [comment]
Thanks for the answer! I am trying to use .forecast afterwards. Or is additional Seasionality irrelevant and i can add it after the forecast? Thank you 😊

**Comment by bashtage** [comment]
The forecast is just the model based forecast + the seasonality. 

https://github.com/statsmodels/statsmodels/blob/8a39cac4f91fc8301c8148d014d0f0d52e5e2ab0/statsmodels/tsa/forecasting/stl.py#L451-L453

It is easy to subtract the seasonality and then add in whatever you want.

I'm going to close this as it seems to be answered and I don't think there is a strong case for allowing official overriding the seasonality since it can be simply worked around.  

You can get the seasonality (but not set it) using `res.result.seasonal`.
