### ISSUE TITLE
How to handle two periods in STL?

### ISSUE THREAD

**Issue by tobtietze** [statsmodels/statsmodels#7942]
Hi,

I am wondering what the best way is to do a STL decomposition when you have seasonality in two different periods and not just one.

The fit() method of the STL itself can only take one period at a time, so our idea was to use one after each other, that is to say in case of the additive mode:

- fit the STL with the first period
- subtract the seasonal component from the original time series
- fit the deseasonalized time series with the second period
- use this trend and residual component as well as the sum of both seasonal components

With this procedure, the composite seasonal component together with the trend and residual component add up to the original time series.

Is this approach reasonable or is there a better way?

Any opinions are welcome and highly appreciated. Thank you!

**Comment by bashtage** [comment]
That sounds reasonable since it is an additive decomposition.  The "risk" with using a repeated procedure is the some of the seasonality for the 2nd period will leak into the first.  You should check whether it makes sense to fit the slow or fast seasonal first since you should get different results.  It might depend on what you want to do with this as to which is more sensible.  You could also try a Monte Carlo where you know the ground truth to see which works better.

**Comment by bashtage** [comment]
Going to close as answered since there is no action for us.  Hally to continue if you have more questions.
