### ISSUE TITLE
have a constant term for regression by default

### ISSUE THREAD

**Issue by zchu13** [statsmodels/statsmodels#8223]
#### Is your feature request related to a problem? Please describe
been using the statsmodels to run regression for a while, everytime i run a regression i need to do smi.add_constant to include intercept.. I just think this is super unproductive and sometimes cause mistakes if I forgot to add

#### Describe the solution you'd like
maybe just with constant as default setting when run regression. I think it should apply to most of the case, if not all

**Comment by josef-pkt** [comment]
This decision has been taken a long time ago and will not be changed anymore.
The formula has adds a constant by default for convenience.

In general, if you are working with DataFrames, then you can just add a constant column of ones and use it like other explanatory variables.

The default will not change also because of backwards compatibility.

We could add a new keyword `add_constant=False` but that would not even save in typing
`OLS(y, x add_constant=True)`
`OLS(y, add_constant(x))`
