### ISSUE TITLE
DESIGN: Prediction intervals in tsa

### ISSUE THREAD

**Issue by tgsmith61591** [statsmodels/statsmodels#8230]
This is in reference to a question that was recently raised on the [pmdarima](https://github.com/alkaline-ml/pmdarima/issues/489) issue board.

The `OLS` predict results API gives the user access to prediction intervals. For instance:

```python
import pandas as pd
import statsmodels.api as sm
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
X = pd.DataFrame(housing["data"][:200, 0], columns=[housing["feature_names"][0]])
X = sm.add_constant(X)
y = pd.DataFrame(housing["target"][:200], columns=housing["target_names"])

mod = sm.OLS(y[1:], X[1:])
res = mod.fit()

pred = res.get_prediction(X[:1]).summary_frame(alpha=0.05)
print(pred)
#       mean   mean_se  mean_ci_lower  mean_ci_upper  obs_ci_lower  obs_ci_upper
# 0  3.92956  0.117469       3.697902       4.161218      2.711407      5.147713
```

My understanding is `[mean_ci_lower, mean_ci_upper]` are confidence intervals, and `[obs_ci_lower, obs_ci_upper]` are prediction intervals (please correct me if I'm wrong). This is achieved through the `regression.PredictionResults` wrapper class by toggling `obs=True` in the [`conf_int`](https://github.com/statsmodels/statsmodels/blob/main/statsmodels/regression/_prediction.py#L78) method:

```python
    def conf_int(self, obs=False, alpha=0.05):
        se = self.se_obs if obs else self.se_mean

        q = self.dist.ppf(1 - alpha / 2., *self.dist_args)
        lower = self.predicted_mean - q * se
        upper = self.predicted_mean + q * se
        return np.column_stack((lower, upper))
```

However, when making a prediction from a SARIMAX model, the [`conf_int`](https://github.com/statsmodels/statsmodels/blob/febb26785bc3de5f632cc0b2013209c82a261d87/statsmodels/tsa/base/prediction.py#L135) appears to _only_ produce the confidence interval, and not a prediction interval:

```python
    def conf_int(self, alpha=0.05):
        se = self.se_mean
        q = self.dist.ppf(1 - alpha / 2.0, *self.dist_args)
        lower = self.predicted_mean - q * se
        upper = self.predicted_mean + q * se
        ci = np.column_stack((lower, upper))
        if self._use_pandas:
            return self._wrap_pandas(ci, columns=["lower", "upper"])
        return ci
        
 ...
 
 In [34]: my_arima_model_results.summary_frame()
Out[34]:
y          mean      mean_se  mean_ci_lower  mean_ci_upper
0  24400.113989  5155.787408   14294.956357   34505.271621
1  25635.745117  5295.188186   15257.366982   36014.123252
2  25405.766858  5327.046350   14964.947868   35846.585848
3  25387.323173  5327.250634   14946.103794   35828.542551
4  25385.844035  5327.251947   14944.622082   35827.065989
5  25385.725412  5327.251956   14944.503442   35826.947382
```

I do not understand the statsmodels API well enough to grok what the equivalent to `se_obs` would be in this scenario, but it seems that's the missing element to being able to compute prediction intervals.

Is it possible to update the `tsa.base.PredictionResults` object to allow `obs=True` in the `conf_int` method?

**Comment by ChadFulton** [comment]
We recently had a discussion about this issue at https://groups.google.com/g/pystatsmodels/c/gLQVsoB6XXs. To briefly reiterate, here is how I understand the use of the terms that the issue you linked to is suggesting:

- "Confidence interval" (for the mean) takes into account the uncertainty from estimating the parameters, but not the uncertainty arising from the error term in the regression equation
- "Prediction interval" takes into account both of these features

In `SARIMAX`, we have not implemented a procedure to incorporate the uncertainty associated with estimating the parameters of the model. But note that R's `arima` and the `forecast` package `Arima` / `forecast` wrappers also do not take into account this uncertainty when creating intervals. And note that `SARIMAX`'s intervals agree with those from `Arima` / `forecast`.

Ultimately, the intervals produced by either `SARIMAX` (python) or `Arima` (R) don't fit either of the definitions above.  In some sense they are more like the "Prediction interval" term, because they *do* take into account the uncertainty arising from the error term (unlike the "Confidence interval" as described above). But it is not an exact match because they *don't* take into account parameter estimation uncertainty.

Finally, as I point out in the linked mailing list article, the term "confidence interval" is used generically in the state space model literature.  In Statsmodels (and R, actually), `SARIMAX` is implemented as part of the state space framework.

But we would be open to suggestions if there is something specific that is being proposed / requested.

-----------

**Example code**: here is code to estimate the same ARIMA model in both R and python so that you can check that the forecast intervals are the same.

```R
library(forecast)
dta <- Nile
dta = (dta - mean(dta)) / sd(dta)
res <- Arima(dta, order=c(1, 0, 0), include.mean=FALSE)
f = forecast(res, h=4, level=0.9)
```

```python
import numpy as np
import statsmodels.api as sm

dta = np.array([1120, 1160, 963, 1210, 1160, 1160, 813, 1230, 1370, 1140, 995, 935, 1110, 994, 1020,
                960, 1180, 799, 958, 1140, 1100, 1210, 1150, 1250, 1260, 1220, 1030, 1100, 774, 840,
                874, 694, 940, 833, 701, 916, 692, 1020, 1050, 969, 831, 726, 456, 824, 702,
                1120, 1100, 832, 764, 821, 768, 845, 864, 862, 698, 845, 744, 796, 1040, 759,
                781, 865, 845, 944, 984, 897, 822, 1010, 771, 676, 649, 846, 812, 742, 801,
                1040, 860, 874, 848, 890, 744, 749, 838, 1050, 918, 986, 797, 923, 975, 815,
                1020, 906, 901, 1170, 912, 746, 919, 718, 714, 740.])
dta -= dta.mean()
dta /= dta.std(ddof=1)
mod = sm.tsa.SARIMAX(dta, order=(1, 0, 0), concentrate_scale=True)
res = mod.fit(disp=0)
res.get_forecast(4).summary_frame(alpha=0.1)
```

**Comment by tgsmith61591** [comment]
@ChadFulton thank you for your excellent answer, and for linking the mail list discussion.
