### ISSUE TITLE
Help! How to extending the dynamic factor model with DynamicFactorMQ

### ISSUE THREAD

**Issue by ZJMXX** [statsmodels/statsmodels#8234]
#### Is your feature request related to a problem? Please describe
I wanna add some lagged values of factors into observed variables to DynamicFactorMQ as "https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_dfm_coincident.html" does. But the way in this link only supports DynamicFactor, the old version. 
I looked through the source code of DynamicFactorMQ, but it's not working by imitating the extending way of DynamicFactor. It doesn't go through the customized "transform_params" and "untransform_params" functions under EM algorithm, and the final params are the initial ones. It does work under other methods but pretty slowly.

--------------------------------
I guess the limitation comes from this function "def _em_maximization_obs_missing()". The equation comes from Banbura at al. (2011), but his original model didn't include lag factor loadings. So if we solve the matrix to get loadings, it can't take lag loadings into account? Just Guess XD.

#### Describe the solution you'd like
A few hints would be helpful. A clear example like the url's above would be excellent !

Appreciated!

**Comment by ChadFulton** [comment]
The `DynamicFactorMQ` model is not designed to be extended because, as you pointed out, it fits the parameters via the EM algorithm.  So extending the model would mean that you would need to modify the EM algorithm.  Unfortunately, we don't have any documentation or example notebooks explaining that.

I'm going to close as answered, but if you ended up trying this and had any follow up questions, feel free to keep commenting.
