### ISSUE TITLE
anova_lm() fails on ols model

### ISSUE THREAD

**Issue by dyc3** [statsmodels/statsmodels#8241]
#### Describe the bug

`anova_lm()` always gives me the following error:
```
AttributeError: 'PandasData' object has no attribute 'design_info'
```

related: #3958

#### Code Sample, a copy-pastable example if possible

CSV is attached here: 
[regression-data.csv](https://github.com/statsmodels/statsmodels/files/8542121/regression-data.csv)

```python
import statsmodels.api
df = pd.read_csv('regression-data.csv')
model = statsmodels.api.OLS(df["Father Height"], df["Student Height"], data=df).fit()
anova = statsmodels.api.stats.anova_lm(model, typ=2)
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `main`. If your problem has been fixed in an unreleased version, you might be able to use `main` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the main branch of this repository? It helps the limited resources if we know problems exist in the current main branch so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
Python: 3.9.2.final.0
OS: Linux 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.13.2 (/home/carson/anaconda3/envs/school/lib/python3.9/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.21.2 (/home/carson/anaconda3/envs/school/lib/python3.9/site-packages/numpy)
scipy: 1.6.3 (/home/carson/anaconda3/envs/school/lib/python3.9/site-packages/scipy)
pandas: 1.2.4 (/home/carson/anaconda3/envs/school/lib/python3.9/site-packages/pandas)
    dateutil: 2.8.1 (/home/carson/anaconda3/envs/school/lib/python3.9/site-packages/dateutil)
patsy: 0.5.2 (/home/carson/anaconda3/envs/school/lib/python3.9/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.4.1 (/home/carson/anaconda3/envs/school/lib/python3.9/site-packages/matplotlib)
    backend: Qt5Agg 
cvxopt: Not installed
joblib: 1.1.0 (/home/carson/anaconda3/envs/school/lib/python3.9/site-packages/joblib)

Developer Tools
================

IPython: 7.23.1 (/home/carson/anaconda3/envs/school/lib/python3.9/site-packages/IPython)
    jinja2: 2.11.3 (/home/carson/anaconda3/envs/school/lib/python3.9/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.9.0 (/home/carson/anaconda3/envs/school/lib/python3.9/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by josef-pkt** [comment]
First, you don't have a constant in the model. It's not automatically added if you provide arrays or dataframes directly.

try to use the formula interface.
My guess is that anova_lm requires the use of formulas. 
Otherwise, there would be not much purpose to using anova_lm, i.e. if there is no formula info, then all columns are considered as separate terms. The main advantage of anova_lm is that it properly handles categorical variables and their interactions.

If you have only one non-constant regressor, then the anova statistics are in the model results, e.g. fvalue and fpvalue.

**Comment by dyc3** [comment]
Using the formula API instead:
```python
model = statsmodels.formula.api.ols('"Father Height" ~ "Student Height"', data=df).fit()
```
I get the following error when calling `fit()`:
```
PatsyError: Number of rows mismatch between data argument and "Father Height" (26 versus 1)
    "Father Height" ~ "Student Height"
```

> First, you don't have a constant in the model.

Could you elaborate on this a little? Not sure what you mean.

**Comment by josef-pkt** [comment]
`model = statsmodels.formula.api.ols('Q("Father Height") ~ Q("Student Height")', data=df).fit()`

regressor names need to be valid python names in the formula.
If they are not then they need to be `Q`uoted

https://stackoverflow.com/questions/50623216/patsy-formula-when-variable-has-a-hypthen

> First, you don't have a constant in the model.
> Could you elaborate on this a little? Not sure what you mean.

When we use the standard array or dataframe interface `OLS`, instead of the formula interface, then statsmodels takes the design matrix  `exog` as given and does not add a constant nor make other changes to it.
i.e. the models take exog exactly as the user provided. If the user does not include a constant, then there is none in the regression.

There is a tool function `add_constant` for users to add a constant (column of ones) to an array or dataframe.

If you want to include a constant, then you need

df = sm.add_constant(df)
`model = statsmodels.api.OLS(df["Father Height"], df[["const", "Student Height"]], data=df).fit()`
or 
model = statsmodels.api.OLS(df["Father Height"], sm.add_constant(df["Student Height"]), data=df).fit()

**Comment by dyc3** [comment]
Ah, ok. Thanks!

**Comment by josef-pkt** [comment]
@Vaibhav9006  That's not a usable question?
which error, which model, which code?

**Comment by Vaibhav9006** [comment]
![image](https://user-images.githubusercontent.com/110875047/227241431-7b34cce8-5045-454c-92ea-6468b36f0d4d.png)

**Comment by sean-workman** [comment]
I appear to be encountering this issue. I am going through Introduction to Statistical Learning with Python and using the ModelSpec() function from their ISLP package to create my design matrices. I then use statsmodels to fit my linear model. The code snippet I am using is:

```
predictors = Auto.columns.drop(['mpg', 'name'])

X = MS(predictors).fit_transform(Auto)
y = Auto['mpg']

model = sm.OLS(y, X)
results = model.fit()
```

Trying to then use `anova_lm(results)` results in the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[233], line 1
----> 1 anova_lm(results)

File ~/miniconda3/envs/islp/lib/python3.10/site-packages/statsmodels/stats/anova.py:353, in anova_lm(*args, **kwargs)
    351 if len(args) == 1:
    352     model = args[0]
--> 353     return anova_single(model, **kwargs)
    355 if typ not in [1, "I"]:
    356     raise ValueError("Multiple models only supported for type I. "
    357                      "Got type %s" % str(typ))

File ~/miniconda3/envs/islp/lib/python3.10/site-packages/statsmodels/stats/anova.py:70, in anova_single(model, **kwargs)
     67 nobs = exog.shape[0]
     69 response_name = model.model.endog_names
---> 70 design_info = model.model.data.design_info
     71 exog_names = model.model.exog_names
     72 # +1 for resids

AttributeError: 'PandasData' object has no attribute 'design_info'
```

I am able to compare 2 or more results objects that were generated in this exact same way using `anova_lm()` just fine, but for a single model it throws this error. Based on the traceback and other posts in this thread I can see it has to do with design info, so does it really just come down to the fact that I didn't set up my model using a formula string? If that's the case, is that the desired behaviour?

**Comment by max-oppermann** [comment]
@sean-workman 
Had the same problem. Someone in the [forum](https://www.statlearning.com/forum) linked to a [page](https://islp.readthedocs.io/en/latest/models/anova.html) in the documentation for the ISLP library; if you scroll almost all the way down, you'll find the answer. Here is my adapted solution:

```python
predictors = Auto.columns.drop(['name', 'mpg'])
design = MS(predictors)
...
y = Auto['mpg']
...

anova = anova_lm(*[sm.OLS(y, D).fit() for D in design.build_sequence(Auto, anova_type='sequential')])
anova.index = design.names

```
The build_sequence() method is specifically for the ModelSpec class, [link](https://islp.readthedocs.io/en/latest/api/generated/ISLP.models.model_spec.html#ISLP.models.model_spec.ModelSpec.build_sequence). I found that overly concise and not very transparent (also that method hadn't been mentioned at all in the book). This gets you all the same F-values:

```python
import statsmodels.formula.api as smf

formula = ' + '.join(predictors)

model_auto2 = smf.ols(f'mpg ~ {formula}', data=Auto).fit()

anova_lm(model_auto2)
```

**Comment by sean-workman** [comment]
Thanks @max-oppermann!

**Comment by josef-pkt** [comment]
see also comments starting in https://github.com/statsmodels/statsmodels/issues/8994#issuecomment-1707268734
for why we don't support (yet) anova_lm for "terms" without formulas.

**Comment by sean-workman** [comment]
Oh interesting. My confusion definitely stems from the point that @jonathan-taylor raises. That is, there do seem to be terms available for the function to use since I am able to see those very terms in the `summary` output of the fitted results. But I can understand your point about interaction terms/categorical predictors with many possible values.

Is the simplest approach probably to just use the formulas whenever possible?
