### ISSUE TITLE
Whitening transformation in sm.GLS()

### ISSUE THREAD

**Issue by Wainberg** [statsmodels/statsmodels#8348]
When calculating the 'warping matrix' for GLS, you're supposed to take the inverse of the Cholesky decomposition of the covariance matrix (see https://en.wikipedia.org/wiki/Generalized_least_squares#Properties for a description of why). 

https://github.com/statsmodels/statsmodels/blob/main/statsmodels/regression/linear_model.py#L181 incorrectly switches the order of the two operations and takes the Cholesky decomposition of the inverse instead:

`cholsigmainv = np.linalg.cholesky(np.linalg.inv(sigma)).T`

The correct code should be:

`cholsigmainv = np.linalg.inv(np.linalg.cholesky(sigma)).T`

The comment to the function has it correct: "Returns sigma (matrix, nobs by nobs) for GLS and the inverse of its Cholesky decomposition." It's just that the code doesn't match the comment.

While you're at it, might be worth renaming `cholsigmainv` (which I read as "Cholesky of sigma inverse") to `invcholsigma` ("inverse of Cholesky of sigma") or some other more descriptive term.

**Comment by ChadFulton** [comment]
This is not a bug, but just two ways to perform whitening. To see this, notice that:

1. We can perform a Cholesky factorization on the matrix itself:  $\Omega = C'C$
2. Or on the inverse: $\Omega^{-1} = L' L$

From this, there are two ways to transform $\Omega$ to the identity:

1. $C \Omega^{-1} C' = I$
2. $(L')^{-1} \Omega^{-1} L^{-1} = I$

This is important, because given the

**Comment by ChadFulton** [comment]
(Sorry for the duplicate, hit enter too quickly before)

This is not a bug, but just two ways to perform whitening. To see this, notice that:

1. We can perform a Cholesky factorization on the matrix itself:  $\Omega = C C'$, which implies $\Omega^{-1} = (C')^{-1} C^{-1}$
2. Or on the inverse: $\Omega^{-1} = L L'$

From this, there are two ways to transform $\Omega$ to the identity:

1. $C' \Omega^{-1} C = I$
2. $L^{-1} \Omega^{-1} (L')^{-1} = I$

This is important, because given the GLS equation:

$$(y - X b)' \Omega^{-1} (y - X b)$$

we can rewrite it as:

$$(y - X b)' (C')^{-1} C' \Omega^{-1} C C^{-1} (y - X b) = (y^* - X^* b)' (y^* - X^* b)$$

or as

$$(y - X b)' L (L)^{-1} \Omega^{-1} (L')^{-1} L' (y - X b) = (y^\dagger - X^\dagger b)' (y^\dagger - X^\dagger b)$$

where

- $y^* = C^{-1} y$
- $y^\dagger = L' y$

in both cases, the data have been whitened to accommodate GLS.

**Comment by Wainberg** [comment]
Neat, thanks for clarifying. So, not a bug after all!

So, replacing `np.linalg.cholesky(np.linalg.inv(sigma)).T` (with the transpose) with `np.linalg.inv(np.linalg.cholesky(sigma))` (without the transpose) would also be correct? But `np.linalg.inv(np.linalg.cholesky(sigma)).T` would be incorrect?

**Comment by bashtage** [comment]
The key liner algebra result is that inv(AB) = inv(B)inv(A).  

Going to close as answered (and not a bug).

**Comment by Wainberg** [comment]
Hmm... I wouldn't say the equivalence between $C^{-1}$ and $L'$ (to use Chad's notation) follows straight-forwardly from inv(AB) = inv(B)inv(A). I appreciated the thoroughness of Chad's explanation.
