### ISSUE TITLE
Question: how are the default ARIMA start_params defined?

### ISSUE THREAD

**Issue by holder-fo** [statsmodels/statsmodels#8445]
when i fit one model with ARIMA-type model, there are `start_params` we can use and where the default is given by ` Model.start_params`. 
sorry for that i am new to this and need to understand how this ` Model.start_params` works and what it would be given by default? would you be kind to elaborate it or guide me with detailed documenst\references that i can dive in?

**Comment by ChadFulton** [comment]
Because the parameters of the ARIMA models are estimated by numerically maximizing the likelihood function, we must have some procedure for generating a set of initial parameters for any model combination. At the same time, numerical optimization can perform poorly if the starting parameters are far away from the true optimal parameters.

For ARIMA models, the default starting parameters are estimated using an approach that is based on the Hannan-Rissanen method (which essentially constructs parameter estimates using least-squares approaches).  Because there are so many possible model combinations, it is difficult to summarize all the details, but you can find the specific implementation here: https://github.com/statsmodels/statsmodels/blob/main/statsmodels/tsa/statespace/sarimax.py#L910

Closing this issue as answered, but feel free to follow up if you have additional questions.
