### ISSUE TITLE
how to set bounds for each parameter when doing sarimax.fit

### ISSUE THREAD

**Issue by holder-fo** [statsmodels/statsmodels#8460]
hi, @ChadFulton sorrry i didn't find any specific document to clarify how to set bounds for each parameter in `sarimax.fit`. 
is it just like the way exactly in [scipy.optimize.minimize](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html)?
if not so, how should i do this? it's appreciated if you can show me a simple example.

**Comment by ChadFulton** [comment]
Unfortunately, setting bounds on parameters via `scipy.optimize.minimize` arguments is not supported in SARIMAX.  This is because we already bound the parameter space using parameter transformations.  You can impose additional bounds by subclassing the SARIMAX class; some details about how this would work can be found in [this mailing list discussion](https://groups.google.com/g/pystatsmodels/c/n8mDxfr8d1o).

**Comment by holder-fo** [comment]
@ChadFulton thanks for your revelation. but i bumped into another problem when doing `untransform_params`, there is few `nan`s popped up, what could i do to avoid this?
