### ISSUE TITLE
FAQ-D/DOC: linking to notebook examples

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#8496]
(I didn't find an issue when I tried to remember or figure out how to do this)

We can link to the notebook examples using relative links

for example

Link from a rst page

in `treatment.rst`
```
See also overview notebook in
`Treatment Effect <examples/notebooks/generated/treatment_effect.html>`__
```

Link from a docstring:

in class docstring of `statsmodels.treatment.treatment_effects.TreatmentEffect`
```
See `Treatment Effect notebook
<../examples/notebooks/generated/treatment_effect.html>`__
for an overview.
```

**Comment by PavloFesenko** [comment]
Adding a task list based on groups of notebook examples since there are quite a lot of them.

- [ ] Linear Regression Models
- [ ] Plotting
- [ ] Discrete Choice Models
- [ ] Nonparametric Statistics
- [ ] Generalized Linear Models
- [ ] Robust Regression
- [ ] Generalized Estimating Equations
- [ ] Statistics
- [ ] Time Series Analysis
- [ ] State space models
- [ ] State space models - Technical notes
- [ ] Forecasting
- [ ] Multivariate Methods
- [ ] User Notes

**Comment by PavloFesenko** [comment]
@josef-pkt The notebook [Autoregressive Distributed Lag (ARDL) models](https://github.com/statsmodels/statsmodels/blob/main/examples/notebooks/autoregressive_distributed_lag.ipynb) doesn't seem to be properly rendered (see [here](https://www.statsmodels.org/stable/examples/notebooks/generated/autoregressive_distributed_lag.html)). Do you know what could be the issue?
