### ISSUE TITLE
BUG:  AttributeError: 'TreatmentEffectResults' object has no attribute 'pvalue'

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#8614]
#### Describe the bug

Bug in test code producing 5 failed tests.

See Azure runs.

@josef-pkt

**Comment by josef-pkt** [comment]
this is a consequence of adding super call in #8608
https://github.com/statsmodels/statsmodels/pull/8608/files#diff-1df1e5f62a25bbedf5a3c05feedbed636e69faf8cfd7102905448dfed12ff693R549

those unit tests fail in that PR

Instead of calling super, I updated the `__dict__` directly
```
tt = results_gmm.t_test(constraints)
self.__dict__.update(tt.__dict__) 
```

I don't remember why I did this this way. 
I guess I was treating ContrastResults class as mixin without needing `__init__`, just to inherit some methods.

Do you remember what the doc build problem was that you added the `super.__init__` call in 8608 ?

Independent of this, fixing the contrast results class in #8615 is good to correct the undefined attribute
(I'm not sure what we need in that `else` part. )

**Comment by josef-pkt** [comment]
`TreatmentEffectResults` has no class docstring
