### ISSUE TITLE
BUG: statsmodels.stats.multitest.fdrcorrection_twostage sometimes returns values in wrong order and gives values above 1

### ISSUE THREAD

**Issue by nevubm** [statsmodels/statsmodels#8619]
test case:
```
>>> import statsmodels.stats.multitest
>>> import numpy as np
>>> test=np.array([0.2, 0.8, 0.3, 0.5, 1])
>>> statsmodels.stats.multitest.fdrcorrection_twostage(test, alpha=0.05, method='bky')[1]
array([0.7875, 0.7875, 0.875 , 1.05  , 1.05  ])
>>> statsmodels.stats.multitest.multipletests(test, alpha=0.05, method='fdr_tsbky')[1]
array([0.7875, 1.    , 0.7875, 0.875 , 1.    ])
```
There are two issues with `fdrcorrection_twostage`
1. it sometimes but not always returns results in sorted order, which does not mach input order. The behavior is inconsistent and depends on values in the input array
2. it returns values above 1

results from `fdrcorrection_twostage` and `multipletests` should match but only results from `multipletests` seems to be correct compared to results from Prism

**Comment by josef-pkt** [comment]
Thanks for reporting.

Looks like a bug, but it's not clear to me yet why. It has the same rearranging code like fdrcorrection and multipletests.

if there is one rejection, then it seems to work

```
test=np.array([0.2, 0.8, 0.3, 0.5, 0.9, 1e-3])
res1 = statsmodels.stats.multitest.fdrcorrection_twostage(test, alpha=0.05, method='bky')[1]
print(test)
res2 = statsmodels.stats.multitest.multipletests(test, alpha=0.05, method='fdr_tsbky')[1]
res1, res2
[0.2   0.8   0.3   0.5   0.9   0.001]
(array([0.525  , 0.7875 , 0.525  , 0.65625, 0.7875 , 0.00525]),
 array([0.525  , 0.7875 , 0.525  , 0.65625, 0.7875 , 0.00525]))
```

**Comment by josef-pkt** [comment]
found it:

if no rejection, then there is an early return that doesn't reorder the result

```
    r1 = rej.sum()
    if (r1 == 0) or (r1 == ntests):
        return rej, pvalscorr * fact, ntests - r1, alpha_stages
```

Also it looks like `multipletests` does not support `iter` keyword for fdr twostage.

aside: both fdrcorrection method always reorder if not is_sorted, no option for turning it off as in multipletest function.

**Comment by josef-pkt** [comment]
possible fixes

- make large if else block, i.e. iterate in else block, or
- keep early return and write helper function for reordering of return arrays

the first is cleaner if we want to change the return, e.g. to HolderTuple, but maybe we only change the return of `multipletests`.

other possible changes
- `iter` is reserved word, rename to `iterate`
- add `fdrts_iterate` (or similar name) keyword to `multipletests` and forward to fdr two-stage
- privatize the two fdr functions, I guess not

**Comment by nevubm** [comment]
> Can you check some additional results with Prism, if you have that?
> 
> a current unit test uses the following uncorrected pvalues pvals = [ 0.0001, 0.0004, 0.0019, 0.0095, 0.0201, 0.0278, 0.0298, 0.0344, 0.0459, 0.3240, 0.4262, 0.5719, 0.6528, 0.7590, 1.000]

This is the output from Prism 9.4.1, using two stage BKY
P value | q value
-- | --
0.0001 | 0.0012
0.0004 | 0.0023
0.0019 | 0.0073
0.0095 | 0.0274
0.0201 | 0.0464
0.0278 | 0.0492
0.0298 | 0.0492
0.0344 | 0.0497
0.0459 | 0.0589
0.3240 | 0.3742
0.4262 | 0.4475
0.5719 | 0.5505
0.6528 | 0.5800
0.7590 | 0.6262
1.0000 | 0.7700

For the unit tests, it would be a good idea to shuffle the input order a couples times instead of feeding it in sorted order, to check the output order.

Also, are the values above 1 related to the sorting or is that a different issue?

**Comment by nevubm** [comment]
Since you're already thinking about this, I have quick a question. Having separate `fdrcorrection_twostage`, `fdrcorrection`, and `multipletests` that do a lot of the same thing was always a bit confusing for me. Is not the main difference that `fdrcorrection_twostage` can do more than 2 stages with `iter`? And `fdrcorrection` seems fully redundant with `multipletests`. Would it be possible to combine these functions into a single function in a way that makes sense?

**Comment by josef-pkt** [comment]
Thanks for the reference numbers

I have not yet checked why pvalue can be >1
The `fdrcorrection` function uses `pvals_corrected[pvals_corrected>1] = 1` but I don't see yet why pvalues can still be >1

```
test=np.array([0.2, 0.8, 0.3, 0.5, 0.9999999])
res1 = statsmodels.stats.multitest.fdrcorrection_twostage(test, alpha=0.05, method='bky')[1]
print(test)
res2 = statsmodels.stats.multitest.multipletests(test, alpha=0.05, method='fdr_tsbky')[1]
res1, res2
[0.2       0.8       0.3       0.5       0.9999999]
(array([0.7875   , 0.7875   , 0.875    , 1.0499999, 1.0499999]),
 array([0.7875, 1.    , 0.7875, 0.875 , 1.    ]))
```

**Comment by josef-pkt** [comment]
> Having separate fdrcorrection_twostage, fdrcorrection, and multipletests that do a lot of the same thing

`multipletests` delegates to the two fdrcorrection functions. I split those out because those computation are much longer than the non-fdr methods.
Essentially, `multipletests` is supposed to be the main public function, the fdrcorrection functions are implementation details.
But because those are not private (no leading underscore), we ended up adding the supporting code like sorting, reordering and pvalue>1 checks to all three functions (and need to finish that for the two-stage fdr).

The multiple testing functions are pretty old. Because this bug hasn't been reported yet, I guess that most users use `multipletests` which does not have the bugs.

After we add the `iter` option for two-stage fdr to multipletests, then there is no reason anymore to use the fdrcorrection functions directly.

**Comment by josef-pkt** [comment]
related: should we have `maxiter` (int or boolean) instead of `iter` (boolean)?

Current `iter` is binary, either no iteration or iterate to convergence. Loop has at most ntests iterations, AFAICS, possible ri=0,...,ntests.
It would be possible to allow just one or two iterations using maxiter.
e.g. 
If maxiter is in {True, False}, then current no are complete iteration
If maxiter is int or not boolean, then stop at maxiter unless already converged before maxiter (as in optimization loops)

**Comment by nevubm** [comment]
`maxiter` seems more complete and flexible, and you can have `maxiter=-1` for no limit/until convergence, `0` for no iteration (default), and any other integer specifies number of iterations

**Comment by josef-pkt** [comment]
another problem that currently the twostage fdrcorrection function is not redundant:
multipletest does not return 2 extra returns from fdrcorrection: m0 estimated number of true hypotheses and alphastages.
m0 can be inferred from other returns, but not alphastages

need holdertuple to allow for extra returns
for more iteration, then twostage, the number of iterations can be inferred from len(alphastages).
Given that we only have a finite number of possible iteration, a `converged` indicator is not needed because we always converge (endless loops are ruled out by code, number of rejections can only increase, raises exception if it decreases)

**Comment by josef-pkt** [comment]
performance:

fdrcorrection_twostage calls fdrcorrection inside the iteration loop with updated alphastar.
However, the only need for alpha is for the rejection decision. corrected pvalues in fdrcorrection are independent of alpha.
This mean, we only need to compute the fdr corrected p-values once and compare those with different alphastar.

Related: **prior true fraction**
we should still add an option to use prior information on the number or fraction of true/non-rejected hypothesis to `fdrcorrection`.
Currently that is in a docstring comment:
"    If there is prior information on the fraction of true hypothesis, then alpha
    should be set to ``alpha * m/m_0`` where m is the number of tests,
    given by the p-values, and m_0 is an estimate of the true hypothesis.
    (see Benjamini, Krieger and Yekuteli)
"

If we do that, then pvals_corrected would be corrected in a similar way as in fdrcorrection_twostage.

Found while writing unit tests for maxiter=0 and my initial thought was that this should agree with `fdrcorrection` but doesn't.

AFAICS, fdrcorrection assumes `fraction_true=1` when computing pvals_corrected

I guess this is still a leftover because the original articles where in terms of rejection decisions and not in terms of corrected pvalues.

i.e. we want fdrcorrection to return corrected pvalues that can be compared with original alpha (e.g. 0.05) for any provided m0.
`pvals_corrected = fdrpvalscorr(fraction_true=1) * fraction_true`  (not verified, but should be correct)

**Comment by josef-pkt** [comment]
aside: graphpad prism has a third fdr version that does not assume nonnegative correlation

https://www.graphpad.com/guides/prism/latest/statistics/stat_pros_and_cons_of_the_three_met.htm :

"""
Corrected method of  Benjamini & Yakutieli (3)
This method requires no assumptions about how the various comparisons correlate with each other. But the price of this is that is has less power, so identifies fewer comparisons as being a discovery. Another way of saying this is that the method is very conservative.  

...
3.Benjamini, Y., & Yekutieli, D. (2001). [The control of the false discovery rate in multiple testing under dependency](http://projecteuclid.org/euclid.aos/1013699998). Annals of statistics, 1165–1188.
"""

from the abstrat of the BY 2001 article

"
For all other forms of dependency, a simple conservative modification of the procedure controls the false discovery rate.
"
