### ISSUE TITLE
BUG: out-of-sample prediction with nan values get unexpected result

### ISSUE THREAD

**Issue by lambdaphy** [statsmodels/statsmodels#8726]
This is an OLS regression model from [this page](https://www.statsmodels.org/stable/example_formulas.html):
```
import statsmodels.api as sm
import statsmodels.formula.api as smf
import numpy as np
import pandas as pd

# example from https://www.statsmodels.org/stable/example_formulas.html
df = sm.datasets.get_rdataset("Guerry", "HistData").data
df = df[['Lottery', 'Literacy', 'Wealth', 'Region']].dropna()
mod = smf.ols(formula='Lottery ~ Literacy', data=df)
res = mod.fit()
```
When this model is fitted, we can use this model to predict: 

```
# out of sample prediction without NaN values. This works as expected.
res.predict(pd.Series([0,1,2,3], name='Literacy'))
```

But when we have NaN values in the exog data, the `predict()` method returns unexpected result, which is a pandas series with only NaN value indexed by None:
 
```
# ****out of sample prediction with NaN values. This gives a strange result!****
res.predict(pd.Series([0,1,2,None,3], name='Literacy'))
```

statsmodels: 0.13.5
pandas: 1.4.4
numpy: 1.23.5
python:3.9.16

**Comment by josef-pkt** [comment]
Thanks for reporting

`exog` need in general be 2-d,  but we have handling for 1-d, although this step is handled by patsy when formulas are used.

The bug is possibly in how we re-add the nan rows to the predict result, after patsy dropped those. Or, patsy is doing something strange in nan handling in Series.

```
res.predict(pd.Series([0,1,2,np.nan, 3], name='Literacy'))
None   NaN
dtype: float64

res.predict(pd.DataFrame([0,1,2,None,3], columns=['Literacy']))
0    64.238948
1    63.697226
2    63.155504
3          NaN
4    62.613781
dtype: float64


res.predict({'Literacy': [0,1,2,np.nan,3]})
0    64.238948
1    63.697226
2    63.155504
4    62.613781
dtype: float64
```

**Comment by josef-pkt** [comment]
We have index handling and convert Series exog to DataFrame, but convert only if we need to go through patsy `transform`.
However, we store the index before the conversion.

The bug is fixed if I store the index after conversion of Series to DataFrame in the transform path
`if isinstance(exog, pd.Series)`

PR with bug fix will come soon.
