### ISSUE TITLE
A little problem on statsmodels.formula.api

### ISSUE THREAD

**Issue by josinovmota** [statsmodels/statsmodels#8903]
I found out that OLS from statsmodels.formula.api is on lower case and it's uppercase on Statmodels.

```python
model = smf.OLS(formula = 'medv ~ lstat * age', data=df).fit()
```

When i did this, i got the error:

AttributeError: module 'statsmodels.formula.api' has no attribute 'OLS'

**Comment by bashtage** [comment]
The formula versions are always lower case since they are functions, not classes (`OLS`) is a class, `smf.ols` is a function that is really  `sm.OLS.from_formula`, i.e., `ols = sm.OLS.from_formula`.

This is standard Python syntax - `CapitalizedCamelCase` for classes, and `lower_case_underscore_separated` function names.
