### ISSUE TITLE
Correlation Coefficient nan when horizontal line

### ISSUE THREAD

**Issue by addejans** [statsmodels/statsmodels#8977]
#### Describe the bug

For `corrcoef` the provided code, there's a potential for division by zero in the expression self.cov / self.std / self.std[:, None] if any standard deviation (self.std) is zero. This would happen, for example, when you have a horizontal line (all y-values are constant).

To adjust the code to account for the case where the standard deviation might be zero, you can utilize numpy's np.where function to safely handle such cases.

Here's the modified code:

#### Code Sample, a copy-pastable example if possible

```python
data = pd.DataFrame({'x1': [200, 205, 280, 500, 600, 800, 423], "x2": [1, 1, 1, 1, 1, 1, 1]})
weights = np.random.random(size=7)
DescrStatsW(data[['x1', 'x2']], weights=weights).corrcoef[0][1]
```
Returns `nan` but should mathematically be 0

Potential fix:
```python
import numpy as np

def corrcoef(self):
    """weighted correlation with default ddof

    assumes variables in columns and observations in rows
    """
    std_outer = np.outer(self.std, self.std)
    with np.errstate(divide='ignore', invalid='ignore'):
        corr = self.cov / std_outer
        corr[std_outer == 0] = 0  # Handle the division by zero case
    return corr
```

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `main`. If your problem has been fixed in an unreleased version, you might be able to use `main` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the main branch of this repository? It helps the limited resources if we know problems exist in the current main branch so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by josef-pkt** [comment]
correlation coefficient is not defined in this case.

There is no unique limit of the correlation coefficient for sequencies of data where at least one variance goes to zero.
(We can construct sequences that converge to any correlation between -1 and 1.)
(Note, regression coefficient is well defined at zero because it divides by only one variance.)


(Aside: Many years ago we had the debate in scipy where for some tests (t-test ?) the 0/0 was not nan based on some ad-hoc intuitive arguments. The decision was to switch to nan because there is no theoretical justification for any specific value, i.e. a specific value can be considered as a limit of a sequence of data, but other limits are also possible.
)

**Comment by addejans** [comment]
You're right. Thank you!
