### ISSUE TITLE
pypy install statsmodel on Windows

### ISSUE THREAD

**Issue by normanlmfung** [statsmodels/statsmodels#9066]
#### Is your feature request related to a problem? Please describe
pypy install statsmodels on Windows

#### Describe the solution you'd like
Problems (and what I tried) I encountered trying to pip install statsmodels in pypy environment described here: https://stackoverflow.com/questions/77501151/pypy-install-statsmodel-on-windows

(I have no issue with statsmodel under conda/cpython environment, but pypy is faster)

**Comment by bashtage** [comment]
The failure are seeing is scopy failing to install.  The only possible route for statsmodels on pypy would be to use conda forge to install numpy, scipy and pandas, then try pip install.  I am pretty sure statsmodela doesn't fully work on pypy since conda forge tries to build it and either the build or the test fails.  

Supporting pypy is not a goal is statamodels at the present given the amount of developer bandwidth.
