### ISSUE TITLE
Save the offset name in `GLM` and results wrapper

### ISSUE THREAD

**Issue by jmahlik** [statsmodels/statsmodels#9100]
#### Is your feature request related to a problem? Please describe
Post model training, it is helpful to know which variable was used as the offset. This aids in post model analysis and deployment.

The offset array is saved and can be accessed after saving the model, but the name of the offset variable is lost when it is a pandas series. The series is [converted to a np.array](https://github.com/statsmodels/statsmodels/blob/ab10165eb897729b50e703b4ea831ae712b53585/statsmodels/genmod/generalized_linear_model.py#L315-L316) which removed the name. Current state, it is difficult to tell which variable may have been used as an offset without tracking it outside the model.

Example use case: Sharing a saved model with a peer. They inspect it to determine what variable was used as the offset in training.

The same may apply to the `var_weights` and `freq_weights` for GLM.

#### Describe the solution you'd like
The model has access on `__init__` to the name of the offset if it is a pandas series. A way to save the offset array's name if it is a series would be wonderful.

Similar to how the endog and exog names can be used in the model summary.

Here's a few ideas I had for how to implement this. Happy to hear if there's a better option.

1. Add an `offset_name` property for GLM
    - Similar to the base models [`endog_names`/`exog_names`](https://github.com/statsmodels/statsmodels/blob/ab10165eb897729b50e703b4ea831ae712b53585/statsmodels/base/model.py#L235-L247)
    - Simple to implement
2. Add it to the `model.data` so it's handled by [`PandasData`](https://github.com/statsmodels/statsmodels/blob/ab10165eb897729b50e703b4ea831ae712b53585/statsmodels/base/data.py#L498)
    - The name could be added back to the offset when making the results wrapper (at least I think that's how it works)
    - I could use some guidance on how to implement this if it is the preferred approach
    - I think it has something to do with the data attrs but it's a bit hard to track down
3. Do not convert to a numpy array if it is a series
    - One could use `model.offset.name` to get at the variable name 
    - Doesn't line up with how the rest of the code works, it expects numpy arrays
    - Likely not a good option
4. User adds `offset_name` attribute to the model class before saving it.
    - Seems like a bad idea, would like support in statsmodels

#### Describe alternatives you have considered
Current workaround is saving the offset name in a separate file, which is not ideal.

#### Additional context
Happy to work on a PR for this.

**Comment by josef-pkt** [comment]
I think currently `1.` is the only option. `2.` would be good but currently the extra arrays are not going through the endog/exog `model.data` handling (at least not in most cases.

We could add a helper function that can be added to the `__init__` as replacement for np.asarray which does asarray plus return additionally the name of the variable if it is available.
This could also be applied to other extra data like exposure and the various weights.

Current extra data like offset, exposure, weights are 1dim. 
For flexibility the helper function could check for and distinguish 1dim and 2dim. In the later case, return individual column names instead of the Series name.

The same as in GLM also applies to discrete models and likely to some other models.
