### ISSUE TITLE
Statsmodels 0.14.2 release (NumPy 2 compat)

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#9209]
I think the 0.14.2 release is essentially ready. It builds all of the [expected wheels on statsmodels-wheels](https://github.com/MacPython/statsmodels-wheels/actions/runs/8676878234).

The release notes are thin.  

Is anything else worth including @josef-pkt?

xref #9194

**Comment by bashtage** [comment]
The interactions anova example seems to be irrevocably broken since the dataset is no longer available.

**Comment by bashtage** [comment]
Available now on PyPI

**Comment by josef-pkt** [comment]
> The interactions anova example seems to be irrevocably broken since the dataset is no longer available.

you could open an issue for this kind of problems, so it does not get lost.

I found the data in the web.archive
https://web.archive.org/web/20170429053043/http://web.stanford.edu/class/stats191/data/salary.table
The current course site has a different salaries dataset.

**Comment by bashtage** [comment]
We should setup a data repo without a clear license just to hold stuff like
this.

**Comment by josef-pkt** [comment]
The problem is that these datasets don't have a clear license, otherwise we could have added them to the statsmodels datasets.

For some it's difficult to find a license. Many of those will not be copyrightable by US law because they are just numbers, but not in other countries like Australia. (discussion was 10 to 15 years ago, and Australia was mentioned as country where you can copyright "public" information like phone book.)

`rdatasets` does not provide a license and AFAIK never got license complaints. 
smdatasets was supposed to be similar without having clarified license for all datasets, just store them for easy access.

(Skipper had asked Greene whether statsmodels can include his book datasets. But he did not want us to include those. And it's not clear whether any of his data sets are even copyrightable.)

**Comment by bashtage** [comment]
I think the risk is low since it will not comingle with statsmdoels and if we do get a.takedown notice, we can just remove.

**Comment by bashtage** [comment]
The alternative would be to put it into a private repo and use an API key to clone the data repo when building docs.  Would be a pain, and also make the docs unrunnable by others.
