### ISSUE TITLE
Add "default_model_infos" property to each result object

### ISSUE THREAD

**Issue by jankatins** [statsmodels/statsmodels#999]
`summary_col` can use that info to generate default values for the result table (of multiple results!).

Also: in https://github.com/statsmodels/statsmodels/pull/915#issuecomment-20814526 @vincentarelbundock  commented:

> If we are set on including a default_model_infos dict of lambda functions in the results instance, then we may consider including a model_info_short (for summary_cols) and model_info_long (for top panel of the summary method).

**Comment by josef-pkt** [comment]
What's the status?   I put an 0.8 milestone to check and close issue. added labels

**Comment by vincentarelbundock** [comment]
I'm not sure adding more information to the models themselves is the way to go here. If we want sensible defaults for ``summary_col``, easiest would be to have a one-line that checks whether the results instance has param and bse values (print out a message otherwise). I think you can close this until there's a better specified idea out there (and demand for it).
